### ISSUE TITLE
作者这是比较忙停止开发了么

### ISSUE THREAD

**Issue by pylist** [go-gost/gost#1]
自从上次说开发3.0版本, 现在一个多月都没更新了

**Comment by ginuerzh** [comment]
目前能投入到gost开发的时间确实不多，未来一段时间也是如此。
3.0还处在开发前期的设计阶段，很多东西还没有确定，所以这是一个长期的过程。
gost 2.x的功能已经很完备，3.0初版只是架构的重新设计和对原有功能的完善和增强，不会引入重大功能。

**Comment by pylist** [comment]
哈哈, 我就是希望能够支持指定出口IP地址就好了, 我用的功能就差这一个, 虽然我也会一点点go, 技术太菜改不动你的代码
