### ISSUE TITLE
socks5: BIND is disabled

### ISSUE THREAD

**Issue by dong3623** [go-gost/gost#101]
服务端10.0.0.11：./gost-linux-amd64-3.0.0-beta.5 -L socks5://:2345
客户端连接后服务端提示："msg":"socks5: BIND is disabled"

客户端：gost-windows-amd64.exe -L rtcp://:8088/:8080 -F socks5://10.0.0.11:2345
客户端连接后提示：
"msg":"route(retry=0) bind on :8088/tcp failed"
"msg":"accept: bind on :8088/tcp failed, retrying in 4s"

哪位大神知道是什么问题吗？

**Comment by ginuerzh** [comment]
SOCKS5需要开启`BIND`命令
```
gost -L socks5://:2345?bind=true
```

**Comment by dong3623** [comment]
> 

@ginuerzh  谢谢，已解决！

**Comment by ellutionist** [comment]
越改越难用
