### ISSUE TITLE
能否重载配置文件

### ISSUE THREAD

**Issue by gundami** [go-gost/gost#105]
rt，我把配置都写在一个文件，修改后只能关掉再启动。能不能像frp重载配置文件，实现热更新配置。

**Comment by Net-Kinger** [comment]
这个实现很简单呀，单独写一个程序封一下gost，启动前判断配置文件有效，有效后启动一个协程定时检测文件有没有被修改，启动一个协程exec拉起Gost传参，检测到修改文件，发signal给后者协程，它kill掉gost再启动。
