### ISSUE TITLE
relay+wss 报错panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhugelail1998** [go-gost/gost#107]
gost  -L tcp://:8080 -F relay+wss://192.168.1.2:12345
连接就报错panic: runtime error: invalid memory address or nil pointer dereference

**Comment by zhugelail1998** [comment]
大佬能看一下什么问题吗

**Comment by ginuerzh** [comment]
最新的代码中已经修复

**Comment by zhugelail1998** [comment]
我就是用的3.0.0.5啊，是你还没有发布吗

**Comment by zhugelail1998** [comment]
> 最新的代码中已经修复

我用的是你发布的最新的beta5，这个问题的修复代码还没有发布新版本吗

**Comment by openwrt2223** [comment]
> > 最新的代码中已经修复
> 
> 我用的是你发布的最新的beta5，这个问题的修复代码还没有发布新版本吗

curl -L https://github.com/openwrt2223/buildgost3/releases/download/$(jq -r '.tag_name' <<< $(curl --silent https://api.github.com/repos/openwrt2223/buildgost3/releases/latest))/gost_android_arm -o gost

**Comment by openwrt2223** [comment]
> > 最新的代码中已经修复
> 
> 我用的是你发布的最新的beta5，这个问题的修复代码还没有发布新版本吗

curl -L https://github.com/openwrt2223/buildgost3/releases/download/$(jq -r '.tag_name' <<< $(curl --silent https://api.github.com/repos/openwrt2223/buildgost3/releases/latest))/gost_linux_amd64 -o gost

**Comment by openwrt2223** [comment]
> > 最新的代码中已经修复
> 
> 我用的是你发布的最新的beta5，这个问题的修复代码还没有发布新版本吗

最新版为beta6
