### ISSUE TITLE
部分系统下无法自动监听IPV4

### ISSUE THREAD

**Issue by HuLian21** [go-gost/gost#108]
甲骨文ubuntu系统下，V3-0.05默认自动监听[::]，在不添加IPV6地址时无法建立连接，log中无任何信息，通过官方docker镜像建立V2版本可正常连接，log中有info信息，显示也是自动监听[::]可正常建立连接。
求问可否手动设置监听IPV4，或有其他解决方案么？

**Comment by ginuerzh** [comment]
如果不设置IP默认会同时监听IPv4和IPv6，IP设置为0.0.0.0则只会监听IPv4。
