### ISSUE TITLE
试用WebAPI遇到的两个问题

### ISSUE THREAD

**Issue by waloyn** [go-gost/gost#11]
问题1，通过API交互进行的配置变更在进程结束后均全部失效，如果保存变更后的配置？
问题2，当前文档显示API已添加身份认证，这个认证信息如何提交？是在header里还是在url里或者其它地方？

**Comment by ginuerzh** [comment]
1. 后面会添加。
2. 认证使用的是HTTP的Basic Auth：https://zh.wikipedia.org/wiki/HTTP%E5%9F%BA%E6%9C%AC%E8%AE%A4%E8%AF%81

**Comment by waloyn** [comment]
> Reference

感谢回复，了解了，第二个问题昨天一直用的是swagger测试，上面的认证入口点不了，后面试着用其它方式，确实可以了。

**Comment by ginuerzh** [comment]
保存接口和swagger认证功能均已添加。

**Comment by waloyn** [comment]
> 保存接口和swagger认证功能均已添加。

还有个小问题，就是返回消息，比如删除不存在的项，除了services可以返回instance not found，其它都是返回ok。
![abc](https://user-images.githubusercontent.com/20416585/153974405-b5beb908-d7fa-4311-a2fa-b76c468f71ab.png)

**Comment by ginuerzh** [comment]
已经统一返回400了
