### ISSUE TITLE
pht无法正确被转发链转发

### ISSUE THREAD

**Issue by uo05** [go-gost/gost#112]
命令举例：

(1) ```./gost -L :1082 -F http+pht://127.0.0.1:1084 -D```

(2) ```./gost -L http+pht://:1084 -D```

执行命令(1)(2)，用curl通过1082端口的代理服务器发出到外部的请求，可以得到正确的结果。

不执行命令(2)，改为用nc监听1084端口，可以接收到一个```GET /authorize HTTP/1.1```的请求。

(3) ```./gost -L :1082 -F http://127.0.0.1:1083 -F http+pht://127.0.0.1:1084 -D```

(4) ```./gost -L http://:1083```

然而，如果改为执行(3)(4)(2)，curl只能接收到503响应。将(2)改为用nc监听1084端口，可以发现接收到了一个CONNECT请求，不符合pht的协议格式，所以无法完成。

这个CONNECT请求形如
```
CONNECT xxx.com:80 HTTP/1.1
Host: xxx.com:80
User-Agent: Go-http-client/1.1
Proxy-Connection: keep-alive
```

正确的行为应当是与没有中转时发送的请求保持一致？

---

**题外话**

存在相当数量的http代理服务器，仅支持对GET/POST等传统请求进行代理，但不支持通过CONNECT或websocket建立数据通道。而pht实现了仅使用传统GET/POST实现双向通信，这使得通过这样的代理建立双向的数据通道成为可能。

是否可以在修复bug的基础上，增加一个功能，使得pht的请求能够以GET/POST等的形式在纯http代理链中转发（可以加选项开启，避免对已有功能产生影响）？

当然，这是有限制的。如果把pht的服务器端可以当作一个支持GET、POST的普通http服务器看待的话，应当只能支持在其之前紧邻的一跳http代理服务器中使用GET/POST而非CONNECT。

例如：
```gost -L :1080 -F http://192.168.0.1:8080 -F http://192.168.0.2:8080 -F pht://192.168.0.3:8080```

（假设192.168.0.1/192.168.0.2上的http代理服务器均不支持CONNECT方法）

这种情况下，因为不能指定192.168.0.1发出一个代理请求（除非192.168.0.2上的代理服务器支持一些特殊格式），无法完成数据通道。

然而，
```gost -L :1080 -F http://192.168.0.1:8080 -F pht://192.168.0.3:8080```

则或许可以通过向192.168.0.1:8080发送GET/POST 192.168.0.3:8080/authorize等请求，完成数据通道。

经过尝试，部分这样的代理服务支持在请求或响应未完全完成时即进行部分转发的功能（而非需要等到完全接收到后才进行转发，但可能要等到缓冲区满）。这或许有助于这样的功能的实用性。

（抱歉我不清楚这样的功能在现有架构下是否容易实现，以及能否得到较广泛应用，只是提出一种可能性作为参考）

---

**题外话2**

pht确实能起到作用（例如搭配cloudflare转发而不走websocket），但似乎存在bug，在多个用户同时使用同一个服务的时候导致带宽大幅降低。不过我没有搞清楚触发条件，以及可能是我当时使用的cloudflare的特性造成的，就不单开issue了。

**Comment by ginuerzh** [comment]
PHT目前是实验性的一个通道，功能还不完善，后面会逐步改善

**Comment by ginuerzh** [comment]
PHT已经支持通过前置节点间接建立连接。
对于前置HTTP代理，目前仅支持CONNECT方法建立连接。
