### ISSUE TITLE
UDP relay on socks5+wss

### ISSUE THREAD

**Issue by jammy551** [go-gost/gost#118]
I have a domain with SSL on nginx and am trying to get udp working on socks5+tls.

nginx listens on MYDOMAIN:443 and forwards /wss traffic to gost-server listening on local port 8080:

[server](https://latest.gost.run/en/reference/handlers/socks5/) gost 3.0.0-beta.6 (go1.19.2 linux/amd64):
`gost -L "socks5+ws://user:pass@127.0.0.1:8080?path=/wss&notls=true&udp=true&bind=true"`

[client](https://latest.gost.run/en/reference/connectors/socks5/):
`./gost-darwin-arm64-3.0.0-beta.6 -L="socks://:1080" -F="socks5+wss://user:pass@MYDOMAIN:443/?path=wss&notls=true"`

TCP packets work fine and I can browse chats in [Telegram desktop](https://desktop.telegram.org/) using the socks5 127.0.0.1:1080 proxy.

For testing UDP, I make calls in Telegram using the same [socks5 proxy ](https://stackoverflow.com/a/49975561/5112995) and it does not work.

Is any specific setting required for making telegram calls work with this setup?

**Comment by ginuerzh** [comment]
The SOCKS5 server on your client side also need to enable the UDP feature:
```
./gost-darwin-arm64-3.0.0-beta.6 -L="socks://:1080?udp=true" -F="socks5+wss://user:pass@MYDOMAIN:443/?path=/wss&notls=true"
```

**Comment by jammy551** [comment]
I tried this command it works only on some networks. Does this mean that UDP packets are not going through the socks5 tunnel? I don't see any UDP connection log on the server side.

The [twilio UDP test](https://networktest.twilio.com/) also fails.

**Comment by jammy551** [comment]
The following steps are required to make telegram calls to go through socks5 proxy:
- Enable socks5 proxy in Telegram Settings -> Data and Storage or Advanced, check "Use Proxy for Calls"
- Set "Use peer-to-peer with" from Settings -> Privacy and Security -> Calls to "Nobody". This will make telegram to [use telegram relay servers](https://core.telegram.org/api/end-to-end/voice-calls) rather than making peer-to-peer connections thus using the socks5 proxy for calls.

I am still not able to make Telegram calls with gost socks5 udp.

**Comment by jammy551** [comment]
> The SOCKS5 server on your client side also need to enable the UDP feature:
> 
> ```
> ./gost-darwin-arm64-3.0.0-beta.6 -L="socks://:1080?udp=true" -F="socks5+wss://user:pass@MYDOMAIN:443/?path=/wss&notls=true"
> ```

I confim that this solution fixes UDP problem. I was able to make Telegram calls when using a proxifier app such as Trojan on android, or shadowrocket on ios and set it to use the socks5 tunnel created by gost in local network, it worked decently.  relay+wss and socks5+wss both worked fine. 

This appears to be a bug in Telegram software that does not honor "use proxy for calls" in socks5 proxy for routing calls even when peer-to-peer connections is disabled and .

**Comment by jammy551** [comment]
The socks5 proxy settings in Telegram has a bug that does not pass Calls:

https://github.com/telegramdesktop/tdesktop/issues/25254

https://github.com/telegramdesktop/tdesktop/issues/23916 

Therefore, currently the only way to use calls on Telegram desktop is to use a VPN that supports IP routing to route [telegram IPs ](https://core.telegram.org/resources/cidr.txt) through the VPN. This way telegram would get connected without any proxy settings and calls will all go through proxy after disabling peer-to-peer calls in Privacy and Security -> Calls.
