### ISSUE TITLE
http3与hosts配置是不是存在问题？

### ISSUE THREAD

**Issue by aa51513** [go-gost/gost#12]
配置片段如下：
hosts:
- name: hosts-0
  mappings:
  - ip: 104.16.77.107
    hostname: my.server.com

chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      hosts: hosts-0
      addr: "my.server.com:443"
      connector:
        type: relay
        auth:
          username: dkaxnu9ng1KvOslo
          password: dyHJop3wATGb4VMW
      dialer:
        type: http3
        metadata:
          authorizePath: /authorize
          pullPath: /pull
          pushPath: /push

日志一直刷这个错误：
{"handler":"socks5","kind":"handler","level":"error","listener":"tcp","msg":"route(retry=0) Get \"https://104.16.77.107:443/authorize\": CRYPTO_ERROR (0x128): tls: handshake failure","service":"service-0","time":"2022-02-18T23:29:27+08:00"}

怀疑是dialer在请求http3之前，直接先把域名替换成了ip，然后才发起http3请求

是有这个可能吗？

我手头没有可以测试http3的工具，所以只能忙猜了，如有理解错误，还望海涵

**Comment by ginuerzh** [comment]
是有这个问题，逻辑上还需要做一些处理

**Comment by ginuerzh** [comment]
最新的代码应该已经解决了这个问题。
