### ISSUE TITLE
两个Gost接力后，TCP请求出现问题，导致VNC协议不可用。

### ISSUE THREAD

**Issue by uf1y** [go-gost/gost#125]
## 场景描述
想要通过服务器做一次中转，在局域网B访问局域网A内的主机VNC服务。
```mermaid
sequenceDiagram
Client A ->> Server:RTCP on Relay
Note right of Server:./gost -L relay://:7777?bind=true
Note right of Client A:./gost -L rtcp://:6900/:5900 -F relay://127.0.0.1:7777
Client B ->> Server:TCP on Relay
Note left of Server:./gost -L relay://:8888
Note left of Client B: ./gost -L tcp://:7900/:6900 -F relay://127.0.0.1:8888
Server -->> Server:5900<--6900<--[...]--6900<--7900
```

## 问题对比
- VNC连接 Server:6900 --> Client A:5900，成功
![image](https://user-images.githubusercontent.com/117698857/200488822-7c643239-2dff-4743-b59f-f86df73db2b0.png)

- VNC连接 Client B:7900-->Server:6900-->Client A:5900，失败
![image](https://user-images.githubusercontent.com/117698857/200488784-ffc1d700-2736-4a82-bd96-c66dfd72e2ff.png)

## 补充
telnet Server:6900，立刻得到返回值
```bash
user@MacBook ~ % telnet 127.0.0.1 6900
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
RFB 003.889
```

telnet Client B：7900，敲一次回车才能得到返回值
```bash
user@MacBook ~ % telnet 127.0.0.1 7900
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

RFB 003.889
```

注意！后面这个请求中，多了一个回车换行符。可能正是因为这个原因，导致VNC连接不上。
经过测试，SSH协议可以使用这种方式中转。为什么VNC不行，求解～

**Comment by ginuerzh** [comment]
VNC服务端在连接建立后会主动发送数据给客户端，relay协议默认是等待接收到客户端数据后才发出请求，可以设置`nodelay`参数来控制：
```
gost -L tcp://:7900/:6900 -F relay://:8888?nodelay=true
```

**Comment by uf1y** [comment]
果然，设置`nodelay`后，确实可以正常连接。到底是文档没看好啊！

https://latest.gost.run/reference/connectors/relay/#_1

**nodelay (bool, default=false)**
默认情况下relay协议会等待客户端的请求数据，当收到请求数据后会把协议头部信息与请求数据一起发给服务端。当此参数设为true后，协议头部信息会立即发给服务端，不再等待客户端的请求。
