### ISSUE TITLE
socks代理不稳定？

### ISSUE THREAD

**Issue by islercn** [go-gost/gost#127]
我把一个https代理转成socks5代理，然后用dns2socks转发代理请求，目前用的v3 rc0

命令：
gost-linux-386 -L socks5://:123 -F https://xxx.com
dns2socks 127.0.0.1:123 10.1.1.1:53 127.0.0.1:55

用goproxy和xray都比较稳定（会偶尔提示DNS错误，但是一直没看到过socks代理服务器连接失败），用gost时dns2socks会有大量的失败，导致目标网站访问不畅，具体如下图所示

![gostsocks](https://user-images.githubusercontent.com/7038562/201047798-d3725410-0fea-493b-bfd4-135286a46043.png)

例如，nslookup一次，会有两条日志：

dns2socks：
2022-11-10 17:37:23   Connecting through SOCKS server has failed: Network unreachable
2022-11-10 17:37:23   Connecting through SOCKS server has failed: Network unreachable

gost：
{"handler":"socks5","kind":"handler","level":"error","listener":"tcp","msg":"route(retry=0) 503 Connect failed","service":"service-0","time":"2022-11-10T09:37:23.604Z"}
{"duration":30038074734,"handler":"socks5","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:123","msg":"127.0.0.1:36614 >< 127.0.0.1:123","remote":"127.0.0.1:36614","service":"service-0","time":"2022-11-10T09:37:23.604Z"}
{"handler":"socks5","kind":"service","level":"error","listener":"tcp","msg":"503 Connect failed","service":"service-0","time":"2022-11-10T09:37:23.604Z"}
{"handler":"socks5","kind":"handler","level":"error","listener":"tcp","msg":"route(retry=0) 503 Connect failed","service":"service-0","time":"2022-11-10T09:37:23.618Z"}
{"duration":30052871426,"handler":"socks5","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:123","msg":"127.0.0.1:36616 >< 127.0.0.1:123","remote":"127.0.0.1:36616","service":"service-0","time":"2022-11-10T09:37:23.618Z"}
{"handler":"socks5","kind":"service","level":"error","listener":"tcp","msg":"503 Connect failed","service":"service-0","time":"2022-11-10T09:37:23.618Z"}

**Comment by ginuerzh** [comment]
503错误是上游https代理返回，请排查https代理服务，从时间上看应该是请求超时。

另外-F https://xxx.com需要加上端口号。

**Comment by islercn** [comment]
是加了端口号的，问题就在于，用gost很大概率会出现超时问题，用goproxy或者xray一直没有观察到，观察时间大概有四五个小时吧，这个就很邪门了
