### ISSUE TITLE
Valid certificate for https

### ISSUE THREAD

**Issue by mgholam** [go-gost/gost#130]
Hi,

Is there a way to have a valid certificate for https:// access via letsencrypt etc.?
```
./gost -L https://:3000
```
using `https://<ipaddress>:3000` as a `https` proxy gives unsecure warning in browser.

**Comment by ginuerzh** [comment]
https://gost.run/en/tutorials/tls/

**Comment by mgholam** [comment]
I found a way to use letsencrypt certs.
