### ISSUE TITLE
Error reading Prometheus: client_error: client error: 404: details: 404 page not found

### ISSUE THREAD

**Issue by uf1y** [go-gost/gost#133]
- gost command

```bash
./gost -L :8080 -metrics=:9000
```
- metrics work

```bash
curl http://localhost:9000/metrics
...
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 1
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```
- Create granfana data source with Prometheus type
URL: `http://localhost:9000/metrics` or `http://localhost:9000`
![image](https://user-images.githubusercontent.com/117698857/203888120-2b000960-37bd-433d-80d0-9ecf8a32574f.png)

Save and Test datasource, get error message:`Error reading Prometheus: client_error: client error: 404: details: 404 page not found`

![image](https://user-images.githubusercontent.com/117698857/203888089-f3f0b381-06fb-4f8f-82ef-651aefd142b5.png)

**Comment by leeaash** [comment]
我好像也遇到了类似的问题，区别是添加data source时不报错，但是explore时选metric会报404，dashboard也不显示任何数据。
![image](https://user-images.githubusercontent.com/78188599/233885290-7a18f93d-1262-4bac-b4da-aaa3216f0cf5.png)
