### ISSUE TITLE
功能需求：多网络接口支持依序尝试多个IP/接口

### ISSUE THREAD

**Issue by tongyuantongyu** [go-gost/gost#134]
https://latest.gost.run/tutorials/multi-homed/ 描述了多网络接口支持，但只支持指定一个IP/接口，在指定接口时仅尝试接口的第一个IP。这导致代理只能连接IPv4或IPv6中的一种。

我提议`interface`参数支持指定多个值，连接时依次尝试使用各值进行连接；对于接口，依次尝试接口上的所有IP。

我自作了一个实现供参考：https://github.com/tongyuantongyu/gost3-core/commit/c248f963954fb6096e9f8ca144de091bafa813ec ，其中还额外包含一个strict标签功能（`!`），控制仅在IP类型不匹配时继续尝试还是发生任何错误时都继续尝试下一个IP/接口。

**Comment by ginuerzh** [comment]
欢迎提交PR。

**Comment by tongyuantongyu** [comment]
> 让代理可以优先使用IPV6访问网站，如果优先使用IPV6访问失败之后再尝试IPV4地址访问

对于单个IPv4+单个IPv6的系统，并不需要诉诸这一功能，Go的默认Dialer就提供了Happy Eyeball支持优先尝试IPv6。这一功能主要针对需要bind到特定地址（当系统拥有多个地址时），并且在失败时回落的特定场景。可以使用`,`分割指定多个ip/interface，Dial时会依序bind到给定地址，尝试连接目标。

**Comment by Ivaneus** [comment]
@tongyuantongyu 十分感谢解答，已经在配置文件实现上述目标，正如你所述happyeyeball的帮助下，在gost中不需要设置域名解析DNS为IPV6优先模式的情况下，多个interface地址中默认就已经优先尝试IPV6，十分感谢，希望作者能把该用法补充在gostV3的使用文档中，方便后来者查阅 @ginuerzh

**Comment by ziyocc** [comment]
> > 让代理可以优先使用IPV6访问网站，如果优先使用IPV6访问失败之后再尝试IPV4地址访问
> 
> 
> 
> 对于单个IPv4+单个IPv6的系统，并不需要诉诸这一功能，Go的默认Dialer就提供了Happy Eyeball支持优先尝试IPv6。这一功能主要针对需要bind到特定地址（当系统拥有多个地址时），并且在失败时回落的特定场景。可以使用`,`分割指定多个ip/interface，Dial时会依序bind到给定地址，尝试连接目标。

请教大佬，两个网卡，tun0和 tun1怎么写？一个失效后自动切换到另一个？谢谢！
