### ISSUE TITLE
终端设备ID

### ISSUE THREAD

**Issue by kkncc** [go-gost/gost#136]
是否可以记录请求终端的设备ID或唯一识别号？

**Comment by ginuerzh** [comment]
目前可以记录客户端的IP，其他信息并不通用，不能保证一定能获取到。

**Comment by Hackxiaoya** [comment]
> 目前可以记录客户端的IP，其他信息并不通用，不能保证一定能获取到。

我觉得这个比较重要，唯一标识，不管任何方式，只要能携带，就能让我们识别呀。

**Comment by ginuerzh** [comment]
具体是什么样的唯一标识，从哪里获取？

**Comment by Hackxiaoya** [comment]
> 具体是什么样的唯一标识，从哪里获取？
可以约定一个字符串，服务端识别 客户端是否把指定的字符串带过来。比如约定一个uuid。什么的。
场景：用户携带uuid 访问A服务器， A服务器转发到B。 B根据uuid来判定 是谁发过来的。

**Comment by Hackxiaoya** [comment]
> 具体是什么样的唯一标识，从哪里获取？

可以约定一个字符串，服务端识别 客户端是否把指定的字符串带过来。比如约定一个uuid。什么的。
场景：用户携带uuid 访问A服务器， A服务器转发到B。 B根据uuid来判定 是谁发过来的。

**Comment by xzycn** [comment]
这种应该比较难做吧？或者说不太可能，至少在做TCP端口转发时是不太可能的。
要么使用一种已经存在的支持存这种trace ID的应用层协议或者gost开发一个，各种代理协议的账密也能当做一种"唯一标识"。
或者使用各种隧道协议，但是也是需要后续的节点都支持，也跟上面说的差不多。

**Comment by moosetk** [comment]
pac 文件不支持账户密码，要是能用设置mac 白名单认证就好了
