### ISSUE TITLE
需要 gost 支持 -D 后台运行

### ISSUE THREAD

**Issue by ogreks** [go-gost/gost#138]
## 需要 gost 支持 -D 后台运行

如下图，我在 windows 上面使用，但是每次启动之后无法后台运行，这样的操作很糟糕
![image](https://user-images.githubusercontent.com/34636593/205544222-5a02b1c0-55d0-47cd-8f66-baf193e2e324.png)

**Comment by wangzhengzhen** [comment]
在linux中可以用nohup，windows中我用的winsw创建服务。如果自带后台运行设置是会方便很多。
