### ISSUE TITLE
tun ipv6 ping 不了

### ISSUE THREAD

**Issue by aeeq** [go-gost/gost#139]
![图片](https://user-images.githubusercontent.com/8926331/205544594-9e800a7b-b6c7-4c9a-b6c0-8c61f6452bbb.png)

按照这个启动，ipv6 的转发不了

**Comment by aeeq** [comment]
试了 net=fd::1/64 ,单独设置 ipv6 可以，能不能同时设置 ipv4 ipv6

**Comment by ginuerzh** [comment]
rc2版本可以通过`net`来指定多IP:
```
gost -L tun://:8421?net=192.168.123.1/24,fd::1/64
```
