### ISSUE TITLE
windows版应该有个bug

### ISSUE THREAD

**Issue by gmhejob1** [go-gost/gost#14]
服务端运行同样一条规则命令，WINDOWS版做服务端监听端口转发数据，客户端直连这个端口传数据是失败的，换作linux版做服务端就没事。。。如果WIN上没有特别设置，那这算不算一个BUG。  2.0和3.0都试了，都有这问题。   WIN版本做服务端会有如下提示
![image](https://user-images.githubusercontent.com/23410845/156290350-3d2ee5b9-edd1-488d-beb8-747f26a88775.png)

**Comment by ginuerzh** [comment]
具体的使用命令配置和日志。
