### ISSUE TITLE
使用Gost穿透专业跳板机的可能性

### ISSUE THREAD

**Issue by imyhxy** [go-gost/gost#147]
使用Gost有几年了，感谢开发者的无私贡献。

现在遇到这样一个使用需求，向开发者请教实现的可能性：
  * 服务器S，跳板机B，客户机C
  * S和C由用户控制
  * B是专业跳板机，当C要访问S时，要向B申请单次服务，B会提供一个帐号密码（动态），用户用其登录跳板机，登录成功后B会直接打开登录S的程序，用户再次输出S的帐号密码登录S

由于S和C可以由用户控制，有没有可能通过修改Gost，在C上用Gost访问B，由B去访问S上经过修改的Gost程序，最终实现代理上网。

这里还有几个限制：
  * 向B申请使用服务时，要指定访问S的端口和服务类型（SSH，VCN，SFTP）
  * B上不能执行任何程序，在登录B后，B会根据申请的服务信息，立刻打开一个连接程序让你登录S
  * B还会对是否登录成功S进行验证

修改思路：
  * C上的Gost通过SSH连接B，监听B返回的Prompt信息，并提供S的帐号密码
  * S上的Gost监听B发来的SSH认证请求，并给予成功登录信号
  * 之后C和S通过SSH协议传输数据包

请问通过修改Gost实现以上需求的可能性有多大，以及主要修改的模块是哪个，如果能提供一些修改思路也感激不尽。:heart:

**Comment by imyhxy** [comment]
@egg1234 跳板机不允许流量转发，因此通过现有的Gost确实无法实现代理。我是想着通过修改Gost，让C和S上的Gost模拟SSH的登录认证流程，欺骗跳板机，让它误以为两端是SSH程序，然后C和S再通过SSH协议进行数据包的交换。

**Comment by imyhxy** [comment]
是的，但是任何数据都可以编码成字符串，然后通过ssh进行传输，只要双方遵循相同的编解码方式

**Comment by woodlyer** [comment]
看我这个可以不。
S是服务器，提供各种服务
B是跳板机， 对不同的用户开启不同的relay服务， 带密码
C采用B的提供的密码连接B，再访问S。  假设C不能直接访问S的服务。

与题目相差的，就是B上没有实现自动化。
```
S:  :22  :80  
B: ./gost -L relay://user1:pass1@:6001    
   ./gost -L relay://user2:pass2@:6002 
C1: ./gost -L tcp://:22/ipS:22  -F relay://user1:pass1@ipB:6001
       ssh root@localhost:22 # 访问S上的ssh
C2: ./gost -L tcp://:80/ipS:80 -F relay://user2:pass2@ipB:6001
       curl localhost:80  # 访问S上的http
```
