### ISSUE TITLE
gost installation

### ISSUE THREAD

**Issue by abraham-sah** [go-gost/gost#154]
I really have problems installing and running gost on my server.

But I couldn't install it with the binary file itself.
I can't find it on Ubuntu official repositories. Actually I expected that but still gave it a try.Should I compile it?

Should I compile it?

I extract it through many ways like gunzip and gzip or even 7zip.
Then tried to make it executable through the chmod command.But it doesn't run.So I think I have to compile it to deb and install it through "install" or "checkinstall" commands.
Right?

And I also didn't find any documentation about how to install or compile gost through its binary.

I also installed it through docker script written in welcome page of your documentation.

But honestly its my first time using docker and now after installation I don't know how to run it by docker.

Can you put a little more time on your wiki part....

Since as a newbie server user I don't get it at all.

**Comment by Coffee-kitten** [comment]
you should learn how to use Linux first

**Comment by xzycn** [comment]
Have you read this?
https://gost.run/en/#installation
