### ISSUE TITLE
ICMP协议到容器的需求讨论

### ISSUE THREAD

**Issue by shadu120** [go-gost/gost#155]
我的绝大多数gost进程运行在容器中，因为通过UDP/TCP可以exposed到外部。
现在有个新的需求，在容器中的gost运行方式为ICMP：`./gost -L icmp://:0`
想问下，这种情况在主机测该如何做操作，才能让客户端的ICMP进入容器，从而让gost解析？

谢谢。

**Comment by ginuerzh** [comment]
可以试试主机网络模式(--network=host)。

**Comment by shadu120** [comment]
开工大吉！
测试过了，得确成功可行。

tips:`gost客户端使用icmp协议，执行时需要用root权限。`

参考
```
Host : 与宿主机共享网络名称空间/网络协议栈，IP 共享、端口范围共享.
Container: 多个容器之间共享一个networknamespaces，多个容器公用一个IP和端口范围
None : 自 闭空间，无网卡，无需网络连接
Bridge: 桥接， 默认模式，在不指定网络模式的情况下创建容器，默认使用此模式, 通过Veth对连接容器与docker0网桥，网桥分配IP给容器,同时docker0作为“局域网”内容器的网关，最后和宿主机网卡进行通讯, 同时，通过IPtables规则将容器IP/port映射出去，用于与宿主机网卡交互
```
- https://aiops.com/news/post/6403.html
- https://blog.csdn.net/hechaojie_com/article/details/83551985
- https://www.51cto.com/article/708088.html
