### ISSUE TITLE
V3 version and whether the customized content of DefaultUserAgent and DefaultProxyAgent has been removed

### ISSUE THREAD

**Issue by Noa886** [go-gost/gost#158]
We can easily modify the contents of DefaultUserAgent and DefaultProxyAgent in the code of gost.go in the v2 version, but no similar code is seen in the v3 version. The reason for modifying this content is that GFW has recognized gost in this respect and needs to modify the default header. Do you still support modification now?

**Comment by Noa886** [comment]
Is there no gost in the default header in v3?
Because we have seen the version information, we don't know whether there is still a case where the default header displays gost.

**Comment by ginuerzh** [comment]
For HTTP/HTTP2/Websocket Requests, you can customize the HTTP headers through the header option in the metadata.
```
metadata:
  header: 
    User-Agent: "Go-http-client/1.1"
    foo: bar
```

**Comment by Noa886** [comment]
thanks ginuerzh
