### ISSUE TITLE
反馈一个已经持续好几年的断流BUG

### ISSUE THREAD

**Issue by PHCSJC** [go-gost/gost#16]
其实在2020年就反馈过：
https://github.com/ginuerzh/gost/issues/627
只是一直没解决，看大佬在开发3.0，希望大佬顺便解决了。
简单说就是断流问题，v2.3-2.6.1版本不断流，后面到2.11.1全部断流

具体重现方法：
环境：amd64或arm64都可以，都试过
服务端：kcp模式
客户端：redirect+kcp模式
kcp参数默认就可以
测试方法：iptables将vps的ssh端口redirect到gost的端口，然后ssh连接vps（此时就是走的gost通道连到vps服务器上了），连接成功后，保持不动就可以了，大概1-10分钟不等这个ssh连接就被断开了

另外我测试过：
ss+kcptun+udp2raw，不会断
gost(<=2.6.1) redirect+kcp+udp2raw，不会断
gost(>2.6.1) redirect+kcp+udp2raw，会断
gost redirect+relay+kcp+udp2raw，会断

**Comment by PHCSJC** [comment]
gost-v2.6.1的redirect+ss+kcp模式，配合udp2raw，不会断

**Comment by flynaj** [comment]
gost 的kcp 本来就有tcp 参数，不需要那个udp2raw，还有kcp 本来就是加密，不用在套其它加密协议。很多路由器检测不到数据流动会断开链接。建议加个全局心跳包。可以彻底解决问题。

**Comment by PHCSJC** [comment]
@flynaj  
1.udp2raw比kcp自带的伪装tcp要稳的多的多，已经测试过几百次
2.我的kcp里的配置加密就是none
3.多路由器检测不到数据流动会断开链接，这个就更扯了
4.心跳包kcp默认就有

**Comment by cod1ingcoding** [comment]
@PHCSJC 
试着在服务器端的/etc/ssh/sshd_config最后添加
```
ClientAliveInterval 60
ClientAliveCountMax 3
```
两行配置，然后`systemctl restart sshd`试试？

**Comment by viponedream** [comment]
大佬, 你现在怎么做的呢? 我也是发现各种协议都会断流.

**Comment by PHCSJC** [comment]
@viponedream gost v3 最新版，已经不断流了

**Comment by viponedream** [comment]
> @viponedream gost v3 最新版，已经不断流了

你是怎么用的呢?  我现在这么用,还是断流,1,2个小时就一次.

本地     gost -L tcp://:12515 -F forward+tls://服务器IP:19515
服务器  ./gost -L tls://:19515/:12515

**Comment by viponedream** [comment]
> @viponedream gost v3 最新版，已经不断流了

**Comment by viponedream** [comment]
> 

你是怎么用法的? 能不能看一下你的用法?

**Comment by PHCSJC** [comment]
ss+kcp，更套一个udp2raw
