### ISSUE TITLE
是否可以考虑允许用户自定义应用Banner信息？

### ISSUE THREAD

**Issue by shadu120** [go-gost/gost#160]
随便一个扫描器就知道目标服务器是gost……

> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 407 Proxy Authentication Required
< Proxy-Authenticate: Basic realm="gost"
< Content-Length: 0

这个很不利于隐藏，非常理解对copyright的标识，但是tunnel工具本身就是为了隐身这一主要需求吧。希望未来考虑下这方面的机制。

**Comment by ginuerzh** [comment]
HTTP/HTTP2已经添加`authBasicRealm`选项来设置realm
```
gost -L http://:8080?authBasicRealm=Realm
```
