### ISSUE TITLE
openwrt使用报错请教

### ISSUE THREAD

**Issue by laga-bu** [go-gost/gost#161]
本小白J1900软路由安装openwrt，下载linux-386那个版本，在ttyd终端运行报错，代码如下：
./gost3-x86: line 1: syntax error: unexpected "("
提示语法错误，请问是我版本下载不对吗？应该下载哪个版本？谢谢各位大佬，祝各位大佬兔年吉祥！万事大吉！

**Comment by ginuerzh** [comment]
可以试试[amd64版本](https://github.com/go-gost/gost/releases/download/v3.0.0-rc.3/gost-linux-amd64-3.0.0-rc.3.gz)。

**Comment by laga-bu** [comment]
> 可以试试[amd64版本](https://github.com/go-gost/gost/releases/download/v3.0.0-rc.3/gost-linux-amd64-3.0.0-rc.3.gz)。

已解决，谢谢大神指点！
