### ISSUE TITLE
udp proxy for wireguard not work

### ISSUE THREAD

**Issue by vjeson** [go-gost/gost#166]
.the new version not worked for udp proxy
./gost -L udp://:12280/118.136.33.11:12280

error message

{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2023-02-08T14:12

but with the old version gost ,it works well.

**Comment by ginuerzh** [comment]
You need to enable `keepAlive` option, please refer to https://gost.run/en/tutorials/port-forwarding/#udp.

**Comment by alou-S** [comment]
Yup that works in my case. Guess you could close the issue

**Comment by trishareyna70** [comment]
@alou-S Good

**Comment by ceozero** [comment]
keepAlive=true
很好用。
