### ISSUE TITLE
端口转发到家宽的问题

### ISSUE THREAD

**Issue by ruixingchen** [go-gost/gost#168]
我想将服务器的某个端口转发到我的家用宽带(有公网IP)，家用宽带每隔一段时间IP会发生变化，我希望每次IP发生变化之后，GOST可以无缝自动切换，请问这样的需求GOST可以实现么

**Comment by ginuerzh** [comment]
如果你的服务器有公网IP，那可以通过在家用网路中使用远程端口转发(rtcp,rudp)来实现，这样就不会受IP变化的影响了。

**Comment by kssion** [comment]
远程端口转发，服务器端需要添加 `bind=true` 才能绑定端口
```sh
gost -L socks5://:1080?bind=true
```

**Comment by xqexqe** [comment]
services:
- name: service-0
  addr: :服务器对外端口
  handler:
    type: tcp
  listener:
    type: tcp
  forwarder:
    nodes:
    - name: target-0
      addr: 你的DDNS域名:端口
--------------------------
我是这样写了一个yml

**Comment by ginuerzh** [comment]
> > 远程端口转发，服务器端需要添加 `bind=true` 才能绑定端口
> > ```shell
> > gost -L socks5://:1080?bind=true
> > ```
> 
> 感谢感谢，那我换回V3再试试，另外我想请问一下，端口转发的数据会自动协商加密么？

两端如果都是gost，会协商加密。
