### ISSUE TITLE
远程端口转发提示：accept：bind unsupported

### ISSUE THREAD

**Issue by qianhd** [go-gost/gost#170]
hello

版本：3.0-rc5

服务端：gost -L quic://:9876
客户端：gost -L rtcp://:12345/:12345 -F quic://x.x.x.x:9876
客户端日志提示 accept: bind unsupported。如果客户端换成socks+quic就正常，不理解为什么。

按照个人理解，客户端使用gost -L rtcp://:12345/:12345 -F forward+quic://x.x.x.x:9876应该也是支持，但实际不行。谁能解答一下，不胜感激。

**Comment by ginuerzh** [comment]
rtcp转发链最后一个节点必须是relay或socks5。

**Comment by qianhd** [comment]
> rtcp转发链最后一个节点必须是relay或socks5。

`注意: TCP远程端口转发使用了socks5 bind协议，所以转发链的末端(最后一个-F参数)一定要是socks5类型； UDP远程端口转发使用了UDP-over-TCP，所以转发链的末端(最后一个-F参数)一定要是gost socks5类型。`
在v2的文档中找到了
https://latest.gost.run/blog/2016/rtcp/
