### ISSUE TITLE
在越狱的ios 系统上可以直接命令行运行 gost 吗？

### ISSUE THREAD

**Issue by moosetk** [go-gost/gost#176]
是用 gost_3.0.0-rc6_darwin_arm64 版本吗？有没有谁测试过？

**Comment by kssion** [comment]
可以自己编译iOS版本，经测试可以运行。但是你必须制作deb包，然后使用dpkg进行安装。

<img width="715" alt="截屏2023-03-20 22 20 17" src="https://user-images.githubusercontent.com/12656299/226369060-e93d444d-3619-4964-a82d-51c28382eaed.png">
