### ISSUE TITLE
relay: unknown command

### ISSUE THREAD

**Issue by shzxm** [go-gost/gost#178]
services:
- name: service-0
  addr: '[::0]:1234'
  handler:
    type: relay
  listener:
    type: tls

报错
{"handler":"relay","kind":"service","level":"error","listener":"tls","msg":"relay: unknown command","service":"service-0","time":"2023-02-23T13:45:07.613Z"}

所使用客户端为shadowrocket（relay模式（gost2.11+relay协议）+gost插件）

**Comment by shzxm** [comment]
gost_3.0.0-rc5_linux_arm64

gost_3.0.0-rc5_linux_arm64

gost_3.0.0-rc6_linux_armv7

**Comment by ginuerzh** [comment]
rc7已修复
