### ISSUE TITLE
[BUG] gost3/relay dont compat gost2/relay

### ISSUE THREAD

**Issue by honwen** [go-gost/gost#183]
#### SERVER
> gost 3.0.0-rc.5 (go1.20 linux/amd64)

`gost3 -L=relay://:1080`

#### client1(OK)
> gost 3.0.0-rc.5 (go1.20 linux/amd64)

`gost3 -L=:1081 -F=relay://127.0.0.1:1080`
`curl --socks5-hostname 127.0.0.1:1081 g.cn`

#### client2(NOT OK)
> gost 2.11.5 (go1.19.2 linux/amd64)

`gost -L=:1081 -F=relay://127.0.0.1:1080`
`curl --socks5-hostname 127.0.0.1:1081 g.cn`

**Comment by honwen** [comment]
anyone reproducing?

**Comment by ginuerzh** [comment]
Try rc7

**Comment by honwen** [comment]
it works
