### ISSUE TITLE
dns代理加密问题

### ISSUE THREAD

**Issue by vjeson** [go-gost/gost#189]
请教
查看了文档https://gost.run/tutorials/dns/
文档里面DNS代理模式 支持tls，这个是指，实际解析的dns 比如1.1.1.1支持tls协议吧？
比如 如下命令
gost -L dns://:10053/1.1.1.1,tls://1.1.1.1:853?mode=tls

mode这里可以设置成tls么？ 如果mode设置成tls,客户端需要怎么设置才能正确解析？
测试过mode=udp正常解析，改成tls后，不知道客户端还需要怎么设置，才能正确解析域名

 本地代理端口10053上面可以加认证么？
客服端可以再转发一层，实现对设备dns透明解析么？
目地就是对服务器上面10053的dns代理进行加密或者认证，防止滥用

**Comment by ginuerzh** [comment]
DNS协议本身不支持认证，你可以通过端口转发来对传输的数据加密和设置认证：

```
gost -L udp://:10053/IP:53 -F relay+tls://user:pass@SERVER_IP:PORT
```
