### ISSUE TITLE
http报错

### ISSUE THREAD

**Issue by bfgngfnfgmnggn** [go-gost/gost#191]
错误日志
{"handler":"http","kind":"service","level":"error","listener":"tcp","msg":"malformed HTTP request \"\\x05\\x02\\x00\\x02\"","service":"service-0","time":"2023-03-18T12:33:50.186Z"}
{"handler":"http","kind":"handler","level":"error","listener":"tcp","local":"172.17.0.2:1080","msg":"malformed HTTP request \"\\x05\\x02\\x00\\x02\"","remote":"123.112.0.0:37824","service":"service-0","time":"2023-03-18T12:33:50.187Z"}

http命令
docker run -d --name socksProxy --restart=always -p 1080:1080 gogost/gost -L "http://:1080?admission=~152.67.0.0"

socks5正常

**Comment by ginuerzh** [comment]
错误日志已经告诉你原因了

**Comment by bfgngfnfgmnggn** [comment]
感谢回复,明白了有干扰
