### ISSUE TITLE
shall we use the quic of hysteria?

### ISSUE THREAD

**Issue by woodlyer** [go-gost/gost#193]
hysteria is based on quic and is very fast.
Because the quic is modified.  
https://github.com/apernet/quic-go  
shall we change default quic-go to this version to make quic faster?

**Comment by ginuerzh** [comment]
QUIC and Hysteria are not the same, we can not simply replace.

**Comment by woodlyer** [comment]
quic of gost is very slow.

**Comment by woodlyer** [comment]
hysterial use replaced version of quic-go, Maybe gost can also use this modified quic-go

https://github.com/apernet/hysteria/blob/master/app/go.mod
```
replace github.com/quic-go/quic-go => github.com/apernet/quic-go v0.32.1-0.20230226201325-e07aae1a800b
```

**Comment by happyharryh** [comment]
You can try my branch of gost V2: https://github.com/happyharryh/gost/tree/hysteria-quic
```
# Build
git clone -b hysteria-quic https://github.com/happyharryh/gost.git
cd gost
go build ./cmd/gost

# Server
./gost -L='quic://127.0.0.1:8080?send_mbps=100'

# Client
./gost -L=auto://127.0.0.1:1080 -F='quic://127.0.0.1:8080?send_mbps=20&keepalive=true'
```
This branch only implements the basic transporter of the Hysteria-QUIC and does not include other encryption features of Hysteria. The data transmission rate is fixed based on the server-side/client-side configuration, rather than being negotiated during the connection establishment.

**Comment by woodlyer** [comment]
@happyharryh 
In my test, hysteria is much faster than gost with quic.  
Is your gost faster than  original quic?

**Comment by happyharryh** [comment]
> @happyharryh In my test, hysteria is much faster than gost with quic. Is your gost faster than original quic?

@woodlyer Yes. My purpose of creating this branch is to speed up the original QUIC in the gost. In fact, I made modifications to the code of gost referred to the Hysteria code.

**Comment by woodlyer** [comment]
@happyharryh  good job.

**Comment by CloudPassenger** [comment]
Thanks to the contributors to this feature, I forked a v3 version of gost to implement Brutal and BBR congestion control.

The repo is: https://github.com/CloudPassenger/gost

## Enhanced Features
- QUIC: Default to BBR, with [Brutal](https://hysteria.network/zh/docs/misc/Hysteria-Brutal/) fixed-rate congestion control by [Hysteria](https://hysteria.network/)
- REALITY: Support Transport Layer [REALITY](https://github.com/XTLS/REALITY) by [Xray](https://xtls.github.io/), can be used as server and client, supports multiplexing
- Forward: Traffic forwarding supports Proxy Protocol to pass client IP (TCP only)

The purpose of my Fork is to improve the reliability of cross-border traffic trasnfer (aka. climb over the wall/翻墙), which conflicts with the author's intent to provide cloud-native tunnel services. So I won't be submitting a Pull Request to request a merge.

Thanks again to the author and the many contributors of this project 🙏

**Comment by onlineie** [comment]
> Thanks to the contributors to this feature, I forked a v3 version of gost to implement Brutal and BBR congestion control.
> 
> The repo is: https://github.com/CloudPassenger/gost
> 
> ## Enhanced Features
> * QUIC: Default to BBR, with [Brutal](https://hysteria.network/zh/docs/misc/Hysteria-Brutal/) fixed-rate congestion control by [Hysteria](https://hysteria.network/)
> * REALITY: Support Transport Layer [REALITY](https://github.com/XTLS/REALITY) by [Xray](https://xtls.github.io/), can be used as server and client, supports multiplexing
> * Forward: Traffic forwarding supports Proxy Protocol to pass client IP (TCP only)
> 
> The purpose of my Fork is to improve the reliability of cross-border traffic trasnfer (aka. climb over the wall/翻墙), which conflicts with the author's intent to provide cloud-native tunnel services. So I won't be submitting a Pull Request to request a merge.
> 
> Thanks again to the author and the many contributors of this project 🙏

There seems to be something wrong with your branch. After running for a while (about 4 to 5 hours), it will be unable to connect.
I checked that the gost process is still alive and there is no error log output..

**Comment by CloudPassenger** [comment]
> > Thanks to the contributors to this feature, I forked a v3 version of gost to implement Brutal and BBR congestion control.
> > The repo is: https://github.com/CloudPassenger/gost
> > ## Enhanced Features
> > 
> > * QUIC: Default to BBR, with [Brutal](https://hysteria.network/zh/docs/misc/Hysteria-Brutal/) fixed-rate congestion control by [Hysteria](https://hysteria.network/)
> > * REALITY: Support Transport Layer [REALITY](https://github.com/XTLS/REALITY) by [Xray](https://xtls.github.io/), can be used as server and client, supports multiplexing
> > * Forward: Traffic forwarding supports Proxy Protocol to pass client IP (TCP only)
> > 
> > The purpose of my Fork is to improve the reliability of cross-border traffic trasnfer (aka. climb over the wall/翻墙), which conflicts with the author's intent to provide cloud-native tunnel services. So I won't be submitting a Pull Request to request a merge.
> > Thanks again to the author and the many contributors of this project 🙏
> 
> There seems to be something wrong with your branch. After running for a while (about 4 to 5 hours), it will be unable to connect. I checked that the gost process is still alive and there is no error log output..

Thanks for the feedback. Let me check this issue and try to resolve it.

**Comment by chenxudong2020** [comment]
> 感谢此功能的贡献者，我分叉了 gost 的 v3 版本来实现 Brutal 和 BBR 拥塞控制。
> 
> 存储库为：https://github.com/CloudPassenger/gost
> 
> ## 增强功能
> * QUIC：默认为 BBR，由 [Hysteria](https://hysteria.network/) 提供[残酷](https://hysteria.network/zh/docs/misc/Hysteria-Brutal/)的固定速率拥塞控制
> * 现实：支持 [Xray](https://xtls.github.io/) 的传输层 [REALITY](https://github.com/XTLS/REALITY)，可用作服务器和客户端，支持多路复用
> * 转发：流量转发支持代理协议传递客户端 IP（仅限 TCP）
> 
> 我的 Fork 的目的是为了提高跨境流量传输（又名 climb over the wall/翻墙）的可靠性，这与笔者提供云原生隧道服务的意图相冲突。所以我不会提交 Pull Request 来请求合并。
> 
> 再次感谢作者和本项目🙏的许多贡献者

v3不支持远程端口转发

**Comment by chenxudong2020** [comment]
> 感谢此功能的贡献者，我分叉了 gost 的 v3 版本来实现 Brutal 和 BBR 拥塞控制。
> 
> 存储库为：https://github.com/CloudPassenger/gost
> 
> ## 增强功能
> * QUIC：默认为 BBR，由 [Hysteria](https://hysteria.network/) 提供[残酷](https://hysteria.network/zh/docs/misc/Hysteria-Brutal/)的固定速率拥塞控制
> * 现实：支持 [Xray](https://xtls.github.io/) 的传输层 [REALITY](https://github.com/XTLS/REALITY)，可用作服务器和客户端，支持多路复用
> * 转发：流量转发支持代理协议传递客户端 IP（仅限 TCP）
> 
> 我的 Fork 的目的是为了提高跨境流量传输（又名 climb over the wall/翻墙）的可靠性，这与笔者提供云原生隧道服务的意图相冲突。所以我不会提交 Pull Request 来请求合并。
> 
> 再次感谢作者和本项目🙏的许多贡献者

感谢不知道为啥 通过远程端口转发 报错 rtcp
