### ISSUE TITLE
webapi是否支持https

### ISSUE THREAD

**Issue by gmsj0001** [go-gost/gost#194]
HTTP BasicAuth是明文的，如果想上公网通常是必须配合HTTPS使用
目前看下来是不支持直接配置的，需要手动添加一条tls到tcp的tunnel

**Comment by telanflow** [comment]
nginx反向代理可以解决

**Comment by ginuerzh** [comment]
WebAPI不再额外增加TLS支持，可以通过TLS转发或反向代理来实现。
