### ISSUE TITLE
[question]当我使用时 内存占用很高

### ISSUE THREAD

**Issue by woshikedayaa** [go-gost/gost#197]
我使用的是因为我在国内的服务器某些服务要java运行且需要访问外网必须要socks5 我就使用 gost -L :1080
来开启一个socks5代理 但是日志疯狂输出在国内的java主机连接后 导致很快内存就慢了 我使用danted同样也有这样的问题 有什么解决办法吗

**Comment by woshikedayaa** [comment]
抱歉昨天晚上太困了没讲清楚 这里讲讲怎么复现和具体问题
##复现
一个国内服务器，一个在国外的服务器
国外服务器:screen -S GOST ./gost -L :1080
国内服务器跑一个jar(会向外网发送请求的)
这里我就以minecraft的服务端为例
启动命令:java -DsocksProxyHost=xx.xx.xx.xx -DsocksProxyPort=1080 -Xmx8g -Xms4g -jar server.jar nogui

启动过后会向我代理端服务器发送大量请求 以至于到后面被操作系统kill

后面我换成了danted来开启socks5 同样存在此问题
同时内存占用是不断上升的 而终端也是不断在打印日志以很快的速度
##问题
想问是socks本身这样 还是java的socks启动有问题 或者其他原因 也想问怎么解决

##环境
java:oracle jdk17
system:ubuntu20.04lts
gost:v3.0 rc5

**Comment by ginuerzh** [comment]
内存使用和很多因素有关，正常情况下和连接数关系比较大。

你可以在服务器上查看一下连接情况：
```
netstat -tnp | grep 1080
```
公网代理务必添加认证，否则很有可能会被滥用。

**Comment by woshikedayaa** [comment]
谢谢，已经解决了 就是端口这玩意不能用默认的 就是被滥用了
