### ISSUE TITLE
我们V3这个WEB UI什么时候上线啊

### ISSUE THREAD

**Issue by q592850** [go-gost/gost#199]
我们V3这个WEB UI什么时候上线啊

**Comment by ginuerzh** [comment]
没有确切日期

**Comment by NFEL** [comment]
@ginuerzh  Hey, I've been using gost for a few months and i found it quite satisfying how you handled eveything!

I would like to collaborate on adding web-ui to project .

**Comment by ginuerzh** [comment]
@NFEL You are welcome to join this community, can you share some ideas or prototypes?

**Comment by NFEL** [comment]
Sweet
Well, I had an admin panel in mind which: 

## Configuration 
- tracks the changes of config file
- live update using api
- export config
- import config
- merge multiple configs into one
- visualize data flow with graph generation 

## Tracking 
- use recorder options to
 - show usefull data in a dashboard 


These are some of things I was going for

If it sounds interesting to you, I like to share a design so then we can generate some go template and use some renderer engine to make it an app while everything is still in golang
Or
Use react or vuejs
