### ISSUE TITLE
能整合下clash那种通过不同IP端口不同域名什么的走不同节点或者直连的功能不

### ISSUE THREAD

**Issue by nic8888dsf** [go-gost/gost#2]
能整合下clash那种通过不同IP端口不同域名什么的走不同节点或者直连的功能不..现有的那个白名单黑名单做不到类似的功能呀..

**Comment by f4nff** [comment]
没啥必要，直接用clash那玩意不就得了，clash就是一个redir的扩展，

**Comment by cod1ingcoding** [comment]
没有必要，gost重点在`协议层(Protocol)和传输层(Transport)`

**Comment by ArcCal** [comment]
直接用clash不就得了
