### ISSUE TITLE
Gost log files?

### ISSUE THREAD

**Issue by italy2010** [go-gost/gost#201]
hello i installed gost with snap commands.
my ubuntu disk space was 4 gb full and 25 gb free...
after 20 day my ubuntu disk space is full... i just installed gost ...why my disk space is full? is it log files? how i can delete them?
thanks

**Comment by ginuerzh** [comment]
You can enable log rotation:
https://gost.run/en/tutorials/log/#rotation

**Comment by italy2010** [comment]
i use gost with this command
nohup gost -L=forward+ssh://root:plus2027@10.10.10.102550 &

how i can ignore save log with this command?

**Comment by ginuerzh** [comment]
The environment variable `GOST_LOGGER_LEVEL` can be used to set the log level, the `fatal` level is analogous to discarding the log:
```
GOST_LOGGER_LEVEL=fatal gost -L=forward+ssh://root:1234@10.10.10.10:2550
```

**Comment by alireza-mrx** [comment]
نه مسعود جان هنوز لاگ ثبت میکنه
راه حلی پیشنهاد میکنم احتمالا حل میکنه
![Capture111111111111](https://github.com/go-gost/gost/assets/161974832/cb4f15e5-4e16-48b6-92fb-42ffaa8ed03a)
