### ISSUE TITLE
请教一下反向代理的问题

### ISSUE THREAD

**Issue by changeche01** [go-gost/gost#202]
感谢大神，非常棒，通过blog 中的案例设置，我已经实现了家里NAS的远程访问web页面了。

先说问题：反向代理是否能实现非web 类型的隧道。 （我想把socket 端口也用类似2023年blog 里的方式在公网实现访问。）

-----------------------
场景：
因为家里网络限制，宽带没有公网ip，所以我用的反向代理中转访问我家里的NAS。并且公网vps 只能开少数的几个端口。所以我参考了blog里只设置案例。并能成功实现了。
访问的架构如下：
访问客户端（无公网IP） ---> 云主机vps （有公网IP）  <---  家里的NAS（无公网IP）

通过ingress 表来区分不同的NAS 页面。
现在我想把我的几个非web的应用也共享出来。

那么，想问下反向代理是否只能实现web 的隧道。能否实现非web 类型的也通过同一个端口访问，设置不同的ingress 访问策略来建立隧道。

**Comment by ArcCal** [comment]
所以呢，blog在哪儿呢

**Comment by changeche01** [comment]
在 项目 wiki 页面里有博客。

https://gost.run/

Arc ***@***.***> 于2023年4月7日周五 14:50写道：

**Comment by ginuerzh** [comment]
由entryPoint进入的流量是通过嗅探请求中的主机名来与Ingress路由进行匹配，因此仅支持Web流量(HTTP/HTTPS)。
对于非Web流量(TCP/UDP)，有两种方式：
1. 通过[远程端口转发](https://gost.run/tutorials/port-forwarding/#_4)将服务映射到服务端的一个端口上，如果端口是开放的则公网可以直接访问。
2. 使用[私有隧道](https://gost.run/tutorials/reverse-proxy-advanced/#_4)，服务端不需要暴露端口，而是在访问端监听端口作为入口点，可以认为端口是通过服务器间接映射到了访问端。可以参考[这个示例](https://gost.run/tutorials/reverse-proxy-advanced/#-iperf)。

**Comment by changeche01** [comment]
感谢大神回复。

之前看文档 私有隧道没看懂是什么意思， 现在想下 好像确实可以实现这个需求。

我速度试下。

谢谢！


ginuerzh ***@***.***> 于2023年4月7日周五 18:51写道：

**Comment by changeche01** [comment]
感谢大神。

用私有隧道模式，能满足我的需求。  gost很好用挺灵活的。
