### ISSUE TITLE
rtcp bind failed

### ISSUE THREAD

**Issue by Clash-zone** [go-gost/gost#208]
I have a domestic server and 1 upstream server

I'ved used this command in domestic server

`gost -L relay+ws://:9000?bind=true`

In the upstream ( foreign ) server, i used rtcp
With this command

`gost  -L rtcp://:2053/127.0.0.1:2053 -F relay+ws://domesticdomain.com:9000
`

Everything goes well, and i can connect to the tunnel, but after a while it disconnects and reconnects again, on each hour it happens more than 2 times, i checked the log and i see this error

`"rtcp","msg":"accept: bind on :9000/tcp failed, retrying in 5s`

What is the solution? Is it a bug?

**Comment by ginuerzh** [comment]
If the network is unstable, the connection will be disconnected, and rtcp will try to re-establish the connection.
