### ISSUE TITLE
Prometheus metrics not work

### ISSUE THREAD

**Issue by leeaash** [go-gost/gost#210]
gost在grafana中添加data source后，explore时选择Metric报404错误，且Dashboard也不现实任何数据，但是 http://hostname:9000/metrics 有数据， 不知该如何解决。
![image](https://user-images.githubusercontent.com/78188599/233886251-c2f20060-c271-4e68-a88e-6a2d4996da97.png)

**Comment by GongSong** [comment]
问题解决了吗？我也遇到同样问题

**Comment by GongSong** [comment]
已经可以了，问题在于gost内置的是Prometheus metrics，并不是Prometheus Server，所以要先安装prometheus Server才可以。

**Comment by leeaash** [comment]
> 已经可以了，问题在于gost内置的是Prometheus metrics，并不是Prometheus Server，所以要先安装prometheus Server才可以。

多谢提供思路，解决了。
