### ISSUE TITLE
怎么进行socks5转发

### ISSUE THREAD

**Issue by 745366841** [go-gost/gost#215]
这个命令 没有udp 转发  ./gost -L "socks5://:89" -F "socks5://0.0.0.0:88"

这个命令  ./gost -L "socks5://:89?udp=true" -F "socks5://0.0.0.0:88?udp=true"  报错  get socks5 UDP tunnel failure

**Comment by ginuerzh** [comment]
首先上级SOCKS5代理服务也必须是gost运行的SOCKS5服务且开启了UDP转发。
```
gost -L socks5://:88?udp=true
```
```
gost -L "socks5://:89?udp=true" -F "socks5://0.0.0.0:88"
```

**Comment by ezbik** [comment]
`gost1 (frontend)`->`gost2 (upstream)` 

So gost1 talks to gost2 (when upstreaming Socks5 UDP) in not-RFC-compliant way. If we replace the upstream with a fully RFC-compliant Socks server, it will show `Unknown Socks5 command` and Gost1 (the frontend) will show `get socks5 UDP tunnel failure`.
