### ISSUE TITLE
When using voice connections such as WhatsApp, Facebook, and Zoom, these connections will automatically disconnect after 5 seconds.

### ISSUE THREAD

**Issue by daouaina** [go-gost/gost#219]
gost v3 is a software that can perform local port traffic forwarding in Relay+tls mode using a configuration file. When using voice connections such as WhatsApp, Facebook, and Zoom, these connections will automatically disconnect after 5 seconds. The software version is v3.0.0-rc7 and uses the Relay+tls protocol. The configuration file takes effect, and it's worth noting that this issue did not occur when using the command in GOST v2 version.

Sample code:

Server:

services:
  - name: service-0
    addr: :23135
    handler:
      type: relay
    listener:
      type: tls
    forwarder:
      nodes:
        - name: target-0
          addr: 127.0.0.1:22135

Client:

services:
  - name: service-0
    addr: :22135
    handler:
      type: udp
      chain: chain-0
    listener:
      type: udp
  - name: service-1
    addr: :22135
    handler:
      type: tcp
      chain: chain-0
    listener:
      type: tcp
chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: 198.211.35.180:23135
            connector:
              type: relay
            dialer:
              type: tls

**Comment by daouaina** [comment]
`5月 11 22:40:22 wlidc gost[4020]: {"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-154","time":"2023-05-11T22:40:22.284+08:00"}`

This will display the following content: 'data discarded: use of closed network connection'."

**Comment by ginuerzh** [comment]
The `keepAlive` option should be enabled for UDP port forwarding.
https://gost.run/en/tutorials/port-forwarding/#udp
