### ISSUE TITLE
最新版gost tun在Android上用不了(无法ping通)

### ISSUE THREAD

**Issue by openwrt2223** [go-gost/gost#22]
最新版gost tun在Android上用不了(无法ping通)。
服务端命令:
gost -L tun://:8888?net=192.168.10.1/24
客户端命令(在Android上):
gost -L tun://:8888/服务端ip:8888?net=192.168.10.2/24
在客户端ping 192.168.10.1失败。

**Comment by openwrt2223** [comment]
@ginuerzh 来看下。

**Comment by cod1ingcoding** [comment]
我测试是没有问题的，是不是你设置的tun设备ip段和本地路由冲突？

**Comment by openwrt2223** [comment]
> 我测试是没有问题的，是不是你设置的tun设备ip段和本地路由冲突？

你用的是哪个版本？

**Comment by openwrt2223** [comment]
> 我测试是没有问题的，是不是你设置的tun设备ip段和本地路由冲突？

在Linux(Ubuntu 20.04)上正常，在Android上不走gost tun，原因未知。

**Comment by Andieqqq** [comment]
测试可用，路由策略自己配就行了

**Comment by openwrt2223** [comment]
> 测试可用，路由策略自己配就行了

来个例子。

**Comment by Andieqqq** [comment]
自己翻路由表……网络层问题
