### ISSUE TITLE
[problem] Forward Multi ports

### ISSUE THREAD

**Issue by Dev-l0p** [go-gost/gost#222]
Hello sir,
When I want to forward a port, Its work correctly:
Server A :
`ExecStart=/usr/local/bin/gost -L=tcp://:440  -F forward+kcp://1.1.1.1:4444`

Server B :
`ExecStart=/usr/local/bin/gost -L=kcp://:4444/:440`

But When I want forward mutli ports:
Server A :
`ExecStart=/usr/local/bin/gost -L=tcp://:440  -F forward+kcp://1.1.1.1:4444 -L=tcp://:445  -F forward+kcp://1.1.1.1:5555`

Server B :
`ExecStart=/usr/local/bin/gost -L=kcp://:4444/:440 -L=kcp://:5555/:445`

At first, it works fine, but after about 20 minutes, the port forwarding doesn't work anymore, and I should in server B restart the Gost service to fix it again.
I have to do this about every 20 minutes.
How I can Fix this issue?

**Comment by ginuerzh** [comment]
The service A should be
```
gost -L=tcp://:440  -F forward+kcp://1.1.1.1:4444 -- -L=tcp://:445  -F forward+kcp://1.1.1.1:5555
```

**Comment by kingsgod** [comment]
hi ginuerzh

i run gost
it ok for wireguard with udp
but dont work in openvpn with tcp
wireguard_port=51820
ovpn_port=1194
plz help me:

=============================================================
**server-2**
sudo apt update
sudo apt install wget nano -y
wget https://github.com/ginuerzh/gost/releases/download/v2.12.0/gost_2.12.0_linux_amd64.tar.gz
tar -xvzf gost_2.12.0_linux_amd64.tar.gz
sudo mv gost /usr/local/bin/gost && sudo chmod +x /usr/local/bin/gost

nano /usr/lib/systemd/system/gost2.service
--------------------------------------------------------
[Unit]
Description=GO Simple Tunnel
After=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/gost -L=relay+kcp://:3333

[Install]
WantedBy=multi-user.target
--------------------------------------------------------
systemctl daemon-reload
systemctl enable gost2.service
systemctl start gost2.service
systemctl restart gost2.service
systemctl status gost2.service

==========================================

**server-1**
sudo apt update
sudo apt install wget nano -y
wget https://github.com/ginuerzh/gost/releases/download/v2.12.0/gost_2.12.0_linux_amd64.tar.gz
tar -xvzf gost_2.12.0_linux_amd64.tar.gz
sudo mv gost /usr/local/bin/gost && sudo chmod +x /usr/local/bin/gost

nano /usr/lib/systemd/system/gost1.service
--------------------------------------------------------
[Unit]
Description=GO Simple Tunnel
After=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/gost -L=udp://:80/b.example.com:51820 -L=tcp://:8080/b.example.com:1194 -F relay+kcp://b.example.com:3333

[Install]
WantedBy=multi-user.target
--------------------------------------------------------
systemctl enable gost.1service
systemctl start gost1.service
systemctl daemon-reload
systemctl restart gost1.service
systemctl status gost1.service
