### ISSUE TITLE
grafana dashboard 无法查看数据

### ISSUE THREAD

**Issue by soragui** [go-gost/gost#223]
按照监控指标配置，可以curl 查看到数据，但是网页版的 grafana 无法查看，请问这个还需要设置其他东西吗
http://localhost:9000/metrics

![image](https://github.com/go-gost/gost/assets/10136640/35e87bd8-05a2-4081-9b80-90fc37b15f1b)

**Comment by orvice** [comment]
看下 metrics 接口是否有被 prometheus 抓取到，metrics 接口里有个指标可以看下是否有被请求:
```
promhttp_metric_handler_requests_total{code="200"}  xxx
```

**Comment by soragui** [comment]
![image](https://github.com/go-gost/gost/assets/10136640/bce0eeed-08d4-4044-a793-1b9fd1bf80d6)

看metrics 是有 的，不过，这个次数是不是有点少了

**Comment by orvice** [comment]
这说明你的 prometheus 没有采集到 gost

**Comment by soragui** [comment]
哦哦，我就是直接在 grafana 上配置了 数据源 Prometheus,然后设置地址 为 http://localhost:9000/metrics，然后测试一下是否可以获取数据，发现都是 404，不知道是不是漏了哪个步骤

**Comment by GongSong** [comment]
需要装prometheus server
