### ISSUE TITLE
rtcp seems will block.

### ISSUE THREAD

**Issue by woodlyer** [go-gost/gost#226]
when use rtcp to do server remote port forwarding.  
If the user count is big, or the network flow is large.    
It seems data block in the tunnel.    only 1 tcp connection to :12345.  
Can we add multi tcp connection to the server to do the network trans to avoid data block in trans.   

```
./gost -L "relay://:12345?bind=true&mbind=true&nodealy=true"
./gost -L rtcp://:80/:80 -F relay://server:12345
```

**Comment by ginuerzh** [comment]
RTCP is a one-to-one connection tunnel. Using multiple connections can get complicated.
