### ISSUE TITLE
web api 保存配置 文件路径

### ISSUE THREAD

**Issue by lucasbozhi** [go-gost/gost#230]
web api “保存配置¶
保存当前的配置到gost.json或gost.yaml文件。
curl -X POST https://gost.run/play/webapi/config?format=yaml
”
这个指令保存到哪里去了 ，愣是没找到
有人知道吗

**Comment by Ivaneus** [comment]
同样遇到这个问题，一直找不到配置文件去处，也没有保存到指向的配置文件里

**Comment by ginuerzh** [comment]
文件保存在当前工作目录

**Comment by ginuerzh** [comment]
新加了一个`path`参数，可以自定义保存位置
https://latest.gost.run/swagger-ui/#/Config/saveConfigRequest
