### ISSUE TITLE
插件无法同时拿到用户的认证信息和用户的访问目标

### ISSUE THREAD

**Issue by uebian** [go-gost/gost#236]
需求：编写插件根据用户名在数据库中查询用户被授权的区域，然后根据区域信息做准入控制。
问题：现在的认证器中无法获取用户访问的目标的信息，准入控制器中无法获取用户的认证信息，同时也没有与连接相关联的唯一的标识符，导致无法根据用户信息进行精确的准入控制。

**Comment by ginuerzh** [comment]
后面会考虑增加连接标识。

**Comment by ginuerzh** [comment]
准入控制器是在用户认证之前根据客户端的IP来做准入控制，用户认证阶段是在用户发起正式请求之前，因此是获取不到用户的目标访问信息。我理解你应该是要用认证器配合分流器来做控制，而不是准入控制器。

**Comment by uebian** [comment]
是的，准确来说应该是"用认证器配合分流器来做控制"，希望实现的效果是特定的用户只能访问特定的网站。

**Comment by ginuerzh** [comment]
最新的提交已经支持客户端ID。
认证器插件可以选择返回一个[客户端ID](https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/auth/proto/auth.proto#L16C16-L16C16)，此ID信息随后会在分流器请求中被发送给插件服务
https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/bypass/proto/bypass.proto#L11C20-L11C20。

**Comment by iLemonRain** [comment]
> 最新的提交已经支持客户端ID。 认证器插件可以选择返回一个[客户端ID](https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/auth/proto/auth.proto#L16C16-L16C16)，此ID信息随后会在分流器请求中被发送给插件服务 [https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/bypass/proto/bypass.proto#L11C20-L11C20。](https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/bypass/proto/bypass.proto#L11C20-L11C20%E3%80%82)

您好，试了一下更新后的版本，bypass的in里面是没有Client的，拿不到ID信息

**Comment by iLemonRain** [comment]
> > 最新的提交已经支持客户端ID。 认证器插件可以选择返回一个[客户端ID](https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/auth/proto/auth.proto#L16C16-L16C16)，此ID信息随后会在分流器请求中被发送给插件服务 [https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/bypass/proto/bypass.proto#L11C20-L11C20。](https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/bypass/proto/bypass.proto#L11C20-L11C20%E3%80%82)
> 
> 您好，试了一下更新后的版本，bypass的in里面是没有Client的，拿不到ID信息

已解决，需要编译最新版本的gost，release最新版本（v3.0.0-rc8）使用不可。

**Comment by iLemonRain** [comment]
> 最新的提交已经支持客户端ID。 认证器插件可以选择返回一个[客户端ID](https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/auth/proto/auth.proto#L16C16-L16C16)，此ID信息随后会在分流器请求中被发送给插件服务 [https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/bypass/proto/bypass.proto#L11C20-L11C20。](https://github.com/go-gost/plugin/blob/0e42c7c67eaa41b86b18fe1a11b51643d87fa8cb/bypass/proto/bypass.proto#L11C20-L11C20%E3%80%82)

还是有一个问题，提供给bypass插件的信息只有ip、端口和ID信息，这样没有办法基于域名进行bypass

**Comment by ginuerzh** [comment]
用法是什么，使用了域名解析器了吗?

**Comment by iLemonRain** [comment]
> 用法是什么，使用了域名解析器了吗?

没有用域名解析器，只是看到传给gRPC的参数里面只有ip、端口、客户端ID。

**Comment by ginuerzh** [comment]
> > 用法是什么，使用了域名解析器了吗?
> 
> 没有用域名解析器，只是看到传给gRPC的参数里面只有ip、端口、客户端ID。

如果没有使用域名解析器，传给插件的`addr`参数应该就是请求的Host信息，可以提供具体的配置信息吗？
最新的提交为bypass插件的请求增加了更多的信息，包括`host`和`network`参数，如果使用了域名解析器，`addr`中是解析后的IP:PORT，`host`中则是原始Host信息。
插件也已经支持HTTP类型，使用起来可能会比gRPC灵活。

**Comment by iLemonRain** [comment]
> > > 用法是什么，使用了域名解析器了吗?
> > 
> > 
> > 没有用域名解析器，只是看到传给gRPC的参数里面只有ip、端口、客户端ID。
> 
> 如果没有使用域名解析器，传给插件的`addr`参数应该就是请求的Host信息，可以提供具体的配置信息吗？ 最新的提交为bypass插件的请求增加了更多的信息，包括`host`和`network`参数，如果使用了域名解析器，`addr`中是解析后的IP:PORT，`host`中则是原始Host信息。https://github.com/go-gost/plugin/blob/master/bypass/proto/bypass.proto#L9 插件也已经支持HTTP类型，使用起来可能会比gRPC灵活。

好的，非常感谢，抽空试一下~
