### ISSUE TITLE
ftp无法在服务端relay模式下工作

### ISSUE THREAD

**Issue by leeaash** [go-gost/gost#241]
服务端配置:
gost -L=relay+mtls://:58964?bind=true

代理端配置:
gost -L=ss://rc4-md5:key@:15368 -L=ssu://rc4-md5:key@:15368 -F=relay+mtls://xxx.xxx:58964

补充一下， 代理前端再套了个clash用来分流

其实也尝试了代理端走socks也无法建立与远端FTP服务器建立连接，其他TCP的服务貌似访问都正常，研究了一下日志，只在代理端看到有连接，未在服务端有看到对应连接，感觉连接在代理端就丢弃了，也许判断不对。

**Comment by leeaash** [comment]
PASV模式下也不行

**Comment by ginuerzh** [comment]
你可以开启`nodelay`选项试一试，我这边测试加了`nodelay`就没问题了。
```
gost -L=ss://rc4-md5:key@:15368 -L=ssu://rc4-md5:key@:15368 -F=relay+mtls://xxx.xxx:58964?nodelay=1
```

**Comment by leeaash** [comment]
> 你可以开启`nodelay`选项试一试，我这边测试加了`nodelay`就没问题了。
> 
> ```
> gost -L=ss://rc4-md5:key@:15368 -L=ssu://rc4-md5:key@:15368 -F=relay+mtls://xxx.xxx:58964?nodelay=1
> ```

是要服务端也要加nodelay配置吧

**Comment by leeaash** [comment]
比较奇怪的一个问题，使用nodelay为什么会导致clash中对节点pingtest的值会比不使用nodelay的延时大呢，从字面上的理解感觉应该得到更快的结果才对。

**Comment by ginuerzh** [comment]
nodelay会增加一次数据交互，多了一个RTT，和TCP_NODELAY类似。

**Comment by leeaash** [comment]
> nodelay会增加一次数据交互，多了一个RTT，和TCP_NODELAY类似。 https://gost.run/tutorials/protocols/relay/#_3

了解了，多谢:P
