### ISSUE TITLE
release 能否增加一个 termux 下编译的可执行文件

### ISSUE THREAD

**Issue by m2acgi** [go-gost/gost#243]
gost termux 下不支持使用域名连接服务器，能否增加一个 termux 下编译的 release 版本？
> https://github.com/ginuerzh/gost/issues/752

**Comment by openwrt2223** [comment]
> gost termux 下不支持使用域名连接服务器，能否增加一个 termux 下编译的 release 版本？
> 
> > [ginuerzh/gost#752](https://github.com/ginuerzh/gost/issues/752)

用android ndk编译的gost就是。

**Comment by openwrt2223** [comment]
> gost termux 下不支持使用域名连接服务器，能否增加一个 termux 下编译的 release 版本？
> 
> > [ginuerzh/gost#752](https://github.com/ginuerzh/gost/issues/752)

go 在android下的老问题了。

**Comment by openwrt2223** [comment]
> gost termux 下不支持使用域名连接服务器，能否增加一个 termux 下编译的 release 版本？
> 
> > [ginuerzh/gost#752](https://github.com/ginuerzh/gost/issues/752)

curl -L https://github.com/openwrt2223/buildgost3/releases/download/$(jq -r '.tag_name' <<< $(curl --silent https://api.github.com/repos/openwrt2223/buildgost3/releases/latest))/gost_linux_amd64 -o gost

**Comment by openwrt2223** [comment]
> gost termux 下不支持使用域名连接服务器，能否增加一个 termux 下编译的 release 版本？
> 
> > [ginuerzh/gost#752](https://github.com/ginuerzh/gost/issues/752)

curl -L https://github.com/openwrt2223/buildgost3/releases/download/$(jq -r '.tag_name' <<< $(curl --silent https://api.github.com/repos/openwrt2223/buildgost3/releases/latest))/gost_android_arm -o gost

**Comment by m2acgi** [comment]
@openwrt2223 谢谢，大佬，方便提交个 PR 吗？

**Comment by openwrt2223** [comment]
> @openwrt2223 谢谢，大佬，方便提交个 PR 吗？

自己用还行，提PR？我不敢
