### ISSUE TITLE
forward multiple port

### ISSUE THREAD

**Issue by arminkhadem1** [go-gost/gost#244]
How can I get a number of ports as TCP and forward them as KCP? I'm writing like this now but it doesn't work.

gost -L tcp://:443  -F forward+kcp://IP:4444 -L tcp://:553  -F forward+kcp://IP:5555

When I hit it individually, it works like this

gost -L tcp://:443  -F forward+kcp://IP:4444

**Comment by woodlyer** [comment]
I recommend to use relay, but not forward.
```
# server
gost -L relay+kcp://:9000
# client map more than one port to server through kcp.
gost -L tcp://:22/:22  -L tcp://:23/:23 -L tcp://:24/:24   -F  relay+kcp://server.com:9000
```

You can see more examples at: https://github.com/woodlyer/gostExample

**Comment by arminkhadem1** [comment]
> I recommend to use relay, but not forward.
> 
> ```
> # server
> gost -L relay+kcp://:9000
> # client map more than one port to server through kcp.
> gost -L tcp://:22/:22  -L tcp://:23/:23 -L tcp://:24/:24   -F  relay+kcp://server.com:9000
> ```
> 
> You can see more examples at: https://github.com/woodlyer/gostExample

thanks
