### ISSUE TITLE
The service traffic limiter setting not effect on ipref3 and speedtest.net result

### ISSUE THREAD

**Issue by weber110** [go-gost/gost#247]
#30 
I've the same problem the service traffic limiter configuration not effect on the ipref3 and speedtest.net result, even thought i remove the limiter line for service, the result still keep on  about 10 Mbits/sec, anyone can help me with my appreciate?

First, please refer my config part which we mentioned:

```
services:
- name: service-0
  addr: ":5448"
  limiter: limiter-0
  handler:
    type: socks5
    auther: auther-0
    chain: chain-0
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: xxx.xxx.xxx.xxx:5448
      connector:
        type: socks5
      dialer:
        type: tcp
limiters:
- name: limiter-0
  limits:
  - $ 100KB 100KB
  - $$ 100KB 100KB
```

Lastly, my proxy chains structure like this: 
1. MacOS without proxy setting, just link my openwrt wifi;
2. OpenWRT installed ssr-plus, select the socks5 node with auth to my China Mainland ECS;
3. China Mainland ECS linsten the 5448~5467 socks5 port and forward to US ECS with IPLC likely tunnel;
4. US ECS linsten the 5448~5467 socks5 port;

**Comment by ginuerzh** [comment]
Can not be reproduced with the latest version, could you double check it again?
