### ISSUE TITLE
Web Api 更新配置后的保存问题

### ISSUE THREAD

**Issue by Ivaneus** [go-gost/gost#253]
api 配置：
api:
  addr: :1000
  pathPrefix: /api
  accesslog: true
gost运行方式：
/usr/bin/gost -C /etc/gost/gost.yaml

不论是把gost作为service运行还是直接命令行指向配置文件运行。
在通过api更新配置并且提交post保存（post的返回值是ok）之后
通过查看gost -C 指向配置文件内容和编辑时间发现并没有任何修改
所以这个保存配置的保存路径和所需权限是有什么特殊要求吗？

**Comment by ginuerzh** [comment]
目前配置文件会保存在当前工作目录中。

**Comment by ginuerzh** [comment]
See #230
