### ISSUE TITLE
使用  -F 时，多个 -L 会逻辑混乱

### ISSUE THREAD

**Issue by 4ft35t** [go-gost/gost#254]
需求：本地 51080 开 socks 代理，使用 ssh 通道转发本地 51080 到远程的 31080 端口

版本: gost 3.0.0-rc8 (go1.20.4 linux/amd64)

本地 IP 1.1.1.1，远程 IP 2.2.2.2

```bash 
gost -L rtcp://:31080/:51080 -L socks5://:51080 -F sshd://usr:pwd@2.2.2.2:22
```
在远程机器上执行
```bash
curl ip.sb -x socks5://127.0.0.1:31080
```
得到结果是远程机器自己的 IP 2.2.2.2

## 产生正确结果的步骤
1. 本地开第一个终端，执行 `gost -L socks5://:51080`
2. 本地开第二个终端，执行 `gost -L rtcp://:31080/:51080  -F sshd://usr:pwd@2.2.2.2:22`
3. 远程终端执行 `curl ip.sb -x socks5://127.0.0.1:31080`, 得到正确结果 1.1.1.1

**Comment by woodlyer** [comment]
-L rtcp://  -L socks5://  -F
这两个-L 都会经过 -F 工作, 相当于:
```
gost -L rtcp://:31080/:51080 -F sshd://usr:pwd@2.2.2.2:22
gost -L socks5://:51080         -F sshd://usr:pwd@2.2.2.2:22
```
因此,不是逻辑错误,是没用对.
