### ISSUE TITLE
V3 版本SSH 转发出现问题

### ISSUE THREAD

**Issue by linxin2020** [go-gost/gost#257]
环境：
服务端 CentOS Linux release 7.9 / sshd.service - OpenSSH server daemon
客户端 gost 3.0.0-rc8 (go1.20.4 windows/amd64)

命令如下：
gost.exe -L=:8888 -F forward+ssh://user:password@host:port 

报错信息
{"handler":"auto","kind":"handler","level":"error","listener":"tcp","msg":"route(retry=0) ssh: rejected: administratively prohibited (open failed)","service":"service-0","time":"2023-08-16T15:47:33.723+08:00"}

用V2版本正常的，gost 2.11.5 (go1.19.2 windows/amd64)；
使用 open-ssh 也是正常的，ssh 命令：ssh -N -D 127.0.0.1:8888 user@host

**Comment by ginuerzh** [comment]
v3中与v2有所区别：
https://gost.run/tutorials/protocols/ssh/#_4
