### ISSUE TITLE
Can't use proxyProtocol on ingress tunnel entryPoint

### ISSUE THREAD

**Issue by ariadarkkkis** [go-gost/gost#259]
Hi, I have the following server config which I want the entryPoint to accept proxyProtocol from HAProxy. Im running HAproxy on port 443 and send proxyProtocol to gost ingress entryPoint. I already tried proxyProtocol version 1 and version 2 but still get `no route to host` error.
Here is my gost server config:
```
./gost -L "relay+ws://:8880?entryPoint=127.0.0.1:4444&proxyProtocol=2&tunnel=domain.com:uuid"
```

Here is my gost client config:
```
./gost -L "rtcp://:0/127.0.0.2:11221?proxyProtocol=2" -F "relay+ws://server_ip:8880?tunnel.id=uuid"
```

On client side, 127.0.0.2:11221 is another HAproxy which accepts proxyProtocol and route and loadbalance my traffic based on SNI and send proxyProtocol to a backend without terminating SSL.

So here is the overview of what I want:
`
user -> server1 HAProxy running on 0.0.0.0:443 -> gost server entryPoint 127.0.0.1:4444 with proxyProtocol -> send to gost client which also need to accept proxyProtocol -> server2 HAProxy running on 127.0.0.2:11221 accepting proxyProtocol (route based on SNI) -> HAProxy send to a backend with proxyProtocol (send-proxy)
`

**Comment by ariadarkkkis** [comment]
Any idea?

**Comment by ginuerzh** [comment]
The PROXY protocol support for entry point and rtcp has been added in the latest commit.
```
gost -L "relay+ws://:8880?entryPoint=127.0.0.1:4444&entryPoint.proxyProtocol=2&tunnel=domain.com:uuid"
```
```
gost -L "rtcp://:0/127.0.0.2:11221?proxyProtocol=2" -F "relay+ws://server_ip:8880?tunnel.id=uuid"
```
