### ISSUE TITLE
gost编译错误

### ISSUE THREAD

**Issue by openwrt2223** [go-gost/gost#26]
![Screenshot_2022-04-02-21-01-36-643_com microsoft emmx beta](https://user-images.githubusercontent.com/92192602/161385031-df742917-5a50-496b-903f-2f64d4596527.jpg)
@ginuerzh 看下是不是？

**Comment by ginuerzh** [comment]
如果Github Actions的自动构建通过就说明没有问题。

**Comment by openwrt2223** [comment]
> 如果Github Actions的自动构建通过就说明没有问题。

我的并没有通过。

**Comment by ginuerzh** [comment]
系统不是Linux?

**Comment by openwrt2223** [comment]
> 系统不是Linux?

Ubuntu 20.04 golang 1.18

**Comment by ginuerzh** [comment]
已修复

**Comment by openwrt2223** [comment]
> 系统不是Linux?

我开了交叉编译(android)

**Comment by openwrt2223** [comment]
> 已修复

好了，编译成功。
