### ISSUE TITLE
gost v3 not support  kcp://:8000?tcp=true

### ISSUE THREAD

**Issue by woodlyer** [go-gost/gost#262]
gost v2 support ?tcp=true to use tcp for kcp.
but in gost v3,  it doesn't support this future.

we have to use  kcp://:8000?c=kcp.json to set tcp usage
```
{
    "tcp": true
}
```

cant  "?tcp=true"  be supported in v3?

**Comment by ginuerzh** [comment]
More config options have been added
https://github.com/go-gost/x/blob/master/listener/kcp/metadata.go#L48-L55

**Comment by woodlyer** [comment]
can this added to the doc of kcp?  
https://gost.run/reference/dialers/kcp/
```
gost -L relay+kcp://:9000?kcp.tcp=true
```
