### ISSUE TITLE
How do I set 2 levels of logging at the same time?

### ISSUE THREAD

**Issue by FastSpace123** [go-gost/gost#263]
![Screenshot_2](https://github.com/go-gost/gost/assets/60469037/3dc74790-7195-4c2f-ac8e-693ba39531fa)

I need **error + warn** level together

![Screenshot_3](https://github.com/go-gost/gost/assets/60469037/6d7a748e-801b-48d3-801d-abf11fbd57d5)

**Comment by ginuerzh** [comment]
The warn level will log all warn, error and fatal level messages.
