### ISSUE TITLE
能否支持动态范围端口？

### ISSUE THREAD

**Issue by baijunty** [go-gost/gost#268]
个人的使用经验，在使用单一端口一旦流量过大了或者时间一长就可能会被ban掉，或者直接drop目标地址端口流量，这时候就需要换端口了。
如果在服务器设置系列端口比如gost -L socks5://:7000-7100，客户端使用 -F socks5://192.168.1.1:7000-7100，在建立连接时随机使用其中一个端口进行连接。这样就比较难出现目标地址端口被ban的情况，即使ban掉其中一个端口，也可以快速切换端口而恢复通信。
可以是v2ray的动态端口的协商建立，暴力点的如kcptun去年的[v20221015]服务器端一次性监听所有范围端口，客户端则是随机使用。

**Comment by dwdhc** [comment]
有点意思，但 感觉Gost 定位不算是一款为了翻墙的工具吧，如果有需要可以Fork一份，自己改。😂

**Comment by AndersonGhost** [comment]
gost 能够中转最新的Hysteria 2协议吗？如何中转呢？

> 即使能够支持端口跳跃，估计也只能是在QUIC协议上实现，毕竟连hysteria协议都是由于标准QUIC协议本身支持端口跳跃的功能才能实现hysteria协议的端口跳跃
> 
> 另外补充一下，kcptun应该不是真正的端口跳跃，按照下面的kcptun描述，应该理解为每个新连接才能随机选用一个新的端口进行连接，但这样的问题是如果用户正在长时间播放4k或8k视频流，那么肯定会被qos限流的，这时视频播放会中断，因为正在使用的端口被阻断了，而QUIC协议实现的端口跳跃是同一个连接，在客户端设定的间隔时间点主动跳跃到新的端口进行传输，上层的tcp连接会话并不会感觉到被切换了连接端口，视频流还是继续播放，用户无感 “by specifying port-range, kcptun will automatically switch to next random port within port-range when establishing each new connection.”

**Comment by AndersonGhost** [comment]
主要是安装hysteria的VPS离自己太远了呀，所以想用gost中转一下，延时会低很多。具体如何操作呢？我使用gost中转hysteria但是没有成功

> 实际上如果要中转的话，不一定需要gost，具体要看你的中转的要求，简单来说hysteria或hysteria 2都支持端口转发，如果只是使用gost的端口转发功能做中转的话，那么直接使用hysteria即可，另外hysteria也支持服务器端的socks5 outbound，就是hysteria服务器端会把流量转发到用户指定的出口而不在本地出局，这样就可以解决分流（outbound到本地同一服务器的xray或sing-box再分流出局），下一跳流量出局等等
> 
> 当然gost还有许多中转的特别功能是hysteria做不了的，所以还是要看你具体的需求
> 
> 经过测试，外层用hysteria，而内层用gost效果会比较好，毕竟hysteria设计初衷就是抗丢包的
> 
> 如果是外层用gost，内层用hysteria，传输效果会惨不忍睹

**Comment by baijunty** [comment]
行吧，我就问一下。
