### ISSUE TITLE
How to enable udp relay ?  [socks5: UDP relay is disabled]

### ISSUE THREAD

**Issue by qianhd** [go-gost/gost#274]
Client A  --> Node B --> Node C --> Internet

Client A:  
gost -L=rtcp://:8080/8080 -F socks+quic://Node_B:1080 -F socks+quic://Node_C:1080

Node B:
gost -L socks+quic://:1080?&bind=true&ttl=61s

Node C:
gost -L socks+quic://:5432?&bind=true&ttl=61s

===========================

Error information:
Client A: accept: get socks5 UDP tunnel failure, retrying in ...
Node B: socks5: UDP relay is disabled
Node C: no error

Is any special paramters i need use to enable udp relay ?

**Comment by qianhd** [comment]
i've tried add udp=true on both Client A, Node B and Node C

here is config

Client A:
gost -L=rtcp://:8080/8080 -F socks+quic://Node_B:1080&udp=true -F socks+quic://Node_C:1080&udp=true

Node B:
gost -L socks+quic://:1080?&bind=true&ttl=61s&udp=true

Node C:
gost -L socks+quic://:5432?&bind=true&ttl=61s&udp=true

============

Here is error prompt:
Client A: accept: timeout: no recent network activity, retrying in ...
Node B: accept stream:timeout: no recent network activity
Node C: accept stream:timeout: no recent network activity

Is any special paramter i need using ?

**Comment by ginuerzh** [comment]
All nodes based on UDP protocol (including QUIC) can only serve as the first node in the forwarding chain.

**Comment by qianhd** [comment]
> All nodes based on UDP protocol (including QUIC) can only serve as the first node in the forwarding chain.

OK ，i get it。 i worndering is there any tech problem for this limition (UDP protocol can only serve as the first node).

**Comment by ginuerzh** [comment]
Including UDP-based proxy protocols, most proxy protocols are used to proxy TCP traffic.

**Comment by 189er** [comment]
z:/gost.exe   -D -L socks://127.0.0.7:1080?udp=true&bind=true&relay=udp;
#试了一下udp123,没有问题
