### ISSUE TITLE
Support multiple addresses per service.

### ISSUE THREAD

**Issue by fernvenue** [go-gost/gost#277]
Sometimes we don't wanna bind on `0.0.0.0` or `::`, but we do wanna bind our service to multiple addresses :)

**Comment by ginuerzh** [comment]
You can start multiple services, each binding on a different address.

**Comment by fernvenue** [comment]
> You can start multiple services, each binding on a different address.

Thanks for your reply, and yea, that's what I do now, and I do think it will be better if gost can bind multiple addresses per service, so that our configuration file can be more human readable :)
