### ISSUE TITLE
multiplexer service ?

### ISSUE THREAD

**Issue by wenerme** [go-gost/gost#278]
e.g. clash can expose socks & http as same port, I think there should be a multiplexer service, can do the same ?

**Comment by MRoSlot** [comment]
{"handler":"auto","kind":"service","level":"error","listener":"tcp","msg":"listen tcp 0.0.0.0:80: bind: address already in use","service":"service-0","time":"2024-07-11T18:55:39.636Z"}
my server: gost -L auto://:80?bind=true
my client: gost.exe -L rtcp://:80/127.0.0.1:5000 -F socks5://{{PUBLIC_IP}}:80
so much opportunity if it can io on single port like chisel
