### ISSUE TITLE
请问tun2tun模式是否支持bypass

### ISSUE THREAD

**Issue by iLemonRain** [go-gost/gost#282]
作者您好，在gost的tun2tun模式的说明文档
[https://gost.run/tutorials/tuntap/#_10](url)
里面只看到支持认证，没看到是否支持bypass
我自己实测了一下，好像不支持？gRPC bypass服务也没有打出log。
希望可以确认一下，谢谢

**Comment by ginuerzh** [comment]
tun需要bypass什么？
gRPC是数据通道层，与bypass无关。

**Comment by iLemonRain** [comment]
比如我想基于域名和ip+port过滤，像是配置成隧道再bypass那样子。不过猜想tun2tun相当于3层vpn，应该是做不到过滤吧？

**Comment by ginuerzh** [comment]
TUN处理的是网络层IP数据包，数据内容对于TUN是透明的。
