### ISSUE TITLE
Missing Permission Control in GOST v3

### ISSUE THREAD

**Issue by jasonkhoi** [go-gost/gost#286]
Hi,

In Gost V2, I was able to place permission control as:

?whitelist=[action]:[IP]:[Port]

In Gost V3, I'm unable to do that. The closest is bypass:

?bypass=~IP

How do I restrict by ports as well in Gost V3?

**Comment by ginuerzh** [comment]
Permission control is deprecated and will be replaced by Bypass later.

**Comment by jasonkhoi** [comment]
I have tested. It has worked.
Now I'm able to upgrade GOST version 2 to version 3.
Thank you very much.
