### ISSUE TITLE
docker 版转发 socks5 报错 bad format

### ISSUE THREAD

**Issue by KennyLeung** [go-gost/gost#288]
sudo docker run -d --name gost \
    -v ${CERT_DIR}:${CERT_DIR}:ro \
    --restart=always \
    --net=host gogost/gost:latest \
    -L "https://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}" \
    -F "socks5://172.17.0.2:40001"

按以上方式运行后，不能实现转发，日志报错：
{"handler":"http","kind":"service","level":"error","listener":"tls","msg":"bad format","service":"service-0","time":"2023-10-02T01:25:58.642Z"}

如果不做转发，即去掉最后一行，功能正常。

**Comment by ginuerzh** [comment]
最新的提交已修复。

**Comment by KennyLeung** [comment]
> 最新的提交已修复。

2天前，我提这个issue的时候，已经下载最新的 Dockerfile 编译测试，发现问题仍然存在才提的 issue。您能告知具体改了哪里的代码吗？如能提供，我对照一下当时编译的代码是否是更改后的代码。谢谢。

**Comment by ginuerzh** [comment]
之前没有完全修复，再试试最新的提交。

**Comment by KennyLeung** [comment]
测试通过，感谢。
