### ISSUE TITLE
请问如果隧道连接数目较多导致端口不够用，如何配置nat

### ISSUE THREAD

**Issue by iLemonRain** [go-gost/gost#291]
隧道被多人使用时，如果连接数目较多，gost服务端的单个物理IP的端口存在不够用的担忧。
因此希望在服务端配置nat改变数据包的源ip段，类似于配置iptables -t nat -A POSTROUTING -s 192.168.0.0/16 -o p5p1 -j SNAT --to-source 172.16.1.0/24
但是这样配置iptables以后会导致代理失效，请问gost有没有什么原生的解决方案？
比如大部队的pc网段是192.168.0.0/16，然后经过gost服务端后希望转换成172.16.1.0/24这个段的出口ip。

一如既往的感谢作者。

**Comment by ginuerzh** [comment]
这个问题我觉得应该是要通过水平扩展和负载均衡来达到扩容目的，而不是通过nat来解决。

**Comment by iLemonRain** [comment]
> 这个问题我觉得应该是要通过水平扩展和负载均衡来达到扩容目的，而不是通过nat来解决。

确实
