### ISSUE TITLE
gost更新到521版本后多级转发的配置失效

### ISSUE THREAD

**Issue by leeaash** [go-gost/gost#294]
问题如题：
客户端必须使用521的版本或两端都使用521版本才能通讯，服务端和客户端使用同一新版本无法通讯

服务端配置
gost -L=tcp://:40001/:40000?udp=truebind=true
客户端配置
gost -L=socks5://:10688?udp=true&bind=true -F=relay+mtls://example.com:443 -F=tcp://10.38.8.1:40001

**Comment by leeaash** [comment]
521版本是指docker镜像5月21创建，应该对应的是rc8版本. 我所有gost都是用docker跑的，目前有问题的应该是521之后更新的镜像

我应该还漏了服务端的配置
服务端配置
容器1： gost -L=tcp://:40001/:40000?udp=true&bind=true  
容器2： gost -L=relay+mtls://:58964?bind=true
客户端配置
gost -L=socks5://:10688?udp=true&bind=true -F=relay+mtls://example.com:443 -F=tcp://10.38.8.1:40001
用途是客户端的socks5 服务通过2级转发链连接到服务器端的容器1上的40001端口的socks服务，容器1的一个接口地址是10.38.8.1，可以让容器2访问到

**Comment by hyyxiaoluo** [comment]
> 521是什么版本？ 这两条命令是要做什么事情？

你好，请问下咱们的gost是没有卸载的命令么，找了好久没找到，我下载的3.0版本，然后用人家的2.0的脚本进行卸载后查看版本还是显示存在

**Comment by ginuerzh** [comment]
> > 521是什么版本？ 这两条命令是要做什么事情？
> 
> 你好，请问下咱们的gost是没有卸载的命令么，找了好久没找到，我下载的3.0版本，然后用人家的2.0的脚本进行卸载后查看版本还是显示存在

直接手动删除即可。

**Comment by ginuerzh** [comment]
> 521版本是指docker镜像5月21创建，应该对应的是rc8版本. 我所有gost都是用docker跑的，目前有问题的应该是521之后更新的镜像
> 
> 我应该还漏了服务端的配置 服务端配置 容器1： gost -L=tcp://:40001/:40000?udp=true&bind=true 容器2： gost -L=relay+mtls://:58964?bind=true 客户端配置 gost -L=socks5://:10688?udp=true&bind=true -F=relay+mtls://example.com:443 -F=tcp://10.38.8.1:40001 用途是客户端的socks5 服务通过2级转发链连接到服务器端的容器1上的40001端口的socks服务，容器1的一个接口地址是10.38.8.1，可以让容器2访问到

如果你的40000端口是个socks5服务，直接转发即可
```
gost -L tcp://:10688/10.38.8.1:40001 -F relay+mtls://example.com:443
```
或者
```
gost -L=socks5://:10688?udp=true&bind=true -F=relay+mtls://example.com:443 -F=socks5://10.38.8.1:40001
```

**Comment by leeaash** [comment]
> > 521版本是指docker镜像5月21创建，应该对应的是rc8版本. 我所有gost都是用docker跑的，目前有问题的应该是521之后更新的镜像
> > 我应该还漏了服务端的配置 服务端配置 容器1： gost -L=tcp://:40001/:40000?udp=true&bind=true 容器2： gost -L=relay+mtls://:58964?bind=true 客户端配置 gost -L=socks5://:10688?udp=true&bind=true -F=relay+mtls://example.com:443 -F=tcp://10.38.8.1:40001 用途是客户端的socks5 服务通过2级转发链连接到服务器端的容器1上的40001端口的socks服务，容器1的一个接口地址是10.38.8.1，可以让容器2访问到
> 
> 如果你的40000端口是个socks5服务，直接转发即可
> 
> ```
> gost -L tcp://:10688/10.38.8.1:40001 -F relay+mtls://example.com:443
> ```
> 
> 或者
> 
> ```
> gost -L=socks5://:10688?udp=true&bind=true -F=relay+mtls://example.com:443 -F=socks5://10.38.8.1:40001
> ```

2个配置都测试过可以正常工作了，之前可以是老版本的对配置的宽容度更高？

**Comment by ginuerzh** [comment]
`-F=tcp://10.38.8.1:40001`这个用法在两个版本之间有差异，rc8及之前等同于`-F=http://10.38.8.1:4001`，rc8之后改为转发模式。
正常不建议使用`-F=tcp://`这种方式，而要明确指明具体的代理协议类型。
