### ISSUE TITLE
GOST V3判断端口被占用逻辑会导致误判而无法正常启动GOST

### ISSUE THREAD

**Issue by Ivaneus** [go-gost/gost#298]
复现流程：
1.gost v3 通过配置文件建立上万个服务，每个服务监听不同的独立端口
2.并为每个服务配置一个使用外部http源的admission
示范：
    {
      "name": "service-5000",
      "addr": ":5000",
      "admission": "admission-0",
      "interface": "",
      "handler": {
        "type": "auto",
        "auther": "auther-5000"
      }
    }

  "admissions": [
    {
      "name": "admission-0",
      "whitelist": false,
      "reload": "3600s",
      "http": {
        "url": "https://raw.githubusercontent.com/v03413/GeoIP2-CN/release/China_IP_list.txt",
        "timeout": "10s"
      }
    }
  ]
当我创建这样的配置文件后，由于端口数量特别大，就会报类似错误
{"handler":"auto","kind":"listener","level":"error","listener":"tcp","msg":"init: listen tcp :12347: bind: address already in use","service":"service-12347","time":"2023-10-13T04:07:50.365Z"}
提示某个端口被占用导致GOST服务启动流程终止，实际上通过排查，这个报错端口并没有被listen
最终发现，是gost v3在判断端口占用情况时把connect端所使用的的端口也归纳在内，实际上这个端口在listen端并没有使用，所以产生上述误判报错。
目前我已经通过修改linux的随机端口范围来暂时解决这个问题，
sysctl -w net.ipv4.ip_local_port_range="1024 4096" (这个范围必须限定在GOST配置文件所使用的端口范围之外)
例如我GOST 使用5000及以上所有的端口，那么这里这个范围就必须设定在0-4999之内
要彻底解决这个问题，还希望作者能够把connect端的端口占用行为排除在外，以免影响gost正常启动

**Comment by ginuerzh** [comment]
这个是正常的，本地TCP客户端建立连接是也会占用本地端口。

**Comment by Ivaneus** [comment]
我认为是admissions在数据源使用http的时候使用系统随机端口产生的connect端端口导致的误判，因为如果我不使用http源的admissions或者直接不使用admissions就不会产生这样的错误

**Comment by ginuerzh** [comment]
这不是误判，而是socket的特性。

**Comment by Ivaneus** [comment]
原来如此，那后期是否考虑让socket支持SO_REUSEADDR或者SO_REUSEPORT等特性？这样就可以让gost在高负载项目下完美运行
我记得同类程序3proxy支持这样的特性
https://3proxy.ru/highload.asp

**Comment by woodlyer** [comment]
Maybe just use this API is OK.   the listen will support reuse addr.
```
// listen on the same port. oh yeah.
l1, _ := reuse.Listen("tcp", "127.0.0.1:1234")
```
https://github.com/libp2p/go-reuseport

**Comment by ginuerzh** [comment]
可以使用SO_REUSEPORT来解决这个问题，但我觉得不是很好的做法，服务的端口监听和作为客户端发起请求是并发的，理论上这个冲突是必然的，如果使用了SO_REUSEPORT，就可能会造成服务和客户端都同时占用此端口，导致数据混乱。最安全的做法还是通过修改net.ipv4.ip_local_port_range，将服务监听端口和客户端请求时的随机分配端口范围区分开。

**Comment by Ivaneus** [comment]
确实有可能,因为我之前在部署3PROXY的时候，如果混合使用http和socks5，就会产生一些奇怪的问题。不过我目前换到GOST之后，net.ipv4.ip_local_port_range目前也是采用这个方式进行分开，但是如果服务监听端口占用特别多，同时客户端请求并发也很高的情况下，区分预留的随机端口范围不足会不会导致无法满足高并发连接情况？
