### ISSUE TITLE
功能增加:ip限速

### ISSUE THREAD

**Issue by steamsv** [go-gost/gost#30]
能够对每个来源ip进行限速

**Comment by sxchxdc** [comment]
同求，对每个来源IP限制速度或者连接数。

**Comment by ginuerzh** [comment]
https://gost.run/concepts/limiter/

**Comment by benyamin218118** [comment]
its not working :
gost -L=ss://AES-256-GCM:password@:4444?limiter.conn.out=250KB&limiter.conn.in=250KB&limiter.in=250KB&limiter.out=250KB
i can download up to my bandwidth
for example 3 MB per seconds.

**Comment by benyamin218118** [comment]
hello? any news on this?

**Comment by ginuerzh** [comment]
Maybe you need to add quotes:
```
gost -L="ss://AES-256-GCM:password@:4444?limiter.conn.out=250KB&limiter.conn.in=250KB&limiter.in=250KB&limiter.out=250KB"
```

You can confirm the command by using the '-O yaml':
```
gost -L="ss://AES-256-GCM:password@:4444?limiter.conn.out=250KB&limiter.conn.in=250KB&limiter.in=250KB&limiter.out=250KB" -O yaml
```
Outputs:
```
services:
- name: service-0
  addr: :4444
  limiter: limiter-0
  handler:
    type: ss
    auth:
      username: AES-256-GCM
      password: password
  listener:
    type: tcp
limiters:
- name: limiter-0
  limits:
  - $ 250KB 250KB
  - $$ 250KB 250KB
```

**Comment by benyamin218118** [comment]
thank you @ginuerzh for the reply, i will try this

**Comment by benyamin218118** [comment]
hi @ginuerzh 
i just tested again 

it looks like its just not working when you use `-F=...`

for example this works :
`gost -L="ss://AES-256-GCM:password@:4444?limiter.conn.out=250KB&limiter.conn.in=250KB&limiter.in=250KB&limiter.out=250KB"`

but this one doesn't works : 

`gost -L="ss://AES-256-GCM:password@:4444?limiter.conn.out=250KB&limiter.conn.in=250KB&limiter.in=250KB&limiter.out=250KB" -F=ss://AES-256-GCM:password@server2.com:4442`

**Comment by benyamin218118** [comment]
so that's how it supposed to work or its a bug?

**Comment by zero0o07** [comment]
how to testing the limiter is work?

using fast.com to testing, the download speed limited , but the upload speed limiter is not work, setup as below

```
- name: limiter-0
  limits:
  - '$ 2MB 2MB'
  - '$$ 2MB 2MB '
```

fast.com result
![2023-03-08 12 56 44](https://user-images.githubusercontent.com/107970768/223623313-739b77b8-2612-45c6-924b-987d25558e21.jpg)


I want to limit the download speed how to set, or how to testing the limiter (input/output) setting is work, 

thanks

**Comment by xzycn** [comment]
@zero0o07 
You should post the complete configuration you are using.
Do you just create a limiter named "limiter-0", but do not assign it to a service?

**Comment by zero0o07** [comment]
> @zero0o07 You should post the complete configuration you are using here. Do you just create a limiter named "limiter-0", but do not assign it to a service?

the details as below:

```
services:
- name: service-0
  addr: ":8888"
  interface: 100.100.100.194
  limiter: limiter-0
  handler:
    type: auto
    auther: auther-0
  listener:
    type: tcp
authers:
- name: auther-0
  auths:
  - username: UNAME
    password: UPWD
limiters:
- name: limiter-0
  limits:
  - $ 2MB 2MB
  - $$ 2MB 2MB
 ```

`100.100.100.194` is a fake address,

`socks://UNAME:UPWD@100.100.100.194:8888`
or
`http://UNAME:UPWD@100.100.100.194:8888`

**Comment by xzycn** [comment]
@zero0o07 
The key point for this problem is that they are different unit.
1 MB = 1Mb * 8, so you should set like this:
```
limits:
  - $ 0.25MB 0.25MB
  - $$ 0.25MB 0.25MB

**Comment by ginuerzh** [comment]
You can use the `scp` command to test the limiter:

**Proxy mode:**

```
gost -L ":8080?limiter.conn.in=1MB&limiter.conn.out=2MB&limiter.in=1MB&limiter.out=2MB"
```

test upload:
```
scp -o "ProxyCommand=nc -X connect -x localhost:8080 %h %p" ./test.dat user@localhost:~
```
test download:
```
scp -o "ProxyCommand=nc -X connect -x localhost:8080 %h %p" user@localhost:~/test.dat .
```

**Port forwarding mode**

```
gost -L "tcp://:2222/:22?limiter.conn.in=1MB&limiter.conn.out=2MB&limiter.in=1MB&limiter.out=2MB"
```

test upload:
```
scp -P 2222 ./test.dat user@localhost:~
```
test download:
```
scp -P 2222 user@localhost:~/test.dat .
```
