### ISSUE TITLE
[QA]请问是否支持域名白名单/黑名单模式?

### ISSUE THREAD

**Issue by pedoc** [go-gost/gost#301]
即如果设置了域名白名单,那么经过此代理访问的域名只能是白名单内的域名(最好支持域名通配符),并且不允许在域名黑名单内的域名被访问.

请问当前支持这种能力吗?谢谢

**Comment by ginuerzh** [comment]
https://gost.run/concepts/bypass/

**Comment by pedoc** [comment]
感谢指导
