### ISSUE TITLE
UDP透明代理转发链如何使用SOCKS5自带的UDP代理

### ISSUE THREAD

**Issue by onlyvae** [go-gost/gost#302]
版本：gost 3.0.0-rc9 (go1.21.1 linux/amd64)
复现：启动命令
`./gost -L redu://:12345?ttl=30s -F socks5://172.16.10.1:10800?udp=true`

配置iptables，参考自https://gost.run/tutorials/redirect/#_4

随后在本地执行dig发出UDP数据包测试代理是否生效
`dig @8.8.8.8 baidu.com`

gost的日志显示get socks5 UDP tunnel failure
`{"handler":"redu","kind":"service","level":"info","listener":"redu","msg":"listening on [::]:12345/udp","service":"service-0","time":"2023-10-18T00:01:11.113+08:00"}
{"handler":"redu","kind":"listener","level":"info","listener":"redu","msg":"172.16.10.5:58709 >> 8.8.8.8:53","service":"service-0","time":"2023-10-18T00:01:17.755+08:00"}
{"handler":"redu","kind":"handler","level":"info","listener":"redu","local":"8.8.8.8:53","msg":"172.16.10.5:58709 <> 8.8.8.8:53","remote":"172.16.10.5:58709","service":"service-0","time":"2023-10-18T00:01:17.756+08:00"}
{"handler":"redu","kind":"handler","level":"error","listener":"redu","msg":"route(retry=0) get socks5 UDP tunnel failure","service":"service-0","time":"2023-10-18T00:01:17.759+08:00"}
{"dst":"8.8.8.8:53/udp","handler":"redu","kind":"handler","level":"error","listener":"redu","local":"8.8.8.8:53","msg":"get socks5 UDP tunnel failure","remote":"172.16.10.5:58709","service":"service-0","time":"2023-10-18T00:01:17.759+08:00"}`

通过抓包发现gost在请求转发链中的代理时，使用的Command是0xF3，对应的是UDP-TUN (UDP-Over-TCP Tunnel) https://gost.run/tutorials/protocols/socks/#udp-tun-udp-over-tcp-tunnel ，但是我这里socks5代理不是用的gost开启的，如果我想用socks5本身的UDP ASSOCIATE来转发UDP该怎么办？
![图片](https://github.com/go-gost/gost/assets/25417261/d16b1aa4-26a3-4cd6-a597-3c52ceb44efe)

**Comment by ginuerzh** [comment]
由于转发链可能有多级，为了通用性，通过SOCKS5转发UDP数据目前仅支持UDP-over-TCP。

**Comment by nansangya** [comment]
现在可以了没
