### ISSUE TITLE
bypass插件问题

### ISSUE THREAD

**Issue by dreamRDK** [go-gost/gost#304]
大佬，使用bypass插件调用http服务传递参数的时候能否传递完整的请求路径而不是域名？

**Comment by ginuerzh** [comment]
后面针对HTTP请求，可以将URI传给插件。

**Comment by dreamRDK** [comment]
请问这个功能预计多久可以上线？

**Comment by dreamRDK** [comment]
或者有没有其他方式可以分流静态资源请求

**Comment by ginuerzh** [comment]
Bypass是一个通用的组件，你需要在哪种协议下使用？

**Comment by dreamRDK** [comment]
http

**Comment by dreamRDK** [comment]
是端口转发
{
      "name": "service-29101",
      "addr": ":29101",
      "admission": "admission-0",
      "handler": {
        "type": "http",
        "retries": 1,
        "chain": "chain-29101"
      },
      "listener": {
        "type": "tcp"
      }
    }

**Comment by dreamRDK** [comment]
```
{
      "name": "service-29101",
      "addr": ":29101",
      "admission": "admission-0",
      "handler": {
        "type": "http",
        "retries": 1,
        "chain": "chain-29101"
      },
      "listener": {
        "type": "tcp"
      }
    }
```
```
{
      "name": "chain-29101",
      "hops": [
        {
          "name": "hop-0",
          "nodes": [
            {
              "name": "node-0",
              "addr": "",
              "connector": {
                "type": "http",
                "auth": {
                  "username": "",
                  "password": ""
                }
              },
              "dialer": {
                "type": "tcp"
              }
            }
          ]
        }
      ]
    }
```

需要在转发链上对请求进行过滤

**Comment by ginuerzh** [comment]
对于HTTP代理我觉得用处不大，目前网站基本上都已经是HTTPS了。
另外GOST采用的是HTTP CONNECT方法与代理服务器连接，Bypass在客户端发送HTTP请求头之前就已经生效。

**Comment by dreamRDK** [comment]
![image](https://github.com/go-gost/gost/assets/14836072/da7bcf91-a66f-4726-97b5-fcbbadc6615a)
就是希望静态资源直接从gost服务器请求，不走下一级代理，这种有方法实现吗？socks5代理支持这种分流吗

**Comment by ginuerzh** [comment]
目前的HTTP基本上都会使用keepalive模式，单个连接执行多次请求，你的需求使用反向代理倒是可以实现。

**Comment by dreamRDK** [comment]
目标网站是不确定的，也不是我自己的服务，无法使用反向代理吧
