### ISSUE TITLE
怎样在一台 vps 上使用 nginx 反带来部署一个基于 docker 的 web 应用和基于 docker 的gost?

### ISSUE THREAD

**Issue by meiyingqishi** [go-gost/gost#305]
我有一台 vps，我想实现这样的功能：部署一个基于 docker 的 web 应用：memos，部署一个基于 docker 的 gost 来科学上网，两个都走 https，都使用自签名证书，使用 nginx 来作反向代理，能够在浏览器访问memos（https://memos.domain.com），也能在客户端通过 Clash 来科学上网（https://xgfw.domain.com），请问这该怎样做？

我尝试了下没有配置成功，memos 倒是能在浏览器访问，但是 Clash 客户端却连不上。

**Comment by ginuerzh** [comment]
具体配置？

**Comment by meiyingqishi** [comment]
感谢回复。

我是基于别人的安装脚本来定制自己的需求，我定制修改后的脚本：https://github.com/meiyingqishi/meiyingqishi.github.io/blob/main/scripts/gost-vpn-server-on-ubuntu.sh

我是按照 init 函数里的步骤：1、2、3……8 来在 EC2 Ubuntu 服务器上部署的。其中关于 Gost 的部分是位于 install_gost 函数里面，具体脚本代码是：
```Bash
sudo docker run -d --name gost \
        --net=host ginuerzh/gost \
        -L "http2://${USER}:${PASS}@${BIND_IP}:${PORT}?probe_resist=web:localhost:5230&knock=www.google.com"
```

然后再安装和配置 nginx，最后使用 certbot 来自签名证书。

原来是使用这个脚本来配置科学上网：
https://github.com/haoel/haoel.github.io/blob/master/scripts/install.ubuntu.18.04.sh
具体脚本代码是：
```Bash
sudo docker run -d --name gost \
        -v ${CERT_DIR}:${CERT_DIR}:ro \
        --net=host ginuerzh/gost \
        -L "http2://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}&probe_resist=code:400&knock=www.google.com"
```
没有问题，运行得很好，但是有一个问题，因为走 https 而占用了 443 端口，导致我再在这台服务器上部署其它 web 应用（即在线备忘录 memos）时只能使用 http，而没法使用 https，因为 nginx 检测到 443 端口已被 docker gost 占用而起不起来。

自己没想到解决方案，在网上搜了半天也没头绪，希望帮忙看下能有什么解决方案来解决，感激不尽。

**Comment by ginuerzh** [comment]
若要用Nginx分流，目前比较好的做法是使用websocket传输协议。

**Comment by meiyingqishi** [comment]
好的，我配成 `mwss`，谢了。

**Comment by meiyingqishi** [comment]
请问如果使用 Nginx 来分流，Gost 的本地监听端口那里使用 ws 协议（可以使用 mwss 吗？），在 Nginx 的 proxy_pass 后面该怎么配置呢？

我按网上的一些说法配成这样没有作用：
```Bash
location / {
                proxy_pass http://localhost:8443;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
```

**Comment by meiyingqishi** [comment]
// TODO
