### ISSUE TITLE
这个文档说明是不是错了，com2没有看到文字说明有啊

### ISSUE THREAD

**Issue by aogg** [go-gost/gost#306]
重定向到远程串口设备[¶](https://gost.run/tutorials/serial/#_4)
将本地串口设备COM1通过转发链重定向到远程主机192.168.1.1上的串口设备COM1。

命令行
配置文件

gost -L serial://COM1/COM2 -F relay://192.168.1.1:8420

**Comment by ginuerzh** [comment]
文档描述有误。
