### ISSUE TITLE
gost 如何转发 trojan 协议

### ISSUE THREAD

**Issue by shizeying** [go-gost/gost#311]

**Comment by 1-bytes** [comment]
也不思考，也不看文档，上来就提一个很小白的问题...
很让人上头啊。。。

**Comment by shizeying** [comment]
sorry。我失去专业程序员的素养。这就去看，不好意思

**Comment by shizeying** [comment]
sorry!我失去了程序员的职业素养，这就去看🥹发自我的 iPhone在 2023年10月23日，17:49，Enzo ***@***.***> 写道：﻿
也不思考，也不看文档，上来就提一个很小白的问题...
很让人上头啊。。。

**Comment by 1-bytes** [comment]
gost只管转发数据，不管你是具体是什么内容
trojan也好，v2ray也罢... 这些只不过是待传输的tcp数据包而已

所以你的这个问题，基本上等价于“gost怎么用”... :(
