### ISSUE TITLE
bypass是否支持来源ip或者来源mac地址过滤

### ISSUE THREAD

**Issue by qwasdr2** [go-gost/gost#313]
局域网中提供了一个gost代理转发，转发链条中有很多个nodes，现在希望局域网不同机器过打到gost的流量走不同的node，所以在node中配置了bypass，CIDR支持来源IP吗（我试了在node中加bypass配置CIDR来源判定没生效）？如果不支持，是否可以在http插件中新增来源ip或者来源mac信息，我自己写接口实现呢？

**Comment by zhfish** [comment]
mark

**Comment by ginuerzh** [comment]
Bypass是根据请求的目标地址来路由，而不是客户端的源地址。如果你想要根据源地址来选择上游节点，可以使用Hop插件，这样上游节点的选择完全可以自己控制。
https://gost.run/concepts/hop/#_9
