### ISSUE TITLE
请问，gost.plus访问是不是无法使用了？

### ISSUE THREAD

**Issue by lhc-ltd** [go-gost/gost#314]
看到教程里 http文件服务 里的 公网临时访问，提到可以用GOST.PLUS提供临时访问。
请问现在这个服务是不是已经停止了？

用教程代码在windows下运行报错：
gost -L file://:8080 -L rtcp://:0/:8080 -F tunnel+wss://tunnel.gost.plus:443
{"handler":"auto","kind":"service","level":"info","listener":"tcp","msg":"listening on [::]:8080/tcp","service":"service-0","time":"2023-10-25T14:42:01.736+08:00"}
{"handler":"rtcp","kind":"service","level":"info","listener":"rtcp","msg":"listening on :0/tcp","service":"service-1","time":"2023-10-25T14:42:01.754+08:00"}
{"handler":"rtcp","kind":"listener","level":"error","listener":"rtcp","msg":"route(retry=0) bind unsupported","service":"service-1","time":"2023-10-25T14:42:02.574+08:00"}
{"handler":"rtcp","kind":"service","level":"warning","listener":"rtcp","msg":"accept: bind unsupported, retrying in 1s","service":"service-1","time":"2023-10-25T14:42:02.575+08:00"}
{"handler":"rtcp","kind":"listener","level":"error","listener":"rtcp","msg":"route(retry=0) bind unsupported","service":"service-1","time":"2023-10-25T14:42:04.079+08:00"}
{"handler":"rtcp","kind":"service","level":"warning","listener":"rtcp","msg":"accept: bind unsupported, retrying in 2s","service":"service-1","time":"2023-10-25T14:42:04.080+08:00"}

尝试过更改端口，错误依旧。

**Comment by ginuerzh** [comment]
需要使用rc10版本
https://github.com/go-gost/gost/releases/tag/v3.0.0-rc10

**Comment by lhc-ltd** [comment]
谢谢，我试试

**Comment by lhc-ltd** [comment]
感谢，测试可以访问，great tool ！
