### ISSUE TITLE
最新的v3.0.0-nightly.20231030运行报错

### ISSUE THREAD

**Issue by praglody** [go-gost/gost#317]
{"level":"error","msg":"connector 93c51954-a543-45bb-8145-376643971ae3: EOF","time":"2023-10-31T17:20:27.900+08:00"}
fatal error: sync: Unlock of unlocked RWMutex

goroutine 28 [running]:
sync.fatal({0x138f54f?, 0x1239400?})
        /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:1061 +0x18
sync.(*RWMutex).Unlock(0xc00056c3d8)
        /opt/hostedtoolcache/go/1.21.3/x64/src/sync/rwmutex.go:209 +0x45
github.com/go-gost/x/handler/tunnel.(*Tunnel).clean(0xc00056c380)
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20231029022713-e8d5e719a434/handler/tunnel/tunnel.go:174 +0x91
created by github.com/go-gost/x/handler/tunnel.NewTunnel in goroutine 12
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20231029022713-e8d5e719a434/handler/tunnel/tunnel.go:76 +0xef

goroutine 1 [select]:
github.com/judwhite/go-svc.Run({0x1532d08, 0x2401300}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/judwhite/go-svc@v1.2.1/svc_common.go:39 +0x1a5
main.main()
        /home/runner/work/gost/gost/cmd/gost/main.go:94 +0x28

goroutine 6 [sleep]:
time.Sleep(0x45d964b800)
        /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/time.go:195 +0x125
github.com/shadowsocks/shadowsocks-go/shadowsocks.newReqList.func1()
        /home/runner/go/pkg/mod/github.com/shadowsocks/shadowsocks-go@v0.0.0-20200409064450-3e585ff90601/shadowsocks/udprelay.go:82 +0x25
created by github.com/shadowsocks/shadowsocks-go/shadowsocks.newReqList in goroutine 1
        /home/runner/go/pkg/mod/github.com/shadowsocks/shadowsocks-go@v0.0.0-20200409064450-3e585ff90601/shadowsocks/udprelay.go:80 +0x8d

goroutine 7 [select]:
github.com/xtaci/kcp-go/v5.(*TimedSched).sched(0xc0004f4910)
        /home/runner/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.6.1/timedsched.go:67 +0x105
created by github.com/xtaci/kcp-go/v5.NewTimedSched in goroutine 1
        /home/runner/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.6.1/timedsched.go:56 +0xe6

goroutine 8 [select]:
github.com/xtaci/kcp-go/v5.(*TimedSched).sched(0xc0004f4910)
        /home/runner/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.6.1/timedsched.go:67 +0x105
created by github.com/xtaci/kcp-go/v5.NewTimedSched in goroutine 1
        /home/runner/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.6.1/timedsched.go:56 +0xe6

goroutine 9 [select]:
github.com/xtaci/kcp-go/v5.(*TimedSched).prepend(0xc0004f4910)
        /home/runner/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.6.1/timedsched.go:103 +0x8a
created by github.com/xtaci/kcp-go/v5.NewTimedSched in goroutine 1
        /home/runner/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.6.1/timedsched.go:58 +0x176

goroutine 19 [chan receive]:
github.com/go-gost/x/handler/tunnel.(*ConnectorPool).closeIdles(0xc000680db0)
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20231029022713-e8d5e719a434/handler/tunnel/tunnel.go:235 +0xa9
created by github.com/go-gost/x/handler/tunnel.NewConnectorPool in goroutine 1
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20231029022713-e8d5e719a434/handler/tunnel/tunnel.go:191 +0x89

goroutine 20 [IO wait]:
internal/poll.runtime_pollWait(0x7f8e7c967ee0, 0x72)
        /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc00056c280?, 0x5452b2?, 0x0)
        /opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00056c280)
        /opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc00056c280)
        /opt/hostedtoolcache/go/1.21.3/x64/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc00060e2a0)
        /opt/hostedtoolcache/go/1.21.3/x64/src/net/tcpsock_posix.go:152 +0x1e
net.(*TCPListener).Accept(0xc00060e2a0)
        /opt/hostedtoolcache/go/1.21.3/x64/src/net/tcpsock.go:315 +0x30
github.com/go-gost/x/admission/wrapper.(*listener).Accept(0xc000680cc0)
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20231029022713-e8d5e719a434/admission/wrapper/listener.go:29 +0x3e
github.com/go-gost/x/listener/tcp.(*tcpListener).Accept(0xc00003ed80?)
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20231029022713-e8d5e719a434/listener/tcp/listener.go:75 +0x1b
github.com/go-gost/x/service.(*defaultService).Serve(0xc0002968f0)
        /home/runner/go/pkg/mod/github.com/go-gost/x@v0.0.0-20231029022713-e8d5e719a434/service/service.go:127 +0x123
main.(*program).Start.func4()
        /home/runner/work/gost/gost/cmd/gost/program.go:136 +0x1c
created by main.(*program).Start in goroutine 1
        /home/runner/work/gost/gost/cmd/gost/program.go:135 +0x330

goroutine 22 [syscall]:
os/signal.signal_recv()
        /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
        /opt/hostedtoolcache/go/1.21.3/x64/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 1
        /opt/hostedtoolcache/go/1.21.3/x64/src/os/signal/signal.go:151 +0x1f

**Comment by ginuerzh** [comment]
后续版本已修复

**Comment by praglody** [comment]
感谢！
