### ISSUE TITLE
Ingress功能目前功能无法满足需求，希望可以改进一下

### ISSUE THREAD

**Issue by praglody** [go-gost/gost#318]
目前Ingress只能通过区分hostname去路由，但是实际使用中，每个hostname上有不同端口的服务，这样就没办去路由了。

**Comment by ginuerzh** [comment]
Ingress通过hostname找到对应的隧道ID，每个隧道对应一个服务，不同的端口需要开启不同的隧道。

**Comment by praglody** [comment]
感谢，是我之前没有弄明白怎么用。

**Comment by ginuerzh** [comment]
上面的解释不是很准确。
隧道的作用是对流量进行转发，对于HTTP流量是根据Host头来路由，但是也可以做到一对多的路由，例如可以将*.example.com的流量都路由到同一个隧道，客户端可以根据Host再次路由，a.example.com对应服务A，b.example.com对应服务B。
对于非HTTP流量(TCP/UDP)，其行为类似于端口转发，hostname在这里同样只是起到隧道路由的作用，至于流量最终到达哪个服务(端口)，是由客户端来决定的。

**Comment by praglody** [comment]
感谢您的耐心解释！经过翻阅官网的文档，基本已经弄明白怎么回事了。之前我将hostname理解成了http协议中的Host，现在知道http协议和其它协议其实都可以自行配置hostname来进行路由。

**Comment by ginuerzh** [comment]
通过hostname方式来对流量统一路由，使用上会更加直观和灵活，另外服务端也不需要暴露端口，隧道也会更加安全。
