### ISSUE TITLE
关于自建公共反向代理服务

### ISSUE THREAD

**Issue by kssion** [go-gost/gost#321]
公共反向代理服务，可以自行搭建吗？有什么条件，服务端怎么配置？

**Comment by ginuerzh** [comment]
简单版本(docker-compose)：https://gost.run/blog/2023/gost-plus/#_3
复杂版本：https://gost.run/tutorials/reverse-proxy-tunnel-ha/#_3

**Comment by kssion** [comment]
好的，我试试看。

**Comment by kssion** [comment]
可以 没问题 感谢！
