### ISSUE TITLE
gost是否可以指定访问远程服务器的端口

### ISSUE THREAD

**Issue by wpzzz** [go-gost/gost#322]
例如 ./gost -L ss://:8080
一个简单的代理，希望只允许用户访问80和443端口，防止滥用 。用iptables可以实现 但不优雅

**Comment by ginuerzh** [comment]
可以通过bypass来限制端口
```
gost -L ss://:8080?bypass=~*:80,*:443
```
https://gost.run/concepts/bypass/#_5
