### ISSUE TITLE
一个程序多个隧道应该怎么写

### ISSUE THREAD

**Issue by wpzzz** [go-gost/gost#327]
-L tcp://:2222 -F relay+tls://1.1.1.1:1234
 -L tcp://:3333 -F relay+tls://2.2.2.2:1234
两个相互独立的隧道，可以用一个命令执行吗

**Comment by kuaizi** [comment]
-L tcp://:2222 -F relay+tls://1.1.1.1:1234 -- -L tcp://:3333 -F relay+tls://2.2.2.2:1234

https://github.com/go-gost/gost/commit/5d9d33f368e641b150fe94a73e3cebfd220e567b
Add -- cmd flag separator to start different Gost processes

**Comment by wpzzz** [comment]
谢谢
