### ISSUE TITLE
Can't bypass when transport via UDP

### ISSUE THREAD

**Issue by iLemonRain** [go-gost/gost#328]
When I transport via UDP, I get the bypassRequest like
Network: "udp"
Addr: "10.192.34.60:10001"
Host: ""
Client: ""

Client always be "", while tcp protocol with the user name I set.

**Comment by iLemonRain** [comment]
gost version: [v3.0.0-nightly.20231112](https://github.com/go-gost/gost/releases/tag/v3.0.0-nightly.20231112)

hello, I set up the http handler like

```
func authHandler(c *gin.Context) {
	var req autherRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	userName := req.Username
	password := req.Password
	resp := autherResponse{}
	if s.VerifyKeyToken(userName, password) {
		resp.OK = true
		resp.ID = userName
	} else {
		resp.OK = false
		resp.ID = userName
	}
	// fmt.Printf("%v\n", resp)
	c.JSON(http.StatusOK, resp)
} 

func bypassHandler(c *gin.Context) {
	var req bypassRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	protocol := req.Network
	addr := req.Addr
	// host := req.Host
	loginKey := req.Client
	resp := bypassResponse{}
        ...
}
```

authHandler runs without any issue on both tcp and udp, I got the return value like:
```
OK:true
ID:"user1"
```
when it was udp, I got the req like:
```
Network: "udp"
Addr: "10.192.34.60:10001"
Host: ""
Client: ""
``` 
while tcp I got:
```
Network: "tcp"
Addr: "10.192.34.60:10001"
Host: ""
Client: "user1"
```
with the right client that I set in authHandler.

**Comment by iLemonRain** [comment]
And I found this issue when I tested the udp performance of server by iperf3.
iperf3 -c ********** -p 10001 -u

**Comment by ginuerzh** [comment]
Could you share your gost configuration?

**Comment by iLemonRain** [comment]
sure.
server:
```
{
    "api": {
        "addr": ":18080",
        "auth": {
            "password": "password",
            "username": "admin"
        },
        "pathPrefix": "/api"
    },
    "authers": [
        {
            "name": "auther-0",
            "plugin": {
                "addr": "http://127.0.0.1:8000/auth",
                "type": "http"
            }
        }
    ],
    "bypasses": [
        {
            "name": "bypass-0",
            "plugin": {
                "addr": "http://127.0.0.1:8000/bypass",
                "type": "http"
            },
            "whitelist": true
        }
    ],
    "metrics": {
        "addr": ":9000",
        "path": "/metrics"
    },
    "services": [
        {
            "addr": ":8771",
            "bypass": "bypass-0",
            "handler": {
                "auther": "auther-0",
                "type": "socks",
                "metadata": {
                    "udp": true
                }
            },
            "listener": {
                "type": "wss"
            },
            "name": "service-0"
        }
    ]
}
```
client:
{
    "services": [
        {
            "name": "service-0",
            "addr": ":8080",
            "handler": {
                "type": "ssu",
                "chain": "chain-0",
                "auth": {
                    "username": "AEAD_CHACHA20_POLY1305",
                    "password": "123456"
                }
            },
            "listener": {
                "type": "udp"
            }
        },
        {
            "name": "service-1",
            "addr": ":8080",
            "handler": {
                "type": "ss",
                "chain": "chain-0",
                "auth": {
                    "username": "AEAD_CHACHA20_POLY1305",
                    "password": "123456"
                }
            },
            "listener": {
                "type": "tcp"
            }
        }
    ],
    "chains": [
        {
            "name": "chain-0",
            "hops": [
                {
                    "name": "hop-0",
                    "selector": {
                        "strategy": "round",
                        "maxFails": 2,
                        "failTimeout": 10000000000
                    },
                    "nodes": [
                        {
                            "name": "node-0",
                            "addr": "***.***.***.***:8771",
                            "connector": {
                                "type": "socks",
                                "auth": {
                                    "username": "user1",
                                    "password": "123456"
                                }
                            },
                            "dialer": {
                                "type": "wss"
                            }
                        }
                    ]
                }
            ]
        }
    ],
    "log": {
        "output": "stdout",
        "level": "info",
        "format": "json"
    },
    "api": {
        "addr": ":18080",
        "pathPrefix": "/api",
        "accesslog": true,
        "auth": {
            "username": "admin",
            "password": "password"
        }
    }
}

**Comment by iLemonRain** [comment]
seems related to x/internal/net/udp/relay.go

comment out this block of code at both line 61 and 101:
```
if r.bypass != nil && r.bypass.Contains(context.Background(), "udp", raddr.String()) {
	if r.logger != nil {
		r.logger.Warn("bypass: ", raddr)
	}
	return nil
}
```
will make udp packet relay to tcp and I can get normal bypassRequest since it won't return nil.
HOWEVER, it's not perfect since "Network" changed from "udp" to "tcp" in that connection, which is inconvenient for accurate bypass purpose.

**Comment by ginuerzh** [comment]
Try today's nightly version.

**Comment by iLemonRain** [comment]
> Try today's nightly version.

Availability confirmed. Great job and thanks!!
