### ISSUE TITLE
请问icmp可以加tls吗

### ISSUE THREAD

**Issue by wktd666** [go-gost/gost#33]
请问icmp可以加tls吗
类似于
客户端：./gost -L :1111/66.66.66.66:2141 -F icmp+tls://66.77.77.77:0 
服务端：./gost -L icmp+tls://:0?keepAlive=1

**Comment by ginuerzh** [comment]
ICMP是数据通道，数据封装在QUIC协议中，已经是加密的。

**Comment by egg1234** [comment]
@ginuerzh 
想请教一下keepAlive=1参数按一般理解应该是加在客户端的，为什么icmp协议下keepAlive=1参数是加在服务器端的？

谢谢！

**Comment by ginuerzh** [comment]
这个参数是QUIC的配置参数，两边都可以使用。
