### ISSUE TITLE
V3 websocket bug

### ISSUE THREAD

**Issue by clywm520** [go-gost/gost#333]
服务端
gost -L "tun://:8421?net=192.168.123.1/24&gw=192.168.123.2&route=192.168.1.0/24" -L "relay+ws://123:123@:40257?bind=true&path=/"

客户端
gost -L "tun://:0/:8421?net=192.168.123.2/24&gw=192.168.123.1&route=10.0.12.0/24" -F "relay+wss://123:123@SERVERIP:19443?path=/"

换成V3版本后，不稳定。如果服务端Ctrl+C中止服务,然后再开启，客户端都再也连接不上了 。再连接时，服务端经常报
{"handler":"tun","kind":"handler","level":"warning","listener":"tun","local":":8421","msg":"unknown packet, discarded","remote":"192.168.123.1","service":"service-0","time":"2023-11-14T19:50:55.939+08:00"}
重试好多次，也没有作用了

**Comment by ginuerzh** [comment]
今天的nightly版本中应该已经修复
