### ISSUE TITLE
Will speed limiter support plugin system?

### ISSUE THREAD

**Issue by iLemonRain** [go-gost/gost#337]
It will make this project better if plugin system can be used in Speed Limiter.
Since plugin system has been support Authenticator and Bypass, if it support limiter in the future plan, we can add rules just like

name: user1    dst：***.***.***.***    port：80    upload: 2MB    download: 10MB
name: user2    dst：***.***.***.***    port：443    upload: 50MB    download: 100MB

we can get "name", "dst", "port" from given params just like what Bypass plugin did.

This could be very helpful.
Again, I appreciate all your help and please let me know if you have any plan on it.

**Comment by ginuerzh** [comment]
See https://latest.gost.run/en/concepts/limiter/#plugin and https://latest.gost.run/en/concepts/limiter/#limiter-in-service-handler

**Comment by iLemonRain** [comment]
thanks!
I have tried 20231118 nightly. The input params should be like `{"network":"tcp","addr":"example.com:443","client":"gost","src":"192.168.1.1:12345"}`
Unfortunately I saw {"network":"","addr":"","client":"","src":""} instead, no available value provided. Maybe need some  fix on it.
The hardcoded return value {"in":1048576, "out":524288} worked fine 🎉
my config:
```
{  
    "authers": [
        {
            "name": "auther-0",
            "plugin": {
                "addr": "http://127.0.0.1:8000/auth",
                "type": "http"
            }
        }
    ],
    "bypasses": [
        {
            "name": "bypass-0",
            "plugin": {
                "addr": "http://127.0.0.1:8000/bypass",
                "type": "http"
            },
            "whitelist": true
        }
    ],
    "limiters": [
        {
            "name": "limiter-0",
            "plugin": {
                "addr": "http://127.0.0.1:8000/limitTraffic",
                "type": "http"
            }
        }
    ],
    "services": [
        {
            "name": "service-1",
            "addr": ":8771",
            "limiter": "limiter-0",
            "bypass": "bypass-0",
            "handler": {
                "type": "socks",
                "auther": "auther-0",
                "metadata": {
                    "udp": true
                }
            },
            "listener": {
                "type": "wss"
            }
        }
    ]
}
```

**Comment by iLemonRain** [comment]
> thanks! I have tried 20231118 nightly. The input params should be like `{"network":"tcp","addr":"example.com:443","client":"gost","src":"192.168.1.1:12345"}` Unfortunately I saw {"network":"","addr":"","client":"","src":""} instead, no available value provided. Maybe need some fix on it. The hardcoded return value {"in":1048576, "out":524288} worked fine 🎉 my config:
> 
> ```
> {  
>     "authers": [
>         {
>             "name": "auther-0",
>             "plugin": {
>                 "addr": "http://127.0.0.1:8000/auth",
>                 "type": "http"
>             }
>         }
>     ],
>     "bypasses": [
>         {
>             "name": "bypass-0",
>             "plugin": {
>                 "addr": "http://127.0.0.1:8000/bypass",
>                 "type": "http"
>             },
>             "whitelist": true
>         }
>     ],
>     "limiters": [
>         {
>             "name": "limiter-0",
>             "plugin": {
>                 "addr": "http://127.0.0.1:8000/limitTraffic",
>                 "type": "http"
>             }
>         }
>     ],
>     "services": [
>         {
>             "name": "service-1",
>             "addr": ":8771",
>             "limiter": "limiter-0",
>             "bypass": "bypass-0",
>             "handler": {
>                 "type": "socks",
>                 "auther": "auther-0",
>                 "metadata": {
>                     "udp": true
>                 }
>             },
>             "listener": {
>                 "type": "wss"
>             }
>         }
>     ]
> }
> ```

Sorry, my bad. It should be
```
    "services": [
        {
            "name": "service-1",
            "addr": ":8771",
            "bypass": "bypass-0",
            "handler": {
                "type": "socks",
                "limiter": "limiter-0",
                "auther": "auther-0",
                "metadata": {
                    "udp": true
                }
            },
            "listener": {
                "type": "wss"
            }
        }
    ]
```
And non-value error didn't occur again.
In addition, the "In" and "Out" params seems to be "limiter.conn.in" and "limiter.conn.out" that mentioned in [https://gost.run/en/concepts/limiter/](url)
will you support "limiter.in" and "limiter.out" in return value?

**Comment by ginuerzh** [comment]
The traffic limiter plugin has added a new parameter: `scope`. For the handler limiter, the scope value will be set to `client`, then the plugin can return different configurations based on the value of the `client` parameter.
```
{"scope":"client","service":"service-0","network":"tcp","addr":"example.com:443","client":"gost","src":"192.168.1.1:12345"}
```
