### ISSUE TITLE
support logging per service level using yml file

### ISSUE THREAD

**Issue by phpmathan** [go-gost/gost#339]
First of all, thank you for the super good tool that makes my life easier.

I defined multiple services like HTTP proxy, reverse proxy, port forwarding, etc., in separate yml files and ran multiple processes of gost, because to separate the logging to different files.

It will be helpful to define the logging option per service level like "admissions" kind of definition so that a single process of gost will do logging to different files based on the definition at the service level.

**Comment by ginuerzh** [comment]
https://latest.gost.run/en/tutorials/log/#logger
