### ISSUE TITLE
Possible malware in Windows binary for 2.11.2

### ISSUE THREAD

**Issue by stevenmcdonald** [go-gost/gost#34]
I downloaded https://github.com/ginuerzh/gost/releases/download/v2.11.2/gost-windows-386-2.11.2.zip and Windows Defender warns it contains "Program:Win32/Uwamson.A!ml", they don't really give any info: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Program%3aWin32%2fUwamson.A!ml&threatid=250070

it might be related to this malware: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Uwamson&ThreatID=2147734168

or maybe a false positive?

**Comment by egg1234** [comment]
刚刚下载https://github.com/ginuerzh/gost/releases/download/v2.11.2/gost-windows-amd64-2.11.2.zip到windows 10暂时没有报告说检测出病毒，
而且把gost-windows-amd64-2.11.2.zip解压后的exe文件上载到https://www.virustotal.com/gui/home/upload进行检测，也暂时没有报告检测到病毒

**Comment by egg1234** [comment]
刚刚下载32位的版本https://github.com/ginuerzh/gost/releases/download/v2.11.2/gost-windows-386-2.11.2.zip 到windows 10及windows 7暂时没有报告说检测出病毒，

把32位版gost-windows-386-2.11.2.zip解压后的exe文件上载到https://www.virustotal.com/gui/home/upload进行检测，的确有17个防病毒软件报告有问题

**Comment by stevenmcdonald** [comment]
Sounds like this is likely a false positive, closing this issue
