### ISSUE TITLE
第三方go应用如何快速嵌入gost

### ISSUE THREAD

**Issue by clywm520** [go-gost/gost#343]
第三方go应用如何快速嵌入gost

**Comment by clywm520** [comment]
@ginuerzh  大佬，第三方go应用如何快速将gost嵌入呀

**Comment by ginuerzh** [comment]
两种方式：
1. 直接调用[go-gost/x](https://github.com/go-gost/x)库集成需要的功能。
2. 集成gost二进制，开启API服务，以Web API方式控制。
