### ISSUE TITLE
tls证书问题

### ISSUE THREAD

**Issue by chenhg** [go-gost/gost#344]
你好，在用gost做隧道转发（relay+tls）的时候，比如访问tiktok时，需要用到tls证书，请问证书有什么要求？我们通过openssl生成的证书，在落地机报错：client didn't provide a certificate，请帮忙看一下呢。

**Comment by chenhg** [comment]
<img width="752" alt="微信图片_20231122121356" src="https://github.com/go-gost/gost/assets/3351004/8ca1f576-e483-43e7-ba5a-7375f99b50a1">

**Comment by woodlyer** [comment]
> 你好，在用gost做隧道转发（relay+tls）的时候，比如访问tiktok时，需要用到tls证书，请问证书有什么要求？我们通过openssl生成的证书，在落地机报错：client didn't provide a certificate，请帮忙看一下呢。

建议先看一下官方文档。 
https://gost.run/tutorials/tls/
