### ISSUE TITLE
请问 gost 如何实现两台不同物理位置的主机之间相互通讯？

### ISSUE THREAD

**Issue by m2acgi** [go-gost/gost#346]
- Internet gost server
- LAN PC: A
- LAN PC: B

请问如何让 A 访问 `B:1234` ? 

或者是否能达到以下目的:
A: `tar -czf - * | gost server --xxx`
B: `gost server --xxx | tar -xzf -`
也就是通过 gost 中转，实现 A 向 B 通过 pipe 传输数据。

**Comment by kuaizi** [comment]
rtcp 远程转发nc端口

**Comment by cnwhy** [comment]
需要一台 和 A B 都通的第三台机器做中转才能用gost;  
如果没有第三台机器，可以用 试都用 GOST官方提供的公共服务 [公共反向代理服务](https://gost.run/blog/2023/gost-plus/)

**Comment by m2acgi** [comment]
@kuaizi 至少要设置两次端口转发或远程端口转发才能实现 `A 访问 B:1234`

@cnwhy 有 vps, Internet gost server 就是指位于互联网上的 gost 服务器

**Comment by cnwhy** [comment]
@m2acgi 不想折腾就直接上 zerotier  

用gost的话，可以 vps 启用 bind ，B 的 1234 远程反向代理到 B的哪个端口上，A使用vps的那个端口向B推数据了，pipe 应该没问题才对 

大概是这样 ：
```
// vps:
gost -L socks5://:1080?bind=true&udp=true

// B:
gost -L rtcp://:1234/:1234 -F socks5://x.x.x.x:1080
```

**Comment by m2acgi** [comment]
如果用 nc, rtcp 出来的端口没有任何安全保护，不安全。这个可以解决:

- server: piping-server (https://github.com/nwtgck/piping-server)
- A: `curl -T "test.dat" https://ppng.io/hello`
- B: `curl https://ppng.io/hello > "test.dat"`

**Comment by m2acgi** [comment]
如果 gost 支持这个功能就好了。
