### ISSUE TITLE
请问icmp可以直接做出口吗？

### ISSUE THREAD

**Issue by egg1234** [go-gost/gost#35]
类似下面这样的配置可以在服务器端转发数据吗？还是必须"socks5+icmp"或承载其它协议?

服务端：./gost -L=icmp://:0?keepAlive=1

客户端：./gost -L=:1111 -F=icmp://22.22.22.22:0?keepAlive=1

谢谢！

**Comment by ginuerzh** [comment]
icmp是数据通道，用法与kcp, tls等一致。
