### ISSUE TITLE
能否支持限制器插件调用时传入每个请求的大小

### ISSUE THREAD

**Issue by rico0808** [go-gost/gost#364]
目前限制器请求插件接口时仅传入了以下几个参数，并没有传入请求的具体大小。这样没办法去统计一个client所消耗的总流量大小。

如果我描述的不清晰的话通俗理解就是流量限制。

`{
  network: 'tcp',
  addr: 'www.baidu.com:443',
  client: 'user',
  src: '127.0.0.1:58213',
}`

**Comment by ginuerzh** [comment]
后面会单独增加流量上报插件。

**Comment by rico0808** [comment]
> 后面会单独增加流量上报插件。

是的，我的目的就是流量上报，预计24年1季度会更新吗？

**Comment by ginuerzh** [comment]
已支持流量统计上报功能:
https://gost.run/concepts/observer/
