### ISSUE TITLE
请问远程端口转发是否与反向代理隧道作用类似？

### ISSUE THREAD

**Issue by m2acgi** [go-gost/gost#373]
请问远程端口转发是否与反向代理隧道作用类似？

**Comment by ginuerzh** [comment]
原理是一样的，功能上定位不同。

**Comment by m2acgi** [comment]
根据文档，反向代理隧道功能更强大，相当于是用域名对应到不同的 client service port 上了，我的理解正确吗？假设只远程转发一个端口的情况下，两者功能是否完全相同呢？

**Comment by ginuerzh** [comment]
二者之间一个主要的不同是反向代理隧道不会在服务端暴露端口，其服务端的功能更像是一个路由器，负责对隧道进行路由。而远程端口转发会在服务端监听端口，是一种直接的端口映射。
