### ISSUE TITLE
web api怎么开启鉴权，命令行参数怎么拼？

### ISSUE THREAD

**Issue by ningyf** [go-gost/gost#387]
试了几个schema类型的，都提示错误，这个命令行参数怎么拼？配置文件里的auth都是对代理设置的，不是对api设置的。

**Comment by ginuerzh** [comment]
已添加对命令行的支持
```
gost -api user:pass@:18080
```
https://latest.gost.run/tutorials/api/overview/#web-api

**Comment by ningyf** [comment]
awesome
