### ISSUE TITLE
分流的bypass无法使用

### ISSUE THREAD

**Issue by mjh-jason** [go-gost/gost#39]
我测试的过程中，拦截百度的访问：
./gost -api :9000 -L http://:1080 -F http://用户名:密码@168.158.199.186:12323?bypass=*.baidu.com
以这样的方式运行命令，但是无法拦截百度的访问

**Comment by mjh-jason** [comment]
大佬有空的时候，求解答一下，谢谢哈

**Comment by ginuerzh** [comment]
如果拦截包括`baidu.com`，可以使用`bypass=.baidu.com`。
`*.baidu.com`包括baidu.com的所有子域名但不包括baidu.com。
`.baidu.com`包括baidu.com本身及其所有子域名。

**Comment by mjh-jason** [comment]
谢谢作者大佬的解答：
但是我发现，我发现改为.baidu.com的时候确实生效了，但是还是会由本机的ip做处理，只是不会做转发。
能够实现拦截某个网站的访问。
谢谢。

**Comment by ginuerzh** [comment]
试试
```
./gost -api :9000 -L http://:1080?bypass=.baidu.com -F http://用户名:密码@168.158.199.186:12323
```

**Comment by mjh-jason** [comment]
> 试试
> 
> ```
> ./gost -api :9000 -L http://:1080?bypass=.baidu.com -F http://用户名:密码@168.158.199.186:12323
> ```

谢谢，可以实现，已解决

**Comment by mjh-jason** [comment]
拦截后，刷新几遍后又可以打开了...有点奇怪
