### ISSUE TITLE
websocket local forward Error

### ISSUE THREAD

**Issue by zhaocaipeng** [go-gost/gost#394]
我本机有个websocket服务，服务path不是"/ws"是全局"/".现在想用gost做加密和压缩通道。
我自己的ws服务在5188端口。我想在同一台机器上启一个gost的5189服务，先单纯测试gost的ws转发
gost版本:v3
启动命令:./gost -L "ws://:5189?path=/" -F "ws://:5188?path=/"
当我的客户端访问5188的时候显示服务正常。但是只要走5189代理服务，就会报错。并且在我的5188服务后台日志没看到新连接接入
![Uploading image.png…]()

**Comment by ginuerzh** [comment]
你这是代理模式不是转发。
