### ISSUE TITLE
[Feature Request] bypass支持反向匹配

### ISSUE THREAD

**Issue by fanthos** [go-gost/gost#398]
希望10.100.0.0/16匹配，但是10.100.0.1和10.100.0.2不匹配。目前需要给这个新建多条策略以完成这个匹配。
加入反向匹配之后旧可以用
```
!10.100.0.1/32
!10.100.0.1/32
10.100.0.0/16
```
```
!dl.baidu.com
.baidu.com
```
做到这个匹配。

类似，ip段应该也不难支持，比如10.0.0.0-10.254.255.255

**Comment by ginuerzh** [comment]
这样会使bypass复杂化，暂不考虑。

**Comment by fanthos** [comment]
建议先支持ip区间匹配，比如1.1.0.0-1.120.255.255。ip区间匹配比cidr在很多情况下会少很多条策略。

**Comment by ginuerzh** [comment]
新版本中已经支持IP范围匹配。
