### ISSUE TITLE
http2 协议兼容一下gprc，

### ISSUE THREAD

**Issue by f4nff** [go-gost/gost#4]
[https://github.com/Qv2ray/gun](https://github.com/Qv2ray/gun)

grpc基于http2，

https://support.cloudflare.com/hc/zh-cn/articles/360050483011-%E4%BA%86%E8%A7%A3-Cloudflare-gRPC-%E6%94%AF%E6%8C%81

这样可以穿cdn

**Comment by ginuerzh** [comment]
已经支持gRPC：https://latest.gost.run/tutorials/http-tunnel/#grpc

**Comment by NightMachinery** [comment]
Is `grpc` proxying still offered by Cloudflare?
