### ISSUE TITLE
[Feature Request] 增加选择器插件

### ISSUE THREAD

**Issue by kimoziiiii** [go-gost/gost#401]
能否增加选择器插件，可以自定义监测器探测节点是否正常，结合参数maxFails + failTimeout，可以的话增加节点黑名单，这样保证上游的节点都是可用的状态。目前maxFails参数由局限性，比如多网络出口场景中，某网卡卸载分离（AWS中可用分离），会报错无此接口，但是也不会转移到另外一个正常的网卡进行通信。

**Comment by kimoziiiii** [comment]
我理解或许应该添加一个节点监测器，这样可用定义节点是否正常或失败。

**Comment by ginuerzh** [comment]
你可以选择使用[Hop插件](https://gost.run/concepts/hop/#_9)，这样节点完全由插件服务来控制。

**Comment by kimoziiiii** [comment]
思路打开了 谢谢 👍
