### ISSUE TITLE
请问 tcp 怎么分流？设置bypass无效。

### ISSUE THREAD

**Issue by superen7527** [go-gost/gost#405]
目前是 gost -L tcp://:80/1.2.3.6:80 访问本地80相当于远程服务器80。因为单纯反向代理http有问题只能通过tcp，可是这样bypass就没效果了，测试了配置文件模式启动也是没效果。

场景是远程跑了个web，通过hostname加载不同的界面，想让非白名单的hostname禁止访问。现在是远程服务器根据hostname拦截了，但是还会有数据传输显示错误状态码 想在gost这里直接拦下来，比较干脆利落。

好像没考虑到tcp作用于网页转发的情况？(另外http反向代理以后会支持命令行写法吗？目前只能配置文件启动)

**Comment by ginuerzh** [comment]
你应该使用[反向代理](https://gost.run/tutorials/reverse-proxy/)，根据主机名进行分流。
