### ISSUE TITLE
反向代理隧道问题

### ISSUE THREAD

**Issue by vjeson** [go-gost/gost#418]
根据这个教程
https://latest.gost.run/tutorials/reverse-proxy-tunnel/  测试能够实现基于http协议的反向代理，

但是无法代理tcp协议的服务，比如rdp,ssh服务

比如我想把内网机器rdp端口3389通过公网服务器的 4389暴露到公网，应该怎么配置可以实现？

当代理ssh端口的时候，会报
ssh_exchange_identification: Connection closed by remote host
错误

**Comment by ginuerzh** [comment]
具体的配置？

**Comment by vjeson** [comment]
我的需求和你不太一样，我是要把内网的一个服务比如,内网22端口的ssh服务，通过公网端口转发出去
类似配置这样
`
gost -L "tunnel://:8443?entrypoint=:8422&tunnel=4d21094e-b74c-4916-86c1-d9fa36ea677b"

gost -L rtcp://:0/127.0.0.1:22 -F "tunnel://:8443?tunnel.id=4d21094e-b74c-4916-86c1-d9fa36ea677b"

本地ssh 22端口，通过gost转发，， 然后通过公网Ip:8422,端口，访问到内网的22ssh服务，
我测试过http协议的，反向代理确实可以，但是tcp协议好像不像，不管是ssh还是rdp,其实只需要透明转发内网tcp协议就行
`

**Comment by vjeson** [comment]
感谢解答，您说的这个方式，反向隧道代理我测试过确实可以，只是这种情况，需要在访问端再运行一个gost客户端，做隧道转发，这种情况适合安全要求比较高的情况，适合把2个内网隔离的服务打通 ，有些情况是想直接把内网的一个端口服务直接通过公网服务器的一个端口转发出去，就相当于端口映射， 这样让别人测试访问的时候直接通过公网Ip和端口就可以访问，不在需要本地运行一个gost客户端

entrypoint指定的入口仅支持HTTP流量，这个是出于什么原因，其实如果entrypoint能直接支持tcp,udp原始协议转发，就能达到我的需求，试过别的几个反向代理软件，都有类似的功能

**Comment by ginuerzh** [comment]
直接用远程端口转发就行了
https://gost.run/tutorials/port-forwarding/#_4

**Comment by vjeson** [comment]
远程端口转发貌似也不可以，因为 比如A机器内网， 可以直接访问到B机器公网， ，而B机器在公网和A机器不是同一个网段，没有通道连接，B机器并不能直接放到到Ａ机器

比如
`gost -L rtcp://:3389/public_ip:4389
`
首先，本地rdp服务是3389端口，本地肯定不能监听3389要起个端口转发到3389，  要通过公网ip 和4389从公网访问，应该怎么设置

**Comment by vjeson** [comment]
> @vjeson 你的 gost -L rtcp://:3389/public_ip:4389 这条命令的意思本来就是把本地的3389这个rdp端口远程转发给public_ip的4389端口，等于用户远程桌面访问public_ip的4389端口，就等于直接访问了本地机器的3389的rdp端口，前提是本地机器已经启动了rdp服务，因为启动了rdp服务就已经监听了3389端口了，所以不存在你说的要起个端口转发到3389
客户端
`
gost -L rtcp://:3389/public_ip:4389
`

服务端需要怎么做呢？我测试服务端
`
./gost -L tcp://:4389 
`

然后通过访问 public_ip:4389 ，并不通，网络报错 connect: connection refused" ，貌似服务端不能转发请求到客服端

**Comment by vjeson** [comment]
> 你搞错了这个命令的用法
> 
> 服务器端应该监听另外一种协议，例如 ./gost -L=quic://:50000
> 
> 客户端 ./gost -L=rtcp://:3389/public_ip:4389 -F=quic://public_ip:50000
> 
> rtcp不是让你监听的，它是一个通知命令，作用仅仅是通知服务器自己去监听4389端口，然后把4389的流量转发到客户端的3389端口而已

非常感谢您的指点，在您的提示下，结合文档，找到了可以的办法
正确的做法应该是
客户端
`
./gost -L=rtcp://:11922/127.0.0.1:3389 -F=socks5://public_ip:11923
`
服务端
`
./gost -L=socks5://:11923?bind=true
`
必须要设置bind
这样访问public_ip:11922 ,就可以直通内网3389了端口了，这里的rtcp有点绕，应该分2种情况，一种是本地监听，一种是让远程服务器监听
这样可以直接把内网的一个端口服务直接通过公网的某个端口暴露出去，别人可以直接通过公网ip和端口访问，这个非常类似frp的反向代理

感谢
