### ISSUE TITLE
v2的配置如何转成v3

### ISSUE THREAD

**Issue by mcat1997** [go-gost/gost#422]
v2的配置怎么改成v3呀，比如下面的这个配置

{
    "Routes": [
        {
            "ChainNodes": [
                "socks5+tls://username:password@服务端ip:4001"
            ],
            "ServeNodes": [
                "客户端ip:4001"
            ]
        }，
        {
            "ServeNodes": [
                "tcp://客户端ip:4002/服务端ip:4002"
            ]
        }
    ]
}

**Comment by ginuerzh** [comment]
你可以用以下等效命令转成配置文件格式
```
gost -L :4001 -L tcp://:4002/:4002 -F socks5+tls://username:password@SERVERIP:4001 -O yaml
```
