### ISSUE TITLE
关于映射器中指定hosts文件的问题

### ISSUE THREAD

**Issue by Typhonling** [go-gost/gost#428]
gost似乎不会动态读取file.path中指定的hosts文件？
当此hosts內容发生变动时，gost中对应的域名解析不会发生变化，仍旧使用启动时所获得的IP。

**Comment by ginuerzh** [comment]
需要开启热加载
https://gost.run/concepts/hosts/#_9

**Comment by Typhonling** [comment]
感谢，是我眼拙了
