### ISSUE TITLE
bypass是否支持在拦截后让流量重定向

### ISSUE THREAD

**Issue by iLemonRain** [go-gost/gost#432]
从客户端来讲，如果传出的流量被流量网关侧的bypass拦截，只能从日志里的host unreachable看出遇到访问失败了。
但是host unreachable同样适用于访问资源不存在等情形，所以客户端无法确切得知是否真的是因为被拦截。
所以麻烦bypass可以增加一个可选设置参数（比如叫redirect），在请求拒绝时重定向到指定的位置，不知道是否可行？

**Comment by ginuerzh** [comment]
Bypass的目的就是流量拦截，如果需要redirect也应该是额外的模块，而不应该由Bypass来处理。
