### ISSUE TITLE
Port Forwarding via ShadowSocks bug

### ISSUE THREAD

**Issue by philinp** [go-gost/gost#439]
Test#1 (connecting to ssh via socks4a)  is OK:
./gost -L socks4a://:1001
./gost -L tcp://:1002/127.0.0.1:22 -F socks4a://127.0.0.1:1001
```
# telnet 127.0.0.1 1002
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
SSH-2.0-OpenSSH_9.2p1
```

Test#2 (connecting to ssh via socks4a via shadowsocks) is failed:
./gost -L ss://:1003
./gost -L socks4a://:1004 -F ss://127.0.0.1:1003
./gost -L tcp://:1005/127.0.0.1:22 -F socks4a://127.0.0.1:1004
```
# telnet 127.0.0.1 1005
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
```

The problem is that the ssh banner doesn't show up in the Test#2.

PS:
Original go-shadowsocks2 is working OK and changing ss:// to kcp:// is working OK too.

Tested version:
```
# ./gost -V
gost v3.0.0-nightly.20240201 (go1.21.6 linux/386)
```

**Comment by ginuerzh** [comment]
You should add the `nodelay` option for ss client:
```
./gost -L socks4a://:1004 -F ss://127.0.0.1:1003?nodelay=true
```
