### ISSUE TITLE
标准SSH协议的远程端口转发功能不正常

### ISSUE THREAD

**Issue by m2acgi** [go-gost/gost#444]
操作系统:

- ssh server: almalinux 9
- client (gost): debian 12

gost 命令: `gost -L=rtcp://:33891/172.16.1.3:3389 -F sshd://user:pass@192.168.1.2:22`
ssh server 本机监听实际结果: `127.0.0.1:33891`, `[::1]:33891`
ssh server 本机监听期待结果: `0.0.0.0:33891`, `[::]:33891`

**Comment by ginuerzh** [comment]
See https://stackoverflow.com/a/23782581
