### ISSUE TITLE
How set custom dns in a socks5

### ISSUE THREAD

**Issue by kbond2024** [go-gost/gost#455]
Hello anyone help me i am making a socks5 locally by this

gost -L socks5://127.0.0.1:9989 -F socks5://mysocks:port 

the dns is resolving using my proxy how i am set for resolve custom dns like 8.8.8.8

**Comment by ginuerzh** [comment]
Try `resolver` option:
```
gost -L socks5://127.0.0.1:9989?resolver=8.8.8.8 -F socks5://mysocks:port
```
https://gost.run/en/concepts/resolver/
