### ISSUE TITLE
移除service后，日志文件依旧存在

### ISSUE THREAD

**Issue by mjh-jason** [go-gost/gost#46]
使用场景：
1.需要根据转发的服务统计流量使用情况。
2.创建service后，通过查看日志的output和input进行统计。
![image](https://user-images.githubusercontent.com/63330349/167082962-34d657ea-8dea-4f90-a6ca-5b5c0b2e1466.png)
3.发现通过API调用移除service后，查看日志依旧存在service。但是通过获取配置文件，发现已经被移除了。
![image](https://user-images.githubusercontent.com/63330349/167083410-d6e1ac76-e668-4dc0-8f51-b070e66122a0.png)

**Comment by mjh-jason** [comment]
希望实现，移除service后，日志文件也能够对应的消失这一块的内容，只有重新添加服务的时候再重新统计

**Comment by ginuerzh** [comment]
这是prometheus的机制，其并未提供清除功能。
