### ISSUE TITLE
3.0rc7及之后版本win10无法使用

### ISSUE THREAD

**Issue by RelicOfTesla** [go-gost/gost#461]
3.0.0rc6是正常的(git 1c2d9b2a5beaaf1395f6680f36df48863165d00b)，从rc7开始，到rc10以及nightly.20240201 都是无法链接。报ERR_SOCKS_CONNECTION_FAILED

go编译版本分别为go1.20.14与1.22.2
协议尝试了http2/mtls都不行

```
client:
gost -L :10806 -F mtls://aaa.bbb.com:5003

{"handler":"auto","kind":"service","level":"error","listener":"tcp","msg":"read tcp 192.168.1.22:56346->8.210.***.25:5003: wsarecv: An existing connection was forcibly closed by the remote host.","service":"service-0","time":"2024-04-23T13:41:58.609+08:00"}

server:
gost -L mtls://:5003

{"handler":"auto","kind":"listener","level":"error","listener":"mtls","msg":"accept stream: write tcp 172.31.***.1:5003->36.251.***.180:8**3: wsasend: An existing connection was forcibly closed by the remote host.","service":"service-0","time":"2024-04-23T13:41:58.338+08:00"}
```

win10 + chrome 124.0.6367.61
主要问题在于client客户端。客户端使用rc6，服务端用最新的nightly.20240201都没问题，但一旦客户端升级到rc7或以上就用不了了.

更确切点话，git acb8c5bd5397d7872f150c822c90611848314761 是正常的，git f02c9810f22ec6767d36956c5d83dfe670301f51 就不行了，中间还有个git fda6214c1263cd7b55147df33163943f75ea3646 编译失败就没测试了

**Comment by ginuerzh** [comment]
我单机上测试是没问题的

**Comment by RelicOfTesla** [comment]
试了下，使用国内机子正常，远端域名改成ip就正常了，使用香港机子被秒墙了，
看更新的代码，https://github.com/go-gost/x/commit/a0765edd405e4ccefeaf903ef039197b3340f6e4，应该是协议上带了域名，未备案香港机被秒墙
