### ISSUE TITLE
希望能提供一个不带路由功能的tun隧道选项

### ISSUE THREAD

**Issue by BaiMeow** [go-gost/gost#464]
我想使用gost作为一个比较有规模的组网项目的一部分去建立一些隧道，其中，内网路由部分已经由BGP管理，gost再管理路由反而会使其不可用。
因此希望有一个metadata选项可以关闭tun的路由，无论是什么ip的包，都直接转发到对端，就像allowips=0.0.0.0/0的wireguard那样

**Comment by ginuerzh** [comment]
你指的是客户端路由还是服务端路由，由于是CS架构，服务端需要路由到不同的客户端，除非是点对点模式。

**Comment by BaiMeow** [comment]
我指的就是点对点的模式，这种情况下，gost无需管理路由，只需转发

**Comment by BaiMeow** [comment]
很喜欢，我先试用试用

**Comment by BaiMeow** [comment]
很好用，谢谢师傅
