### ISSUE TITLE
怎么禁用sock5的udp over tcp？

### ISSUE THREAD

**Issue by PHCSJC** [go-gost/gost#471]
想要使用标准的udp sock5代理，但gost会把udp先转成tcp，请问怎么禁用udp over tcp呢？

**Comment by ginuerzh** [comment]
可以添加`relay=udp`选项试试
```
-F socks://:1080?relay=udp
```

**Comment by scruel** [comment]
@ginuerzh 貌似不行：
`gost -L :1080?udp=true`
这样后还是 socks5: UDP relay is disabled

**Comment by ginuerzh** [comment]
要加在客户端上。

**Comment by scruel** [comment]
> 要加在客户端上。

啊？客户端我不用 gost，配合 sing-box 一直无法联网，我看情况复现下后单开个 issue 吧
