### ISSUE TITLE
关于流量观测

### ISSUE THREAD

**Issue by wudgaby** [go-gost/gost#472]
在使用http插件流量监控时,观测到流量数据是累加的. 
后续是否会增加重置流量功能?
或只统计单次请求的流量.

**Comment by ginuerzh** [comment]
后面会考虑增加重置功能。
单次请求的统计有何意义？

**Comment by wudgaby** [comment]
可以统计到用户单次请求所用的流量

**Comment by ginuerzh** [comment]
不太现实
