### ISSUE TITLE
IP限速配置的问题

### ISSUE THREAD

**Issue by mdksl** [go-gost/gost#473]
场景：我有A,B两个中转，在A中转中配置了多个服务，转发到B的对应端口，例如监听A的4000端口，转发到B的4000端口，A的4001，转到B的4001
期望：在A中使用IP限速（IP为B的IP），使A中所有转到B的服务速度总和不超过10M
实际：
我进行了如下配置，但未生效。包括单个服务的限速也没有
{
    "name": "limiter-t",
    "limits": [
        "B的IP  10MB 10MB"
    ]
}

**Comment by ginuerzh** [comment]
完整的配置？

**Comment by mdksl** [comment]
服务A的配置
{
    "name": "service-5004-tcp",
    "addr": ":5004",
    "limiter": "limiter-test",
    "handler": {
        "type": "tcp"
    },
    "listener": {
        "type": "tcp"
    },
    "forwarder": {
        "nodes": [
            {
                "name": "target-0",
                "addr": "XXX.XXX.XXX.XXX:50720"
            }
        ]
    }
}

**Comment by mdksl** [comment]
服务配置
![image](https://github.com/go-gost/gost/assets/161801231/213d8afe-05fb-47a5-8b81-4f584e813bd3)
![image](https://github.com/go-gost/gost/assets/161801231/737ffee6-f57f-493e-9a33-a6121933b342)
限速配置
![image](https://github.com/go-gost/gost/assets/161801231/93b5e8a9-0387-4140-acdb-0eb8fad53ad4)

**Comment by ginuerzh** [comment]
限速配置是对客户端(相对于本服务)做限制，如果要限制A到B的速度应该在B端配置。
