### ISSUE TITLE
获取ip 有缓存

### ISSUE THREAD

**Issue by lc-c** [go-gost/gost#475]
gost -L socks5://xxx:pxxs@:8443 -F http://xxxxpyproxy.io:16666      转发到代理服务器 pyproxy  但是通过 http://api.myip.com/      https://ipinfo.io/json 网站 都无法获取新的ip，只有杀死gost重新开启才可以

**Comment by ginuerzh** [comment]
GOST本身不会对数据做缓存，请检查上下游是否存在缓存。

**Comment by lc-c** [comment]
> GOST本身不会对数据做缓存，请检查上下游是否存在缓存。

采用手机热点测试依旧不会切换ip

**Comment by lc-c** [comment]
> > GOST本身不会对数据做缓存，请检查上下游是否存在缓存。
> 
> 采用手机热点测试依旧不会切换ip，切不同ip测试接口获取的ip不同

通过curl 测试ip服务商代理是可以换ip的

**Comment by coralproxy** [comment]
我家的IP资源比灵匠ipidea的分站品易要便宜哦

**Comment by cakeip** [comment]
pyproxy是灵匠ipidea的分站，我家的海外住宅价格更低，物美价廉，你可以来试试

**Comment by cakeip** [comment]
独家住宅资源，非转售，最低$0.3/GB，欢迎真机，逆向，EMU等业务来测试https://www.cakeip.com

**Comment by lc-c** [comment]
> GOST本身不会对数据做缓存，请检查上下游是否存在缓存。

目前得知长链接会引起这个问题，默认是长链接吗
