### ISSUE TITLE
关于指关闭日志输出&resolver参数问题

### ISSUE THREAD

**Issue by yqk100** [go-gost/gost#481]
阅读了文档，好像没有通过指令当时关闭日志的输出，后期会考虑添加吗？
```
-F=https://baidu.com:8443?resolver=1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4
```
resolver参数指定了多个DNS，切换网络(WLAN→移动数据)会重新筛选最快的DNS进行解析域名吗？
resolver后期会添加定时筛选最快的DNS吗？

**Comment by ginuerzh** [comment]
> 阅读了文档，好像没有通过指令当时关闭日志的输出，后期会考虑添加吗？

日志支持服务级别的[日志记录器](https://gost.run/tutorials/log/#_5)，可以单独控制，全局日志不支持动态配置。

> ```
> -F=https://baidu.com:8443?resolver=1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4
> ```
> 
> resolver参数指定了多个DNS，切换网络(WLAN→移动数据)会重新筛选最快的DNS进行解析域名吗？ resolver后期会添加定时筛选最快的DNS吗？

暂时不考虑。
