### ISSUE TITLE
关于双栈隧道的搭建

### ISSUE THREAD

**Issue by helloworldiambeok** [go-gost/gost#483]
入口A 双栈
出口B 双栈
方式1:客户端使用ipv6 连接入口的ipv6，入口再连接出口的ipv6再落地，正常
方式2:客户端使用ipv4 连接入口的ipv4，入口再连接出口的ipv6再落地，不通
2种方式使用的命令是 
入口：./gost  udp://:33333 -L tcp://:33333 -F relay+tls://[XXX:XXX:XXX::]:33333
出口：./gost -L relay+tls://:33333/XXX.com:33333
这种是情况是没有 ipv4 to ipv6 造成的吗，是否缺少额外的命令呢

**Comment by ginuerzh** [comment]
日志有报错信息吗?

**Comment by helloworldiambeok** [comment]
方式1会有输出： {"handler":"tcp","kind":"handler","level":"info","listener":"tcp","local":"[入口ipv6]:33347","msg":"[客户端ip]:62597 <> [入口ipv6]:33347","remote":"[xx]:62597","service":"service-1","time":"2024-05-28T08:21:15.067Z"}
方式2没有任何提示

**Comment by helloworldiambeok** [comment]
解决了，是入口的ipv4 端口的问题，换了个端口就可以了，由于同一个端口ipv6是正常的，让我误以为ipv4的端口也没问题。
