### ISSUE TITLE
[Feature Request] Reconnecting WebSocket if the connection is dropped

### ISSUE THREAD

**Issue by marudevx** [go-gost/gost#484]
refer: [https://github.com/recws-org/recws](https://github.com/recws-org/recws)

Reconnecting WebSocket if the connection is dropped

It would be great to add this option. It helps maintain connectivity in situations where the network changes IP addresses, unexpectedly disconnects, or otherwise gets interrupted.

**Comment by ginuerzh** [comment]
Websocket is based on TCP, so a websocket-based tunnel is a reliable streaming tunnel. It is reasonable that the user should be notified when the connection is interrupted, and it should be up to the user to decide whether to reconnect.
