### ISSUE TITLE
有个问题想请教一下大佬，gost怎么在C#中直接调用？

### ISSUE THREAD

**Issue by ladycwd** [go-gost/gost#495]
有个问题想请教一下大佬，gost怎么在C#中直接调用？我现在只能作为内嵌资源然后释放到程序目录再带参数process.Start();
这样虽然是目前能够使用了，但是感觉不是最好的使用方式，能不能不释放直接由C#控制

**Comment by cnwhy** [comment]
是不是该去 .Net 社区问呢
