### ISSUE TITLE
ss不支持"none"

### ISSUE THREAD

**Issue by f4nff** [go-gost/gost#5]
`ssserver -k "" -m "none" -s "127.0.0.1:9000"`

https://github.com/shadowsocks/shadowsocks-rust

不支持此模式。

**Comment by ginuerzh** [comment]
none应该是不对数据做处理吧

**Comment by f4nff** [comment]
Stream Ciphers
plain or none (No encryption, only used for debugging or with plugins that ensure transport security)

对，不加密，

**Comment by ginuerzh** [comment]
不使用任何加密方法就是none
```
gost -L ss://:8338
```

**Comment by f4nff** [comment]
ok
