### ISSUE TITLE
远程socks5转发的用户密码怎么填写？

### ISSUE THREAD

**Issue by zwl1619** [go-gost/gost#501]
文档中快速开始那一节，“TCP本地端口转发”和“TCP远程端口转发”是这样写的：

> TCP本地端口转发(转发链)
> gost -L=tcp://:8080/192.168.1.1:80 -F socks5://192.168.1.2:1080  //将本地的TCP端口8080通过转发链映射到192.168.1.1的80端口。
> 
> TCP远程端口转发
> gost -L=rtcp://:2222/:22 -F socks5://192.168.1.2:1080  //在192.168.1.2上开启并监听TCP端口2222，并将192.168.1.2上的2222端口映射到本地TCP端口22，所有到192.168.1.2:2222的数据会被转发到本地端口22。

以上引用内容来源：https://gost.run/getting-started/quick-start/#tcp_1

请教三个问题：
1、socks5地址，上面写的是内网地址，可以是公网任意地址吗？
2、socks5地址，除了ip地址和端口，如果还有用户名密码，应该怎么写？
3、gost监听的本地端口数据，gost是代替原程序接管这个端口的数据，还是只是复制一份这个端口的数据而不影响原程序对数据的处理？举个例子，比如我安装了科学上网软件sing-box服务端，它在监听8080端口，它收到8080端口数据后，它自己有它的处理方式。现在，我加入了gost来转发8080端口的数据到另一个socks5代理，那么，gost是接管了sing-box对8080端口的监听，还是说两个程序都有拿到8080端口的数据分别各自处理？

**Comment by ginuerzh** [comment]
1, 2. 请看文档并尝试。
3. 端口转发是透传模式，不会对数据做修改。
