### ISSUE TITLE
Websocket Secure 如何配置使用 http3

### ISSUE THREAD

**Issue by wen-long** [go-gost/gost#505]
mws 和 mwss 应该可以配置成通过 http3 发起连接
阅读文档没有找到相关话题

**Comment by ginuerzh** [comment]
有相关的提案: [RFC9220](https://www.rfc-editor.org/rfc/rfc9220.html)，但仅此而已。
目前的趋势是会被[WebTransport](https://quic-go.net/docs/webtransport/)取代。
参考: https://gost.run/tutorials/protocols/http3/#webtransport
