### ISSUE TITLE
Deployment Issue: Config file is lost after Docker container restarts

### ISSUE THREAD

**Issue by amirsaam** [go-gost/gost#506]
Hi, thanks for your valuable project!

Unfortunately looks like config file is not persistent between container restarts in Docker environment. I tried to make a volume for GOST under it's `pathPrefix/config` but still after restart the file is lost.
Can you explain how can I make sure the file is persistent?

Thanks,

**Comment by cnwhy** [comment]
You can use this interface  [saveConfigRequest](https://api.gost.run/swagger-ui/?url=/docs/swagger.yaml#/Config/saveConfigRequest)

**Comment by amirsaam** [comment]
@cnwhy Hi, thanks for the reply but I don't think it's a good solution, GOST should save a file automatically in a path and try to read that in that path first and we should make it persistent in docker.

**Comment by ginuerzh** [comment]
You should start GOST with `-C` from config file:
```
gost -C /path/to/config/file
```
then save config to /path/to/config/file when it changes.

**Comment by cnwhy** [comment]
@amirsaam I understand what you mean, so [web-ui](https://github.com/go-gost/gost-ui) uses the "saveConfigRequest" interface to implement "auto save"

**Comment by amirsaam** [comment]
Thanks!
