### ISSUE TITLE
gost与标准协议的兼容性和互操作性

### ISSUE THREAD

**Issue by douniwan5788** [go-gost/gost#507]
gost似乎只考虑了两端都是gost实现的情况，在标准协议上定义了很多私有字段/方法，导致无法与其他使用标准协议的程序兼容。
如socks5 传输udp 使用 UDP-Over-TCP方法(0xF3)，而非UDP ASSOCIATE(0x03)，导致无法用标准socks5服务器转发
ssh 也用自定义的 gost-tunnel ，而非direct-tcpip 等channel 导致无法利用现有的openssh服务实现转发

1、请问有合适的配置参数可以让gost与其他标准协议的服务兼容吗？
2、gost后续是否会改进与标准协议的兼容性和互操作性？

**Comment by ginuerzh** [comment]
SOCKS5: #471

SSH有两种模式，使用标准协议的是[转发模式](https://gost.run/tutorials/protocols/ssh/#_2)
