### ISSUE TITLE
dns跟resolver有什么区别啊？

### ISSUE THREAD

**Issue by yinghua8wu** [go-gost/gost#51]
看了说明文档，对于dns跟resolver两个参数有点疑问
比如创建两个本地代理
gost -L :1080?dns=1.1.1.1,tls://1.1.1.1:853
gost -L :1090?resolver=1.1.1.1,tls://1.1.1.1:853
这两个代理是否都使用1.1.1.1,tls://1.1.1.1:853来解析域名？

**Comment by ginuerzh** [comment]
`dns`参数仅用于[DNS代理服务](https://gost.run/tutorials/dns/)，用于指定上游DNS服务。
`resolver`用于对请求的目标地址进行解析。https://gost.run/concepts/resolver/
