### ISSUE TITLE
Gost v3 HTTP代理在某些情况下出现ssl异常

### ISSUE THREAD

**Issue by BreathBlush** [go-gost/gost#515]
这个问题是我在使用Python写脚本时发现的，使用`aiohttp`库设置好gost建立的http代理服务器后发送http请求时，发现所有请求都会报错，我一度以为是`aiohttp`这个库的问题，后来测试了其他的http代理服务器，发现并无此问题，同时gost v2版本也无此问题，特此反馈，希望修复，十分喜欢gost v3，感谢作者的付出！

以下是测试代码，报错似乎是ssl方面有问题，但具体问题，无法得知
```python
import asyncio
import aiohttp

env = 'http://127.0.0.1:8080'

async def main():
    async with aiohttp.ClientSession() as cs:
        async with cs.get("https://www.python.org", proxy=env) as r:
            res = await r.text()
            print(res[:100])

asyncio.run(main())
```

![1_error](https://github.com/go-gost/gost/assets/10967857/fd7280ea-574e-4df6-a747-63e1c2e65c10)

gost v3的日志中，一切正常，没有任何info级别以上的日志

![1_output](https://github.com/go-gost/gost/assets/10967857/157bbdf5-6597-4918-88b8-19d70bc3d7f2)

然后使用gost v2进行测试，一模一样的python代码，请求是成功的

![2_ok](https://github.com/go-gost/gost/assets/10967857/ca7e8652-e1fc-4a61-82ad-a61bdcf77b80)

gost v2的日志中，同样一切正常

![2_output](https://github.com/go-gost/gost/assets/10967857/f43cf3bc-7001-4cd9-a39b-5f644c43bab8)

我最初在aiohttp的项目那边开了一个issue，认为是aiohttp库的问题，后来经过使用其他http代理程序测试，发现这应该是gost v3的问题，这个问题可能不太好排查，如果作者有意，希望能尝试解决，否则我得同时使用v3 和 v2，这有点遗憾！

最后感谢作者的gost，这一堪称伟大的作品

**Comment by ginuerzh** [comment]
应该是返回了`Content-Length: 0` HTTP头导致的，服务端返回了这个头而客户端又没有忽略。[RFC9110](https://www.rfc-editor.org/rfc/rfc9110#section-9.3.6-12)中有严格规定：
```
A server MUST NOT send any Transfer-Encoding or Content-Length header fields in a 2xx (Successful) response to CONNECT. 
A client MUST ignore any Content-Length or Transfer-Encoding header fields received in a successful response to CONNECT.
```

今天的nightly版本已修复。
