### ISSUE TITLE
增加端口复用配置项

### ISSUE THREAD

**Issue by chenyi0909** [go-gost/gost#517]
有些使用场景下只开放一个端口使用给使用，该端口用于收发数据，gost监听后就无法在使用这个端口了，建议增加一个端口复用的配置项或命令行参数

**Comment by ginuerzh** [comment]
你需要的是反向代理。

**Comment by chenyi0909** [comment]
尊敬的作者大佬：
&nbsp; &nbsp; &nbsp; &nbsp; emmm我应该不是这个意思？我想请教一个问题，如果我想给sock5的监听端口设置端口复用，我应该在我本地拉下来的gost库修改那个文件的接口？我本意是想修改service/parse..go文件，我发现日志是从这个文件的ln.Init()报出的地址正在被使用，但是捋了下代码发现从这里无从下手。特来咨询一下大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月26日(周三) 晚上9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [go-gost/gost] 增加端口复用配置项 (Issue #517)




 
你需要的是反向代理。

**Comment by ginuerzh** [comment]
auto handler本身已经实现了端口复用，可以参考https://github.com/go-gost/x/blob/master/handler/auto/handler.go
