### ISSUE TITLE
GOST V3 SK5於安卓物理機(SK5 不設帳密驗證可用,設用戶認證則無法使用)

### ISSUE THREAD

**Issue by starry1314** [go-gost/gost#519]
PC端           = 可用
安卓模擬器 =可用
安卓物理機=不可用 (只有不設定用戶認證才可使用)
IOS物理機=可用

出错日志:
"handler":"socks5","kind":"service","level":"error","listener":"tcp","msg":"EOF","service":"service-0","time":"2024-06-29T08:33:15.373-04:00"}

**Comment by ginuerzh** [comment]
客户端是什么？

**Comment by starry1314** [comment]
V2rayng

> 客户端是什么？
以下都嘗試過無法使用
v2rayng
Kitsunebi
BifrostV_0.6.9_apkcombo.com
v2rayNG_1.8.16_x86_64

**Comment by ginuerzh** [comment]
可能与https://github.com/v2fly/v2ray-core/issues/1048 有关。

**Comment by starry1314** [comment]
看了下 ~好像得是得指定客戶端,有辦法修復服務端來適配嗎?
只要安桌手機端任一種SK5代理軟件都不可用

**Comment by ginuerzh** [comment]
最新版本中已做兼容，可以试试
https://github.com/go-gost/gost/releases/tag/v3.0.0-nightly.20240704

**Comment by starry1314** [comment]
> 最新版本中已做兼容，可以试试 https://github.com/go-gost/gost/releases/tag/v3.0.0-nightly.20240704
感謝,測試後狀況如下

測試命令行方式安卓手機已可連線,配置文件的話失敗
services:
- name: service-1
  addr: "10.30.3.1:1080"
  handler:
    type: socks5
    auther: auther-1
    metadata: 
      udp: true
  listener:
    type: tcp
log:
  output: none
  level: debug
  format: json
authers:
- name: auther-1
  reload: 10s
  file:
    path: /etc/gost.auth

**Comment by ginuerzh** [comment]
报什么错？请检查gost.auth文件格式是否正确。

**Comment by starry1314** [comment]
> 报什么错？请检查gost.auth文件格式是否正确。

文件格式是正確的,因為PC或是模擬器都可用

LOG:
`Jul  5 11:00:01 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: sysstat-collect.service: Succeeded.
Jul  5 11:00:01 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Finished system activity accounting tool.
Jul  5 11:10:10 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Starting system activity accounting tool...
Jul  5 11:10:10 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: sysstat-collect.service: Succeeded.
Jul  5 11:10:10 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Finished system activity accounting tool.
Jul  5 11:14:31 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Started Session 3827 of user root.
Jul  5 11:14:31 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: session-3827.scope: Succeeded.
Jul  5 11:15:22 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Started Session 3829 of user root.
Jul  5 11:15:22 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: session-3829.scope: Succeeded.
Jul  5 11:15:34 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Started Session 3830 of user root.
Jul  5 11:15:34 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: session-3830.scope: Succeeded.
Jul  5 11:15:44 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Started Session 3831 of user root.
Jul  5 11:15:44 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: session-3831.scope: Succeeded.
Jul  5 11:15:48 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Started Session 3832 of user root.
Jul  5 11:15:55 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: session-3832.scope: Succeeded.
Jul  5 11:20:10 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Starting system activity accounting tool...
Jul  5 11:20:10 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: sysstat-collect.service: Succeeded.
Jul  5 11:20:10 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Finished system activity accounting tool.
Jul  5 11:30:10 iZj6c9pyh23ovs8h4avq3zZ systemd[1]: Starting system activity accounting tool...`

**Comment by starry1314** [comment]
> 报什么错？请检查gost.auth文件格式是否正确。

Log

Jul  5 03:08:49 debian gost[2542]: {"auther":"auther-0","caller":"auth/auth.go:148","kind":"auther","level":"debug","msg":"load items 13","time":"2024-07-05T03:08:49.065-04:00"}

**Comment by starry1314** [comment]
請問這個命令行方式已經修復可用於安卓手機了,配置文件的方式需要怎麼調整或是還需要修復呢?

**Comment by starry1314** [comment]
> 最新版本中已做兼容，可以试试 https://github.com/go-gost/gost/releases/tag/v3.0.0-nightly.20240704

請問這個兼容問題有辦法解決嗎? 看版本已拿掉了

**Comment by starry1314** [comment]
目前測試已找出原因,
GOSK5 沒加海外中轉IOS 可以,安卓不行
GOSK5 加上海外中轉IOS 可以,安卓可以
非中國地區可以直連,在中國地區得加上海外中轉才能使用
可能協議頭封裝是被封的?

> 报什么错？请检查gost.auth文件格式是否正确。
