### ISSUE TITLE
报错:"too many colons in address"

### ISSUE THREAD

**Issue by Goooooooooood** [go-gost/gost#532]
如题。升级至v3.0.0-nightly.20240708后，服务端运行出现"too many colons in address"报错。

不管运行ss-server还是https代理服务器，都会这样报错。

v3.0.0-nightly.20240704使用一切正常。

以下是在之前版本可以正常执行的命令行：
gost -L ss://加密协议:密码@:2048 -F 省略的加密协议和密码

请问运行新版本软件时，需要改变命令行吗？不知和更新日志中提到的“0d7a6f8 add port range support for service”是否有关？

感谢您看到这里，期待得到指点。

**Comment by TD-fupengfei** [comment]
我也遇到了，换格式了吗

**Comment by ginuerzh** [comment]
今天的版本中修复
