### ISSUE TITLE
ssu会导致udp端口耗尽

### ISSUE THREAD

**Issue by leeaash** [go-gost/gost#540]
服务端配置如下
-L=ss://rc4-md5:password@:12345 -L=ssu://rc4-md5:password@:12345

client端为clash

问题现象：

gost会耗尽服务端udp端口，并导致主机udp查询无法使用，另一个可能影响，是导致主机cpu利用率高。

**Comment by ginuerzh** [comment]
最新的版本中已经修复。

**Comment by leeaash** [comment]
试用了一下，貌似有改善，开了一天目前端口占用7400+，感觉还有增长趋势。和shadowsocks-libev实现比较了一下，shadowsocks-libev占用udp端口要少两个数量级啊

**Comment by ginuerzh** [comment]
可能是请求超时端口没有释放，可以试试今天的版本。

**Comment by leeaash** [comment]
观察了下，新版本貌似修复了
