### ISSUE TITLE
ICMP+TUN问题

### ISSUE THREAD

**Issue by dreamage** [go-gost/gost#55]
A内网机器能访问B公网机器（仅限ICMP协议可以出去），想在A、B之间搭TUN，以便从互联网可以访问A网络后面的应用

./gost3 -V
gost 3.0.0-beta.2 (go1.18.1 linux/amd64)

**测试一**
B
./gost3 -L icmp://:0
./gost3 -L tun://:8421?net=192.168.123.1/24

A
./gost3 -L udp://:18421/127.0.0.1:8421 -F icmp://119.254.xxx.xxx:0
./gost3 -L tun://:28421/127.0.0.1:18421?net=192.168.123.2/24

TUN接口无法访问通，A进程1报错
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:02:24+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:02:25+08:00"}
{"handler":"udp","kind":"handler","level":"info","listener":"udp","local":"[::]:18421","msg":"127.0.0.1:46432 <> [::]:18421","remote":"127.0.0.1:46432","service":"service-0","time":"2022-06-12T21:02:27+08:00"}
{"dst":"127.0.0.1:8421/udp","handler":"udp","kind":"handler","level":"info","listener":"udp","local":"[::]:18421","msg":"127.0.0.1:46432 >> 127.0.0.1:8421","remote":"127.0.0.1:46432","service":"service-0","time":"2022-06-12T21:02:27+08:00"}
{"address":"127.0.0.1:8421","chain":"chain-0","connector":"http","dialer":"icmp","hop":"hop-0","kind":"connector","level":"info","local":"0.0.0.0","msg":"connect 127.0.0.1:8421/udp","network":"udp","node":"node-0","remote":"119.254.xxx.xxx:63349","time":"2022-06-12T21:02:27+08:00"}
{"handler":"udp","kind":"handler","level":"error","listener":"udp","msg":"route(retry=0) 403 Forbidden","service":"service-0","time":"2022-06-12T21:02:27+08:00"}
{"dst":"127.0.0.1:8421/udp","handler":"udp","kind":"handler","level":"error","listener":"udp","local":"[::]:18421","msg":"403 Forbidden","remote":"127.0.0.1:46432","service":"service-0","time":"2022-06-12T21:02:27+08:00"}
{"dst":"127.0.0.1:8421/udp","duration":4876772,"handler":"udp","kind":"handler","level":"info","listener":"udp","local":"[::]:18421","msg":"127.0.0.1:46432 >< [::]:18421","remote":"127.0.0.1:46432","service":"service-0","time":"2022-06-12T21:02:27+08:00"}
{"handler":"udp","kind":"service","level":"error","listener":"udp","msg":"403 Forbidden","service":"service-0","time":"2022-06-12T21:02:27+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:02:27+08:00"}

**测试二**
B
./gost3 -L relay+icmp://:0
./gost3 -L tun://:8421?net=192.168.123.1/24

A
./gost3 -L udp://:18421/127.0.0.1:8421 -F relay+icmp://119.254.xxx.xxx:0
./gost3 -L tun://:28421/127.0.0.1:18421?net=192.168.123.2/24

很有规律的每隔10个包，TUN接口可以访问通一次
PING 192.168.123.1 (192.168.123.1) 56(84) bytes of data.
64 bytes from 192.168.123.1: icmp_seq=1 ttl=64 time=3.42 ms
64 bytes from 192.168.123.1: icmp_seq=11 ttl=64 time=7.71 ms
64 bytes from 192.168.123.1: icmp_seq=21 ttl=64 time=5.13 ms
64 bytes from 192.168.123.1: icmp_seq=31 ttl=64 time=4.86 ms

A进程1日志
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:43+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:46+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:46+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:48+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:49+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:51+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:52+08:00"}
{"handler":"udp","kind":"handler","level":"info","listener":"udp","local":"[::]:18421","msg":"127.0.0.1:38510 <> [::]:18421","remote":"127.0.0.1:38510","service":"service-0","time":"2022-06-12T21:03:52+08:00"}
{"dst":"127.0.0.1:8421/udp","handler":"udp","kind":"handler","level":"info","listener":"udp","local":"[::]:18421","msg":"127.0.0.1:38510 >> 127.0.0.1:8421","remote":"127.0.0.1:38510","service":"service-0","time":"2022-06-12T21:03:52+08:00"}
{"address":"127.0.0.1:8421","chain":"chain-0","connector":"relay","dialer":"icmp","hop":"hop-0","kind":"connector","level":"info","local":"0.0.0.0","msg":"connect 127.0.0.1:8421/udp","network":"udp","node":"node-0","remote":"119.254.xxx.xxx:16334","time":"2022-06-12T21:03:52+08:00"}
{"dst":"127.0.0.1:8421/udp","handler":"udp","kind":"handler","level":"info","listener":"udp","local":"[::]:18421","msg":"127.0.0.1:38510 <-> 127.0.0.1:8421","remote":"127.0.0.1:38510","service":"service-0","time":"2022-06-12T21:03:52+08:00"}
{"dst":"127.0.0.1:8421/udp","duration":7371765,"handler":"udp","kind":"handler","level":"info","listener":"udp","local":"[::]:18421","msg":"127.0.0.1:38510 >-< 127.0.0.1:8421","remote":"127.0.0.1:38510","service":"service-0","time":"2022-06-12T21:03:52+08:00"}
{"dst":"127.0.0.1:8421/udp","duration":7606071,"handler":"udp","kind":"handler","level":"info","listener":"udp","local":"[::]:18421","msg":"127.0.0.1:38510 >< [::]:18421","remote":"127.0.0.1:38510","service":"service-0","time":"2022-06-12T21:03:52+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:53+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:53+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:54+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:55+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:55+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:57+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:58+08:00"}
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-12T21:03:58+08:00"}

**测试三**
B
./gost3 -L relay+icmp://:0
./gost3 -L tun://:8421?net=192.168.123.1/24

A
./gost3 -L tun://:28421/127.0.0.1:8421?net=192.168.123.2/24 -F relay+icmp://119.254.xxx.xxx:0

A报错
{"address":"","chain":"chain-0","connector":"relay","dialer":"icmp","hop":"hop-0","kind":"connector","level":"info","local":"0.0.0.0","msg":"connect /udp","network":"udp","node":"node-0","remote":"119.254.xxx.xxx:14407","time":"2022-06-12T21:09:53+08:00"}
{"handler":"tun","kind":"handler","level":"error","listener":"tun","msg":"route(retry=0) bind on /udp failed","service":"service-0","time":"2022-06-12T21:09:53+08:00"}
{"dst":"127.0.0.1:8421/udp","handler":"tun","kind":"handler","level":"error","listener":"tun","local":":28421","msg":"bind on /udp failed","remote":"192.168.123.2","service":"service-0","time":"2022-06-12T21:09:53+08:00"}
{"address":"","chain":"chain-0","connector":"relay","dialer":"icmp","hop":"hop-0","kind":"connector","level":"info","local":"0.0.0.0","msg":"connect /udp","network":"udp","node":"node-0","remote":"119.254.xxx.xxx:14407","time":"2022-06-12T21:09:57+08:00"}
{"handler":"tun","kind":"handler","level":"error","listener":"tun","msg":"route(retry=0) bind on /udp failed","service":"service-0","time":"2022-06-12T21:09:57+08:00"}
{"dst":"127.0.0.1:8421/udp","handler":"tun","kind":"handler","level":"error","listener":"tun","local":":28421","msg":"bind on /udp failed","remote":"192.168.123.2","service":"service-0","time":"2022-06-12T21:09:57+08:00"}
{"address":"","chain":"chain-0","connector":"relay","dialer":"icmp","hop":"hop-0","kind":"connector","level":"info","local":"0.0.0.0","msg":"connect /udp","network":"udp","node":"node-0","remote":"119.254.xxx.xxx:14407","time":"2022-06-12T21:10:03+08:00"}
{"handler":"tun","kind":"handler","level":"error","listener":"tun","msg":"route(retry=0) bind on /udp failed","service":"service-0","time":"2022-06-12T21:10:03+08:00"}
{"dst":"127.0.0.1:8421/udp","handler":"tun","kind":"handler","level":"error","listener":"tun","local":":28421","msg":"bind on /udp failed","remote":"192.168.123.2","service":"service-0","time":"2022-06-12T21:10:03+08:00"}

以上所有测试将127.0.0.1换为各自的内网IP也是同样问题

**测试四**
网络放开A到B的tcp访问，按照 https://latest.gost.run/tutorials/tuntap/#tcptuntap 测试`转发链 和 端口转发`均失败

转发链
B
./gost3 -L tun://:8421?net=192.168.123.1/24 -L relay://:61111

A
./gost3 -L tun://:0/:8421?net=192.168.123.2/24 -F relay://119.254.xxx.xxx:61111

A报错
{"address":"","chain":"chain-0","connector":"relay","dialer":"tcp","hop":"hop-0","kind":"connector","level":"info","local":"172.16.4.201:41518","msg":"connect /udp","network":"udp","node":"node-0","remote":"119.254.xxx.xxx:61111","time":"2022-06-12T21:15:24+08:00"}
{"handler":"tun","kind":"handler","level":"error","listener":"tun","msg":"route(retry=0) bind on /udp failed","service":"service-0","time":"2022-06-12T21:15:24+08:00"}
{"dst":":8421/udp","handler":"tun","kind":"handler","level":"error","listener":"tun","local":":0","msg":"bind on /udp failed","remote":"192.168.123.2","service":"service-0","time":"2022-06-12T21:15:24+08:00"}

端口转发
B
./gost3 -L tun://:8421?net=192.168.123.1/24 -L relay://:61111

A
./gost3 -L tun://:8421/:8420?net=192.168.123.2/24 -L udp://:8420/:8421 -F relay://119.254.xxx.xxx:61111

A报错
{"address":"","chain":"chain-0","connector":"relay","dialer":"tcp","hop":"hop-0","kind":"connector","level":"info","local":"172.16.4.201:41554","msg":"connect /udp","network":"udp","node":"node-0","remote":"119.254.xxx.xxx:61111","time":"2022-06-12T21:17:28+08:00"}
{"handler":"tun","kind":"handler","level":"error","listener":"tun","msg":"route(retry=0) bind on /udp failed","service":"service-0","time":"2022-06-12T21:17:28+08:00"}
{"dst":":8420/udp","handler":"tun","kind":"handler","level":"error","listener":"tun","local":":8421","msg":"bind on /udp failed","remote":"192.168.123.2","service":"service-0","time":"2022-06-12T21:17:28+08:00"}

请问有解决办法吗？

**Comment by ginuerzh** [comment]
首先要注意几点：
1. udp转发默认是不保活的，需要通过`keepAlive`参数开启，并通过`ttl`参数控制。
`udp://:18421/127.0.0.1:8421?keepAlive=true&ttl=60s`
具体说明详见：https://gost.run/tutorials/port-forwarding/#udp

2. http和relay服务默认没有开启UDP转发，需要手动开启。
对于HTTP使用的是UDP转发: `gost -L icmp://:0?udp=true`
对于relay协议使用的是BIND方法: `gost -L relay+icmp://:0?bind=true`


3. ICMP通道使用QUIC来封装数据，QUIC需要心跳来维持连接。
`icmp://1.2.3.4:0?keepAlive=true`

TUN over ICMP有以下几种实现方式(建议使用1或2)：
1. HTTP+ICMP
B: `gost -L icmp://:0?udp=true -L tun://:8421?net=192.168.123.1/24`
A: `gost -L tun://:8421/:8421?net=192.168.123.2/24 -F icmp://1.2.3.4:0?keepAlive=true`

2. Relay + ICMP
B: `gost -L relay+icmp://:0?bind=true -L tun://:8421?net=192.168.123.1/24`
A: `gost -L tun://:8421/:8421?net=192.168.123.2/24 -F relay+icmp://1.2.3.4:0?keepAlive=true`

3. UDP转发
B: `gost -L relay+icmp://:0?bind=true -L tun://:8421?net=192.168.123.1/24`
A: `gost -L udp://:18421/:8421?keepAlive=true&ttl=60s -F relay+icmp://1.2.3.4:0?keepAlive=true`和`gost -L tun://:8421/:18421?net=192.168.123.2/24`
