### ISSUE TITLE
socks5代理转发认证失效

### ISSUE THREAD

**Issue by naicha520** [go-gost/gost#551]
我购买了一条认证socks5，我想在本机使用gost中转这条socks5，并使用自定义账号密码认证

gost.exe -L socks5://a123456789:a123456789@:20000-F socks5://qivV9tfm:zmwK312G@46.149.135.120:64083

当我使用 socks5://a123456789:a123456789@127.0.0.1:20000  提示认证失败

![image](https://github.com/user-attachments/assets/b8787d0a-2a23-4309-91a2-88a35265fd34)

密码没错

![image](https://github.com/user-attachments/assets/10be72ef-54a3-42a2-b294-2e1eda936bca)

请问为什么转发之后就异常了？

**Comment by ginuerzh** [comment]
测试正常，请检查客户端认证信息是否一致。

**Comment by naicha520** [comment]
感谢
