### ISSUE TITLE
gost流量限速不够精准

### ISSUE THREAD

**Issue by intmain0** [go-gost/gost#555]
在一个连接刚开始的时候（第1秒），连接速度会冲得很高然后恢复正常。原因是限流器Token桶的容量设的比较大了。https://github.com/go-gost/x/blob/bc0d6953bcb372b6394f8ed648552dfa824d66bc/limiter/traffic/limiter.go#L19
第二个参数修改成r/20+1就可以解决了

**Comment by ginuerzh** [comment]
并不是桶的大小问题，而是令牌桶初始状态下是满的，因此在第一秒会有一个burst。
