### ISSUE TITLE
请问能根据不同的客户端ip来进行分流吗

### ISSUE THREAD

**Issue by skier789** [go-gost/gost#556]
根据不同的客户端ip 转发到不同的代理

**Comment by pi2376327** [comment]
> 根据不同的客户端ip 转发到不同的代理

开启多个监听转发服务，iptables匹配客户端ip的流量到不同的监听端口呗

**Comment by ginuerzh** [comment]
也可以通过Hop插件来实现，GOST会把客户端地址传给插件。
https://gost.run/concepts/hop/#_9

**Comment by nansangya** [comment]
使用插件会不会对性能造成很大影响，如果请求过多的话
