### ISSUE TITLE
[BUG] gost3的udp转发相比gost2存在兼容性问题

### ISSUE THREAD

**Issue by aploium** [go-gost/gost#56]
发现gost3的udp转发无法用于kcp、n2n等，而gost2可以，下面是复现命令(单机)

1.udp转发到kcp，server
```
gost3 -L=udp://:2333/:2334 -L=kcp://:2334
```

2.一个走kcp的普通转发，client
```
gost3 -L=auto://:2666 -F=kcp://127.0.0.1:2333
```

3. 执行curl
```
curl -v example.com --proxy 127.0.0.1:2666
```
反复多执行几次curl，会发现命令3卡死不动，命令1的地方会出现连续多条报错
```
{"handler":"udp","kind":"listener","level":"warning","listener":"udp","msg":"data discarded: use of closed network connection","service":"service-0","time":"2022-06-20T16:15:24+08:00"}
```

以上请求链路为   curl--> auto:2666 -> udp:2333 -> kcp:2334

-------------------------------------
gost2的情况
以上仅将命令1的`gost3`替换为`gost2` 其他命令不变
```
gost2 -L=udp://:2333/:2334 -L=kcp://:2334
```
(所有命令都得关掉重新运行一次，不然好像会有残留)

发现命令3的curl可以成功完成请求，反复执行多次curl也不会有异常

版本:
gost3: v3.0.0-beta.2
gost2: gost 2.11.2
系统: ubuntu

**Comment by ginuerzh** [comment]
GOST v3中UDP转发的行为有所变化，默认情况下，只会进行1次数据交互。可以通过`keepAlive`和`ttl`参数来控制。
详见：https://gost.run/tutorials/port-forwarding/#udp
