### ISSUE TITLE
关于由客户端动态注册host做反向代理隧道如何实现？

### ISSUE THREAD

**Issue by hero821** [go-gost/gost#568]
服务端：启动一个固定端口，例如 80
客户端A：注册自己的 8080 到 a.example.com
客户端B：注册自己的 8080 到 b.example.com

如上场景，还可以理解为，有个调度模块做扩缩容，客户端数量是变化的，每次变化都要动态修改server配置（即使通过api）有些麻烦。

1、是否可以使用[直接路由](https://gost.run/tutorials/reverse-proxy-tunnel/#_5)实现？
_看文档，我理解为直接路由不能使用公共入口点，只能在访问端做端口映射？这样理解是否正确？_
2、我看GOST.PLUS有类似功能，看似是依赖gost-plugins扩展做的，请问作者，这个gost-plugins的代码是否公开了。

**Comment by ginuerzh** [comment]
[gost-plugins](https://github.com/ginuerzh/gost-plugins)已开源。
