### ISSUE TITLE
当使用bypass时如何配置才能实现拦截后拦截重定向

### ISSUE THREAD

**Issue by rico0808** [go-gost/gost#574]
在使用分流器分流时，遇到非法流量想要将非法的请求重定向到到某个网址上，这种功能是否支持呢？

想实现的大概类似未备案域名解析到国内云服务上，访问域名会被重定向到域名未备案提示页面。

**Comment by ginuerzh** [comment]
你可以增加一个节点，通过bypass将需要重定向的流量分流到此节点上，由节点来处理。

**Comment by rico0808** [comment]
再次请教下，对于非法请求没有进入到指定服务里。也就是配置里的 127.0.0.1:7001。
127.0.0.1:7001 这个服务是一个web服务，用于接收用户的非法请求并进行重定向。

当浏览器使用代理 :8080 端口时，访问非法域名也就是 *.taobai.com 会被直接阻断，也没有请求进入到 127.0.0.1:7001这个服务里，访问正常的域名浏览器报错 “此站点的连接不安全”

我使用的配置
`services:
  - name: service-0
    addr: ":8080"
    handler:
      type: http
      chain: chain-0
    listener:
      type: tcp

chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: :8002
            connector:
              type: http
            dialer:
              type: tcp

          - name: node-1
            addr: 127.0.0.1:7001
            bypass: bypass-0
            connector:
              type: tcp
            dialer:
              type: tcp

bypasses:
  - name: bypass-0
    matchers:
      - "*.taobao.com"
`
