### ISSUE TITLE
V3 bypass CIDR规则不支持端口匹配 可以怎麼做?

### ISSUE THREAD

**Issue by starry1314** [go-gost/gost#581]
> 大部分情况下bypass可以满足。

請問V3 CIDR规则不支持端口匹配,可以怎麼解決連入的代理出去時禁止前往所有IP的指定端口
例如代理後禁止連線  *:7500

**Comment by ginuerzh** [comment]
在service上使用bypass即可
```
gost -L :8080?bypass=*:7500
```

**Comment by starry1314** [comment]
> 在service上使用bypass即可
> 
> ```
> gost -L :8080?bypass=*:7500
> ```
使用後沒有阻攔成功
![图片](https://github.com/user-attachments/assets/dc4fdb92-82d7-4ea9-9198-0cdc3413dc7f)

**Comment by ginuerzh** [comment]
已修复。
