### ISSUE TITLE
udp forward + icmp 

### ISSUE THREAD

**Issue by steom** [go-gost/gost#59]
server  -L relay+icmp://:0

client -L=udp://10.0.0.2:5189/192.168.0.3:5189 -F relay+icmp://192.168.0.2:12345?keepAlive=1

udp forward + icmp  cannot work reliable, famous udp based vpn fail go through

PS: when will you support wintun for tun adapter?

**Comment by ginuerzh** [comment]
You should enable keepAlive for udp port forward:
```
gost -L='udp://10.0.0.2:5189/192.168.0.3:5189?keepAlive=true&ttl=60s' -F relay+icmp://192.168.0.2:12345?keepAlive=1
```
See: https://gost.run/en/tutorials/port-forwarding/#udp
