### ISSUE TITLE
請問如果有多個服務各自有不同的BYPASS文件,如何指定目錄

### ISSUE THREAD

**Issue by starry1314** [go-gost/gost#593]
版本:[v3.0.0-nightly.20241011](https://github.com/go-gost/gost/releases/tag/v3.0.0-nightly.20241011)
系統:DEBIAN 11
以下方式BYPASS分流失效

/usr/local/bin/gost -L socks5://XX:XX@:35113?bypass=file:///opt/service_manager/service_35113/bypass.txt
/usr/local/bin/gost -L socks5://XX:XX@:35114?bypass=file:///opt/service_manager/service_35114/bypass.txt

/usr/local/bin/gost -L socks5://XX:XX@:35113?bypass=bypass.txt
/usr/local/bin/gost -L socks5://XX:XX@:35114?bypass=bypass.txt

**Comment by ginuerzh** [comment]
用法有误
https://gost.run/concepts/bypass/
