### ISSUE TITLE
EOF after update to latest version

### ISSUE THREAD

**Issue by vahidyeganeh1373** [go-gost/gost#594]
in version v3.0.0-rc10 it's work
today i update to latest version and get EOF error

The example I use

server1 :
gost -L=tcp://:8081 -F forward+tcp://[11.22.33.44]:443 

server2 :
gost -L=tcp://:443/:8081

Do I have to make any changes in the new update?
I wish you would tell us how to do it in a tutorial

**Comment by ginuerzh** [comment]
Try the latest nightly version.
