### ISSUE TITLE
均匀负载没法用吗?

### ISSUE THREAD

**Issue by viponedream** [go-gost/gost#60]
gost -L tcp://:12510 -F relay+tls://ip1:13510?ip=ip2:13510,ip3:13510&strategy=round&max_fails=1&fail_timeout=3s

我用了3个IP,  结果它只连第一个, 如果第一个IP关了, 不会自动连后面的那些IP

在v2版本, 是可以用的

**Comment by ginuerzh** [comment]
v3版本已经不再使用`ip`参数，改为逗号分割的地址列表：
```
gost -L tcp://:12510 -F "relay+tls://ip1:13510,ip2:13510,ip3:13510?strategy=round&max_fails=1&fail_timeout=3s"
```
