### ISSUE TITLE
服务配置中能同时指定authers和admission是或的关系么

### ISSUE THREAD

**Issue by abcxi** [go-gost/gost#602]
服务配置中能同时指定authers和admission是“或”的关系么
用户名密码和 白名单ip只要一个匹配就可以有这样的配置么

**Comment by abcxi** [comment]
或者修改代码直接改成或可行不

**Comment by ginuerzh** [comment]
auther和admission是独立的，必须两个同时通过才能进入下一步。
如果需要自定义逻辑，可以通过auther插件实现：https://gost.run/concepts/auth/#_12

**Comment by abcxi** [comment]
ok
