### ISSUE TITLE
http协议下 日志无法记录http相关链接的日志

### ISSUE THREAD

**Issue by abcxi** [go-gost/gost#603]
不知道是不是我测试问题  
http:// 或者 301 跳转的都没有记录   只有在http协议的时候这样  访问https://链接没有问题   socks5也没有问题

{"handler":"http","kind":"handler","level":"info","listener":"tcp","local":"192.168.0.20:8888","msg":"192.168.0.20:53526 <> 192.168.0.20:8888","remote":"192.168.0.20:53526","service":"auto.8888","sid":"cshj2k2cnjml41n2sc6g","time":"2024-10-31T15:27:12.150+08:00"}
{"duration":320791583,"handler":"http","kind":"handler","level":"info","listener":"tcp","local":"192.168.0.20:8888","msg":"192.168.0.20:53526 >< 192.168.0.20:8888","remote":"192.168.0.20:53526","service":"auto.8888","sid":"cshj2k2cnjml41n2sc6g","time":"2024-10-31T15:27:12.471+08:00"}
{"handler":"http","kind":"handler","level":"info","listener":"tcp","local":"192.168.0.20:8888","msg":"192.168.0.20:57484 <> 192.168.0.20:8888","remote":"192.168.0.20:57484","service":"auto.8888","sid":"cshj9dicnjml41n2sc70","time":"2024-10-31T15:41:42.367+08:00"}
{"duration":313937292,"handler":"http","kind":"handler","level":"info","listener":"tcp","local":"192.168.0.20:8888","msg":"192.168.0.20:57484 >< 192.168.0.20:8888","remote":"192.168.0.20:57484","service":"auto.8888","sid":"cshj9dicnjml41n2sc70","time":"2024-10-31T15:41:42.680+08:00"}

**Comment by ginuerzh** [comment]
用的哪个版本？

**Comment by abcxi** [comment]
嗯嗯 版本比较老了  更新了下 好了
