### ISSUE TITLE
反向代理好像不支持重写和添加响应头

### ISSUE THREAD

**Issue by SianHH** [go-gost/gost#604]
在文档只看见了重写响应体的功能，请问能否支持重写和添加响应头

**Comment by SianHH** [comment]
麻烦问一下，这个重写或添加响应头的功能，近期有开发计划吗？

**Comment by ginuerzh** [comment]
已添加
https://gost.run/tutorials/reverse-proxy/#_5

**Comment by SianHH** [comment]
能否支持content-type匹配，或者url正则匹配。
由于nginx没有方便的api修改配置，想使用gost代替nginx做反向代理，第三方服务动态控制。

**Comment by ginuerzh** [comment]
已经集成了Traefik的路由规则，其中包含Header和URL Path正则匹配功能。
https://gost.run/tutorials/reverse-proxy/#_8

**Comment by SianHH** [comment]
感谢
