### ISSUE TITLE
限速限流插件做修改了么30秒经过一次插件？

### ISSUE THREAD

**Issue by abcxi** [go-gost/gost#606]
我直接下载的最新的二进制文件测试的
limiters:
  - name: limiter-8888
    plugin:
      type: grpc
      addr: 127.0.0.1:38002 限速限流插件么30秒经过一次插件
测试之前的老版本 这里是实时的嗖嗖嗖

**Comment by abcxi** [comment]
2024/11/08 16:19:49 开始 ----- 0
2024/11/08 16:19:49 in=1024000, out=1024000
2024/11/08 16:19:49 开始 ----- 0
2024/11/08 16:19:49 in=1024000, out=1024000
2024/11/08 16:20:19 开始 ----- 0
2024/11/08 16:20:19 in=1024000, out=1024000
2024/11/08 16:20:19 开始 ----- 0
2024/11/08 16:20:19 in=1024000, out=1024000

**Comment by ginuerzh** [comment]
完整的配置？

**Comment by abcxi** [comment]
> 完整的配置？

services:
- name: auto.8888
  addr: "192.168.0.20:8888"
  interface: 192.168.0.20
  handler:
    type: auto
    auther: auther-0
    limiter: limiter-0
    metadata:
      udp: true
      udpBufferSize: 4096  # 根据需要调整缓冲
      observePeriod: 5s
  listener:
    type: tcp

authers:
  - name: auther-8888
    plugin:
      type: grpc
      addr: 127.0.0.1:38001
      token: 54

limiters:
  - name: limiter-8888
    plugin:
      type: grpc
      addr: 127.0.0.1:38002
      token: 54

**Comment by ginuerzh** [comment]
现在是每30秒请求一次。

**Comment by abcxi** [comment]
嗯嗯  好的
