### ISSUE TITLE
在新加端口时，最近老是创建失败，然后我查询端口占用发现下面的进程，并且有的进程端口也并不是我设置的（都是读取的json配置）

### ISSUE THREAD

**Issue by guchenghua** [go-gost/gost#618]
gost    1070 root 2888u  IPv4 123143      0t0  TCP cid40638-w150441-hkg3-vm01:32934->115.164.114.18:59059 (ESTABLISHED)

**Comment by ginuerzh** [comment]
出站的连接也是会占用本地端口的。

**Comment by guchenghua** [comment]
大佬如何解决这个占用问题，目前我创建端口都是+1，时常遇到创建不了

**Comment by ginuerzh** [comment]
可以根据需要来划分不同的端口范围，可以参考https://www.cnblogs.com/Wangzx000/p/18259030

**Comment by guchenghua** [comment]
解决了，谢谢大佬 就是出口的问题
