### ISSUE TITLE
在国外的VPS上转发HTTP 请求不通 

### ISSUE THREAD

**Issue by dnslin** [go-gost/gost#629]
/usr/local/bin/gost -L http://abc:xxx@:10288

{"client":"x.x.x.x","duration":7737409,"handler":"http","inputBytes":114,"kind":"handler","level":"info","listener":"tcp","local":"10.1.1.4:10288","msg":"x.x.x.x:45378 >< 10.1.1.4:10288","outputBytes":0,"remote":"x.x.x.x:45378","service":"service-0","sid":"ctkiuuvcoo7vbivkl1sg","time":"2024-12-23T09:38:03.283Z"}
{"handler":"http","kind":"service","level":"error","listener":"tcp","msg":"write tcp 10.1.1.4:10288->x.x.x.x:45378: write: connection reset by peer","service":"service-0","sid":"ctkiuuvcoo7vbivkl1sg","time":"2024-12-23T09:38:03.283Z"}

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by EZLiM** [comment]
是IP封锁吗？我也碰到了类似的问题，请教下你怎么解决的

**Comment by EZLiM** [comment]
> /usr/local/bin/gost -L http://abc:xxx@:10288
> 
> {"client":"x.x.x.x","duration":7737409,"handler":"http","inputBytes":114,"kind":"handler","level":"info","listener":"tcp","local":"10.1.1.4:10288","msg":"x.x.x.x:45378 >< 10.1.1.4:10288","outputBytes":0,"remote":"x.x.x.x:45378","service":"service-0","sid":"ctkiuuvcoo7vbivkl1sg","time":"2024-12-23T09:38:03.283Z"} {"handler":"http","kind":"service","level":"error","listener":"tcp","msg":"write tcp 10.1.1.4:10288->x.x.x.x:45378: write: connection reset by peer","service":"service-0","sid":"ctkiuuvcoo7vbivkl1sg","time":"2024-12-23T09:38:03.283Z"}
> 
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

是IP封锁吗？我也碰到了类似的问题，请教下你怎么解决的？

**Comment by dnslin** [comment]
> > /usr/local/bin/gost -L http://abc:xxx@:10288
> > {"client":"x.x.x.x","duration":7737409,"handler":"http","inputBytes":114,"kind":"handler","level":"info","listener":"tcp","local":"10.1.1.4:10288","msg":"x.x.x.x:45378 >< 10.1.1.4:10288","outputBytes":0,"remote":"x.x.x.x:45378","service":"service-0","sid":"ctkiuuvcoo7vbivkl1sg","time":"2024-12-23T09:38:03.283Z"} {"handler":"http","kind":"service","level":"error","listener":"tcp","msg":"write tcp 10.1.1.4:10288->x.x.x.x:45378: write: connection reset by peer","service":"service-0","sid":"ctkiuuvcoo7vbivkl1sg","time":"2024-12-23T09:38:03.283Z"}
> > requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
> 
> 是IP封锁吗？我也碰到了类似的问题，请教下你怎么解决的？

无法解决 只能使用加密协议进行转发
