### ISSUE TITLE
[Feature Request] 增加 Deirect 转发

### ISSUE THREAD

**Issue by soffchen** [go-gost/gost#63]
用法:
`gost -L :8080 -F "direct://:0?interface=wg0"`

目的:
直接访问 wireguard 等 tap/tun 设备

glider 已实现，可以参考
https://github.com/nadoo/glider/blob/master/proxy/direct.go

`glider -listen :8443 -forward direct://#interface=eth0`

**Comment by ginuerzh** [comment]
https://gost.run/concepts/chain/#_5

**Comment by soffchen** [comment]
测试通过，命令行写法还真是 

```gost -L :9999 -F "direct://:0?interface=wg0"```

感谢~~~

**Comment by alpominth** [comment]
@soffchen

I tested with a Wireguard config here with no tables added (Table = off), it doesn't connect when specifying the interface in GOST, I guess IPv4 /32 and IPv6 /128 addresses need additional routes and tables for making them reachable (Wireguard use local IPs like this)

Install this script, run and follow the instructions: https://gist.github.com/alpominth/1314be7da682b13277241ceaf0ed9417

Run again:
`$ gost -L :9999 -F "direct://:0?interface=wg0"`

That script creates a supplementary route for Wireguard interface with a default gateway in the table created, so making  the Wireguard interface routable. You can modify that script as you wish, and even create a modified version of it and use with PostUp/PreDown options in the Wireguard config file.
