### ISSUE TITLE
http3无法接入cloudflare cdn

### ISSUE THREAD

**Issue by timwhitez** [go-gost/gost#632]
server:
./gost -L "http+h3://:443?bind=true"

cloudflare cdn接入后会显示Web server is down

**Comment by timwhitez** [comment]
cloudflare的问题

**Comment by ginuerzh** [comment]
如果是使用CF的HTTP/3加速，服务端需要使用pht或TLS加密的phts
```
gost -L http+pht://:80
```
或
```
gost -L http+phts://:443
```
