### ISSUE TITLE
配置架构优化

### ISSUE THREAD

**Issue by steamsv** [go-gost/gost#65]
您好，在使用过程中感觉配置过于复杂，很多专有名词无对应解释，也无完整示例解读；相较于v2使用门槛提高，大量配置需要反复测试才能确定，是否有对文档或配置架构进行优化的计划

**Comment by ginuerzh** [comment]
后面webui出来以后可以直接通过UI动态配置，文档会持续改善。

**Comment by m2acgi** [comment]
附议

配置过于复杂，很多专有名词无对应解释，也无完整示例解读；相较于v2使用门槛提高，大量配置需要反复测试才能确定

**Comment by ginuerzh** [comment]
V3版本相较于v2版本已经有非常大的变化，可以认为二者是不同的两个软件，只是在功能和使用方式上有些相似。
当需求变得复杂，就要求架构要更灵活，相应的会导致使用上的难度提升。但大部分情况是不需要很复杂的配置，可能一行命令就足够了，因此我觉得这不是问题。
