### ISSUE TITLE
来源IP白名单功能增加

### ISSUE THREAD

**Issue by steamsv** [go-gost/gost#7]
希望大大能增加这个功能，例如把ip存入redis并设置有效期，gost定时读取redis里的ip

**Comment by steamsv** [comment]
老哥，方便接私单吗，代码量大概在200行左右，甚至150不到，预算100u

**Comment by steamsv** [comment]
老大，我的想法是这样的，因为ip数量较多，大概上千个，而且是不断变动的。
我目前的方案是使用ipset iptables，设置每个ip的有效期，通过http api 提交ip到ipset，这样旧的就会被删除，而存在的就一直刷新有效期。

目前想到的适合gost的方案是，通过http api把ip提交到redis，gost定时获取redis里面的ip，并热更新，或者gost自带有效期设置；或者ip白名单放在文件里面，gost去获取热更新

**Comment by ginuerzh** [comment]
目前可以通过动态配置来更新ip列表，后面会支持redis

**Comment by cod1ingcoding** [comment]
用redis这类太重了， 用命令行如果来源太多，又不好书写，还是用iptables+ipset是最好的。

**Comment by ginuerzh** [comment]
已增加对外部文件和redis的支持：
https://latest.gost.run/concepts/admission/#_4

**Comment by perk67h6ins** [comment]
> 已增加对外部文件和redis的支持： https://latest.gost.run/concepts/admission/#_4

只能拒绝吗？匹配转发那块不能热更新？
