### ISSUE TITLE
建立relay+tls之后, 无法访问google/youtube

### ISSUE THREAD

**Issue by balzaron** [go-gost/gost#78]
1. 首先我在vps服务端上建立了relay+tls服务: nohup ./gost3 -L=relay+tls://user:password@:12345 &
2. 然后在windows的本地机器建立了一个客户端连接:  .\gost3.exe -L=socks5://user:pwd@:8082 -F=relay+tls://user:password@vps_ip:12345
然后看到流量的确从境外vps转发了, 但是google/youtube/Facebook不可以访问, 其他的一些境外网址倒是可以连接.
请问这是啥原因? 请指教谢谢

**Comment by balzaron** [comment]
{"handler":"relay","kind":"handler","level":"error","listener":"wss","msg":"route(retry=0) dial tcp 106.15.196.123:80: i/o timeout","service":"service-0","time":"2022-08-21T09:12:58.234Z"}
{"duration":17264660495,"handler":"relay","kind":"handler","level":"info","listener":"tls","local":"","msg":"121.31.136.53:52415 >< ","remote":"121.31.136.53:52415","service":"service-0","time":"2022-08-21T09:12:58.234Z","user":"lf123123"}
{"handler":"relay","kind":"service","level":"error","listener":"wss","msg":"dial tcp 106.15.196.123:80: i/o timeout","service":"service-0","time":"2022-08-21T09:12:58.234Z"}

**Comment by ginuerzh** [comment]
请查看是否为DNS问题。
