### ISSUE TITLE
SNI协议仅在443端口正常

### ISSUE THREAD

**Issue by zhenjie1022** [go-gost/gost#79]
经过测试SNI有比其他协议更低的延迟，但仅在443端口正常，希望支持其他端口，目前我通过监听其他端口转发到443来使用，稍显不便

**Comment by ginuerzh** [comment]
仅能用443端口是什么意思？

**Comment by zhenjie1022** [comment]
当时用得时候报错信息提示监听443端口才能正常工作，用其他端口确实不通

**Comment by ginuerzh** [comment]
目前最新的版本测试下来没有以上问题。
