### ISSUE TITLE
请教一个多地址端口转发问题

### ISSUE THREAD

**Issue by sakuyamaij** [go-gost/gost#80]
版本：v3.0.0-beta.3
使用场景如下，A平台和B平台的rtmp推流直播（rtmp为端口1935的tcp）
假设分别对应为rtmp://A和rtmp://B

需要将RTMP的tcp数据走代理，并做本地端口转发
目前分成两个命令
-L=tcp://:1935/A:1935 -F=socks://...
-L=tcp://:1935/B:1935 -F=socks://...
在哪个平台直播时，就运行对应的命令

想实现一行命令直接对应2个平台
于是使用
-L=tcp://:1935/A:1935,B:1935 -F=socks://...

发现有时会出现问题
直播软件往A平台推流，gost日志显示转发到B平台上去了
或者B的流转发到A平台上去
会偶尔出现这样的问题，请问是我参数设置的不对么？
麻烦指教，感谢

**Comment by zhenjie1022** [comment]
-L=tcp://:1935/A:1935,B:1935 -F=socks://...
你这样本来就是把本地1935端口的数据同时转发到A和B
你的需求我认为程序不能实现，程序是无法判断你想往哪个平台推流的

**Comment by ginuerzh** [comment]
端口转发无法根据数据流来指定具体的转发目标地址。
