### ISSUE TITLE
可否实现只要白名单IP和用户密码任何一个满足要求即可上网？

### ISSUE THREAD

**Issue by raintears2** [go-gost/gost#84]
如果同时设置白名单IP和用户密码认证，则在白名单里的用户IP还是需要通过用户密码认证才能上网。
可否同时支持IP认证和账号密码认证，即只要绑定客户端IP或用户密码任何一个满足要求即可上网？

**Comment by sxchxdc** [comment]
同求楼主添加

**Comment by ginuerzh** [comment]
可以通过[插件系统](https://gost.run/concepts/plugin/)来自定义业务逻辑。
