### ISSUE TITLE
使用Dependabot来自动更新依赖

### ISSUE THREAD

**Issue by Tsukimeizi** [go-gost/gost#85]
自己编译时用go get -u ./...更新所有依赖发现不少组件都有更新，比如：quic-go v0.28.1 => v0.29.0 grpc v1.45.0 => v1.49.0 等...

建议使用github的Dependabot来自动更新依赖。

**Comment by Tsukimeizi** [comment]
刚刚更新了所有依赖，编译成功。

服务端使用更新依赖的版本+本地使用更新依赖的版本，报错：
./gost -L socks://:1080 -F relay+grpc://XXX.XXX:3002 
{"level":"warning","msg":"load global TLS certificate files failed, use random generated certificate","time":"2022-08-28T23:02:19.517+08:00"}
{"handler":"socks","kind":"service","level":"info","listener":"tcp","msg":"listening on [::]:1080/tcp","service":"service-0","time":"2022-08-28T23:02:19.517+08:00"}
{"handler":"socks","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:1080","msg":"127.0.0.1:58533 <> 127.0.0.1:1080","remote":"127.0.0.1:58533","service":"service-0","time":"2022-08-28T23:02:22.418+08:00"}
{"handler":"socks","kind":"handler","level":"error","listener":"tcp","msg":"EOF","service":"service-0","time":"2022-08-28T23:02:22.419+08:00"}
{"handler":"socks","kind":"handler","level":"error","listener":"tcp","local":"127.0.0.1:1080","msg":"EOF","remote":"127.0.0.1:58533","service":"service-0","time":"2022-08-28T23:02:22.419+08:00"}
{"duration":2184666,"handler":"socks","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:1080","msg":"127.0.0.1:58533 >< 127.0.0.1:1080","remote":"127.0.0.1:58533","service":"service-0","time":"2022-08-28T23:02:22.419+08:00"}

服务端使用更新依赖的版本+本地使用beta3，正常：
./gost-darwin-arm64-3.0.0-beta.3 -L socks://:1080 -F relay+grpc://XXX.XXX:3002
{"level":"warning","msg":"load global TLS certificate files failed, use random generated certificate","time":"2022-08-28T23:01:59.692+08:00"}
{"handler":"socks","kind":"service","level":"info","listener":"tcp","msg":"listening on [::]:1080/tcp","service":"service-0","time":"2022-08-28T23:01:59.692+08:00"}
{"handler":"socks","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:1080","msg":"127.0.0.1:58517 <> 127.0.0.1:1080","remote":"127.0.0.1:58517","service":"service-0","time":"2022-08-28T23:02:00.774+08:00"}

**Comment by ginuerzh** [comment]
有些依赖库并不是稳定版，有兼容性问题，自动更新有可能会导致编译失败。
