### ISSUE TITLE
Forward tun 2 Socks5

### ISSUE THREAD

**Issue by kontorol** [go-gost/gost#86]
Hello , How i need Proxy Windows Clients TCP/UDP packate to server and forward Package To Socks5 Proxy . But in client tap driver restart continusly . Pls Help Me . thans .
Server: gost -L=tun://:8421?net=192.168.123.1/24 -L="relay+grpc://user:pass@:8443?udp=true" -F="socks5://192.168.168.211:1818"

Client: gost -L="tun://:0/:8421?net=192.168.123.2/24" -F="relay+grpc://user:pass@192.168.168.1:8443"

Log:
{"level":"warning","msg":"load global TLS certificate files failed, use random generated certificate","time":"2022-08-29T18:26:32.193-07:00"}
{"handler":"tun","kind":"service","level":"info","listener":"tun","msg":"listening on :0/udp","service":"service-0","time":"2022-08-29T18:26:32.194-07:00"}
2022/08/29 18:26:32 Using existing driver 0.14
2022/08/29 18:26:32 Creating adapter
{"handler":"tun","kind":"listener","level":"info","listener":"tun","msg":"name: wintun, net: 192.168.123.2, mtu: 65535, addrs: [fe80::b5fb:fc3e:6ca0:2613/64 192.168.123.2/24]","service":"service-0","time":"2022-08-29T18:26:33.416-07:00"}
{"handler":"tun","kind":"handler","level":"info","listener":"tun","local":":0","msg":"192.168.123.2 <> :0","remote":"192.168.123.2","service":"service-0","time":"2022-08-29T18:26:33.416-07:00"}
{"dst":":8421/udp","duration":13006200,"handler":"tun","kind":"handler","level":"info","listener":"tun","local":":0","msg":"192.168.123.2 >< :0","remote":"192.168.123.2","service":"service-0","time":"2022-08-29T18:26:33.429-07:00"}
2022/08/29 18:26:34 Using existing driver 0.14
2022/08/29 18:26:34 Creating adapter
{"handler":"tun","kind":"listener","level":"info","listener":"tun","msg":"name: wintun, net: 192.168.123.2, mtu: 65535, addrs: [fe80::3c7d:2c21:c84d:fe1b/64 192.168.123.2/24]","service":"service-0","time":"2022-08-29T18:26:35.039-07:00"}
{"handler":"tun","kind":"handler","level":"info","listener":"tun","local":":0","msg":"192.168.123.2 <> :0","remote":"192.168.123.2","service":"service-0","time":"2022-08-29T18:26:35.039-07:00"}
{"dst":":8421/udp","duration":271906600,"handler":"tun","kind":"handler","level":"info","listener":"tun","local":":0","msg":"192.168.123.2 >< :0","remote":"192.168.123.2","service":"service-0","time":"2022-08-29T18:26:35.311-07:00"}
2022/08/29 18:26:36 Using existing driver 0.14
2022/08/29 18:26:36 Creating adapter
{"handler":"tun","kind":"listener","level":"info","listener":"tun","msg":"name: wintun, net: 192.168.123.2, mtu: 65535, addrs: [fe80::2803:5bb8:e68b:eea1/64 192.168.123.2/24]","service":"service-0","time":"2022-08-29T18:26:36.941-07:00"}
{"handler":"tun","kind":"handler","level":"info","listener":"tun","local":":0","msg":"192.168.123.2 <> :0","remote":"192.168.123.2","service":"service-0","time":"2022-08-29T18:26:36.941-07:00"}
{"dst":":8421/udp","duration":5121800,"handler":"tun","kind":"handler","level":"info","listener":"tun","local":":0","msg":"192.168.123.2 >< :0","remote":"192.168.123.2","service":"service-0","time":"2022-08-29T18:26:36.947-07:00"}
2022/08/29 18:26:38 Using existing driver 0.14
2022/08/29 18:26:38 Creating adapter
{"handler":"tun","kind":"listener","level":"info","listener":"tun","msg":"name: wintun, net: 192.168.123.2, mtu: 65535, addrs: [fe80::e1:75d0:89a0:55d3/64 192.168.123.2/24]","service":"service-0","time":"2022-08-29T18:26:38.567-07:00"}
{"handler":"tun","kind":"handler","level":"info","listener":"tun","local":":0","msg":"192.168.123.2 <> :0","remote":"192.168.123.2","service":"service-0","time":"2022-08-29T18:26:38.567-07:00"}
{"dst":":8421/udp","duration":263946100,"handler":"tun","kind":"handler","level":"info","listener":"tun","local":":0","msg":"192.168.123.2 >< :0","remote":"192.168.123.2","service":"service-0","time":"2022-08-29T18:26:38.831-07:00"}

**Comment by ginuerzh** [comment]
TUN server does not use chain to forward data.

**Comment by kontorol** [comment]
what is the best way to Proxy Windows Clients packates (TCP/UDP) to server and forward Package To Socks5 Proxy ?
