### ISSUE TITLE
最新源码编译出的beta.4的两处bug

### ISSUE THREAD

**Issue by waloyn** [go-gost/gost#87]
系统环境：
windows11 和  debian10.2

go版本：
go version go1.19 windows/amd64

gost版本：
windows:  gost 3.0.0-beta.4 (go1.19 windows/amd64)
debian:     gost 3.0.0-beta.4 (go1.19 linux/amd64)

ps:
debian下测试的gost使用的是windows下交叉编译的。

bug1:
配置文件中加入log节的话，gost启动过程会卡住导致无法启动，windows和debian都会卡住。

bug2:
处理器socks5直接无法使用，所有连接均提示以下错误信息：
`{"handler":"socks5","kind":"service","level":"error","listener":"tcp","msg":"EOF","service":"service-0","time":"2022-08-30T10:24:50.840+08:00"}
`

**Comment by waloyn** [comment]
使用github下载的beta.4测试，同样存在上述2处bug.
1.    最简单的命令行 ./gost -L socks5://:1080
2.   使用配置文件，添加log节，程序卡住

**Comment by ginuerzh** [comment]
SOCKS5已修复。
Log卡住无法复现，配置文件可否贴出来看看。

**Comment by waloyn** [comment]
> SOCKS5已修复。 Log卡住无法复现，配置文件可否贴出来看看。

`services:
- name: service-0
  addr: :1080
  handler:
    type: socks5
  listener:
    type: tcp
log:
  level: error
  format: json
  output: stderr`

![b](https://user-images.githubusercontent.com/20416585/188265052-5f9f0666-04e7-449b-8c2b-adf0b8becbc4.png)

**Comment by ginuerzh** [comment]
这是正常的，error级别只会输出错误级别的日志。

**Comment by waloyn** [comment]
> 这是正常的，error级别只会输出错误级别的日志。

知道问题所在了，之前是使用服务方式，启动后会有进程名显示，这次因为socks5不通，所以使用cli方式运行，任务管理器里看不到进程，就以为是没启动，实际是启动了，只是socks5不通。
