### ISSUE TITLE
命令行多服务共用一条转发链

### ISSUE THREAD

**Issue by zhenjie1022** [go-gost/gost#88]
服务端：gost -L socks5+wss://:1080
客户端：gost -L auto://:1080?bypass=~127.0.0.1 -L auto://:1081 -F socks5+wss://服务端地址:1080
文档里多转发链需要用配置文件，但是多服务共用一条转发链的情况没有提及，做了以上尝试运行一分钟后开始出错

**Comment by ginuerzh** [comment]
具体报什么错？

**Comment by zhenjie1022** [comment]
"level":"error"

**Comment by zhenjie1022** [comment]
gost    8033 root  722u  IPv4 6247515      0t0  TCP 004401FF0001007006B960D21C58C188:53233->服务器IP:端口 (ESTABLISHED)
gost    8033 root  724u  IPv4 6249474      0t0  TCP 004401FF0001007006B960D21C58C188:53234->服务器IP:端口 (ESTABLISHED)
gost    8033 root  726u  IPv4 6249487      0t0  TCP 004401FF0001007006B960D21C58C188:53235->服务器IP:端口 (ESTABLISHED)
gost    8033 root  728u  IPv4 6246246      0t0  TCP 004401FF0001007006B960D21C58C188:53236->服务器IP:端口 (ESTABLISHED)
gost    8033 root  730u  IPv4 6246304      0t0  TCP 004401FF0001007006B960D21C58C188:53237->服务器IP:端口 (ESTABLISHED)
gost    8033 root  732u  IPv4 6246362      0t0  TCP 004401FF0001007006B960D21C58C188:53238->服务器IP:端口 (ESTABLISHED)
gost    8033 root  734u  IPv4 6249630      0t0  TCP 004401FF0001007006B960D21C58C188:53239->服务器IP:端口 (ESTABLISHED)
gost    8033 root  736u  IPv4 6249698      0t0  TCP 004401FF0001007006B960D21C58C188:53240->服务器IP:端口 (ESTABLISHED)
gost    8033 root  738u  IPv4 6248085      0t0  TCP 004401FF0001007006B960D21C58C188:53241->服务器IP:端口 (ESTABLISHED)
gost    8033 root  740u  IPv4 6249740      0t0  TCP 004401FF0001007006B960D21C58C188:53242->服务器IP:端口 (ESTABLISHED)
gost    8033 root  741u  IPv6 6248702      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39924 (CLOSE_WAIT)
gost    8033 root  742u  IPv4 6250610      0t0  TCP 004401FF0001007006B960D21C58C188:53243->服务器IP:端口 (ESTABLISHED)
gost    8033 root  743u  IPv6 6248227      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39932 (CLOSE_WAIT)
gost    8033 root  744u  IPv4 6250675      0t0  TCP 004401FF0001007006B960D21C58C188:53244->服务器IP:端口 (ESTABLISHED)
gost    8033 root  745u  IPv6 6248420      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39940 (CLOSE_WAIT)
gost    8033 root  746u  IPv4 6248765      0t0  TCP 004401FF0001007006B960D21C58C188:53245->服务器IP:端口 (ESTABLISHED)
gost    8033 root  747u  IPv4 6251560      0t0  TCP 004401FF0001007006B960D21C58C188:53246->服务器IP:端口 (ESTABLISHED)
gost    8033 root  748u  IPv6 6251557      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39946 (CLOSE_WAIT)
gost    8033 root  749u  IPv6 6251611      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39952 (CLOSE_WAIT)
gost    8033 root  750u  IPv4 6250900      0t0  TCP 004401FF0001007006B960D21C58C188:53247->服务器IP:端口 (ESTABLISHED)
gost    8033 root  751u  IPv6 6251659      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39956 (CLOSE_WAIT)
gost    8033 root  752u  IPv4 6251662      0t0  TCP 004401FF0001007006B960D21C58C188:53248->服务器IP:端口 (ESTABLISHED)
gost    8033 root  753u  IPv6 6251099      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39962 (CLOSE_WAIT)
gost    8033 root  754u  IPv4 6248864      0t0  TCP 004401FF0001007006B960D21C58C188:53249->服务器IP:端口 (ESTABLISHED)
gost    8033 root  755u  IPv6 6251101      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39964 (CLOSE_WAIT)
gost    8033 root  756u  IPv4 6251104      0t0  TCP 004401FF0001007006B960D21C58C188:53250->服务器IP:端口 (ESTABLISHED)
gost    8033 root  757u  IPv6 6251181      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39968 (CLOSE_WAIT)
gost    8033 root  758u  IPv4 6251842      0t0  TCP 004401FF0001007006B960D21C58C188:53251->服务器IP:端口 (ESTABLISHED)
gost    8033 root  759u  IPv6 6251212      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39976 (CLOSE_WAIT)
gost    8033 root  760u  IPv4 6251899      0t0  TCP 004401FF0001007006B960D21C58C188:53252->服务器IP:端口 (ESTABLISHED)
gost    8033 root  761u  IPv6 6250338      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39984 (CLOSE_WAIT)
gost    8033 root  762u  IPv4 6252004      0t0  TCP 004401FF0001007006B960D21C58C188:53253->服务器IP:端口 (ESTABLISHED)
gost    8033 root  763u  IPv6 6252128      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39988 (CLOSE_WAIT)
gost    8033 root  764u  IPv4 6251377      0t0  TCP 004401FF0001007006B960D21C58C188:53254->服务器IP:端口 (ESTABLISHED)
gost    8033 root  765u  IPv6 6252169      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39994 (CLOSE_WAIT)
gost    8033 root  766u  IPv4 6249204      0t0  TCP 004401FF0001007006B960D21C58C188:53255->服务器IP:端口 (ESTABLISHED)
gost    8033 root  767u  IPv6 6252195      0t0  TCP 004401FF0001007006B960D21C58C188:2096->局域网主机:39996 (CLOSE_WAIT)
gost    8033 root  768u  IPv4 6250426      0t0  TCP 004401FF0001007006B960D21C58C188:53256->服务器IP:端口 (ESTABLISHED)

**Comment by ginuerzh** [comment]
可以使用最新的master 分支试一试

**Comment by zhenjie1022** [comment]
用得就是v3.0.0-beta.3，将服务端换成2.11.3还是一样

**Comment by zhenjie1022** [comment]
经过认真测试得出结论，有非常多不活跃的转发隧道不会被关闭造成连接数过多，占用系统资源

**Comment by openwrt2223** [comment]
@zhenjie1022 测试

**Comment by zhenjie1022** [comment]
@openwrt2223 ?

**Comment by openwrt2223** [comment]
@zhenjie1022 字面意思。

**Comment by ginuerzh** [comment]
这个问题是在beta.3中引入，最新的提交已经修正。

**Comment by zhenjie1022** [comment]
上述问题编译新版本测试已解决，但是我这里有一个socks5客户端报错no accepted authentication method，之前的版本是没有问题的，不知道是不是我编译的有问题
