### ISSUE TITLE
gost v3 socks的bug，能100%复现

### ISSUE THREAD

**Issue by aa51513** [go-gost/gost#95]
版本gost v3 beta4
服务：socks5+tcp
转发链：relay+mwss

出现问题：

用curl测试socks5，第一次正常，后面就一直提示“can't complete socks5 connection to 0.0.0.0:0”
[root@201.117.23.11 ~]# time curl -vvv -4 --socks5 172.21.14.33:22022 http://www.msftconnecttest.com/connecttest.txt
*   Trying 172.21.14.33...
* TCP_NODELAY set
* SOCKS5 communication to www.msftconnecttest.com:80
* SOCKS5 connect to IPv4 23.202.34.242 (locally resolved)
* Can't complete SOCKS5 connection to 0.0.0.0:0. (3)
* Closing connection 0
curl: (7) Can't complete SOCKS5 connection to 0.0.0.0:0. (3)

服务端gost节点日志：
{"handler":"relay","kind":"listener","level":"error","listener":"mws","msg":"accept stream: websocket: close 1006 (abnormal closure): unexpected EOF","service":"service-1","time":"2022-09-07T23:22:39.876-04:00"}

重启gost后，第一次正常，后面又是这个错误

疑似不会自动重连？

**Comment by kingwilliam** [comment]
https://github.com/go-gost/gost/issues/92
