### ISSUE TITLE
gost v3 API提交services 到一定数量则返回 403 object creation failed.

### ISSUE THREAD

**Issue by lcl520123** [go-gost/gost#96]
gost v3 API提交services 到一定数量则返回 403 object creation failed.
是否因为API有限制?
能否解决呢?

**Comment by ginuerzh** [comment]
API没有限制，这个错误应该是解析配置出错，有错误日志吗？

**Comment by lcl520123** [comment]
> API没有限制，这个错误应该是解析配置错误，有错误日志吗？
{"caller":"parsing/service.go:74","handler":"auto","kind":"listener","level":"error","listener":"tcp","msg":"init: listen tcp :50956: bind: address already in use","service":"50956","time":"2022-09-10T11:41:23+08:00"}
{"caller":"parsing/service.go:74","handler":"auto","kind":"listener","level":"error","listener":"tcp","msg":"init: listen tcp :50958: bind: address already in use","service":"50958","time":"2022-09-10T11:41:23+08:00"}
{"caller":"parsing/service.go:74","handler":"auto","kind":"listener","level":"error","listener":"tcp","msg":"init: listen tcp :50960: bind: address already in use","service":"50960","time":"2022-09-10T11:41:23+08:00"}
{"caller":"parsing/service.go:74","handler":"auto","kind":"listener","level":"error","listener":"tcp","msg":"init: listen tcp :50962: bind: address already in use","service":"50962","time":"2022-09-10T11:41:23+08:00"}

这是错误日志.提示初始化端口被占用,但是我能肯定没有被占用. 现在的错误是比如我提交 1000条API,总会有一些错误失败. 但是我批量删除的API又一点问题都没有,随便提交多少都是可以成功的.

**Comment by lcl520123** [comment]
@ginuerzh  能留个联系方式吗? QQ或者WX,方便交流一下吧。或者你加我QQ:100201244

**Comment by lcl520123** [comment]
@ginuerzh 找到了错误地点了.API提交返回:
[31m2022/09/12 23:52:59 [Recovery] 2022/09/12 - 23:52:59 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:260 (0x452495)
/usr/local/go/src/runtime/signal_windows.go:255 (0x452465)
/home/gerry/code/go-gost/x/config/parsing/service.go:145 (0xb76587)
/home/gerry/code/go-gost/x/api/config_service.go:48 (0xb82844)
/home/gerry/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x9ce2a1)

/home/gerry/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x9ce28c)

/home/gerry/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x9cd150)

/home/gerry/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x9ccdb8)
/home/gerry/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x9cc8f1)
/usr/local/go/src/net/http/server.go:2947 (0x762c2b)
/usr/local/go/src/net/http/server.go:1991 (0x75de46)
/usr/local/go/src/runtime/asm_amd64.s:1594 (0x46faa0)
[0m

**Comment by ginuerzh** [comment]
提交的数据是什么?可以用beta.5试试。
