### ISSUE TITLE
动态 node source

### ISSUE THREAD

**Issue by helloworldyuhaiyang** [go-gost/gost#98]
你好，想讨论一个  feature的使用场景。
## 背景:
    我有比较多的 vps。部署 gost 作为代理池，代理池里的vps 每2min **IP 会变化** 。现在希望通过一个总的代理(部署gost 并且ip不会变化)来进行代理访问网络。如下图。

<img width="847" alt="图片" src="https://user-images.githubusercontent.com/10350492/190547647-5b478303-50f1-4463-8858-f5493d292cdf.png">

## 当前实现:
当前的 gost -F 的方式指定的下级代理都是静态的。
```
type Forwarder interface {
	Forward(*chain.NodeGroup)
}
```

## 一个初步的方案:
可以给 Forwarder 一个 NodeSource interface 来获取 *NodeGroup ,而不是在构造 handler 的时候给赋值一个初始化好的 NodeGroup。
```

type NodeSource interface {
 	Get() *NodeGroup
}

type Forwarder interface {
	Forward(source NodeSource)
}
```
而我们的 NodeSource 可以有扩展各种实现类。 例如其中的 StaticNodeSource 可以作为我们之前从配置和命令行读出来的 NodeGroup。提供的 RedisNodeSource, 和 HttpNodeSource 两个基本的实现。后面有定制化的需求也可以根据自己的需要增加实现类。

<img width="812" alt="图片" src="https://user-images.githubusercontent.com/10350492/190548643-b5e1c009-1af5-43cf-abf7-a44aaf1751c8.png">

## 最后:
感谢作者分享这么好的开源软件(特别是 gost V3)。希望有机会一起参与成为这个 commiter。

**Comment by ginuerzh** [comment]
可以考虑这种方式

**Comment by helloworldyuhaiyang** [comment]
准备做之前仔细看了下，有几个问题想要确认下。
1. -F 影响的 Router 里的 Chainer 好像才是转发的关键。通过这个 Chainer 构建出的 net.Conn。相关接口: type Chainer interface {
2.  -L=tcp://:8080/192.168.1.1:80 这种方式是通过上面构建出来的左右一层的 connector去 connet 真正的目标然后数据透传数据。

3.  如果上面是正确的那么我们有两种方案:

每次都会经过 chainer.Route() 构造的一个全新的 router 来做 Dial() 到真正的落地目标。

			route = r.chain.Route(ctx, network, address)
- 方案1：增加一个 Channer 的实现类DynamicChanner 生成的 Route 是根据动态数据源生成的。			

- 方案2: 可否通过增强当前 Chain 来从判断如果是 dynamic 模式则从动态	Route 根据动态数据源生成的。

**Comment by ginuerzh** [comment]
目前整个转发链的各个子模块之间关系如下：
所有Service(Listener/Handler)统一通过Router来建立连接(Dial/Bind)，Router中通过Chainer获取一个Route，再通过Route中的Nodes逐一连接到目标地址。

一个Chainer由一组Hop组成(之前是NodeGroup)，每个Hop作为转发链的一个层级拥有一组Nodes。端口转发中的转发器(Forwarder)同样也改为Hop作为转发目标。

目前的设计是在Hop级别支持热加载，这样可兼顾转发链和转发器。Chainer级别可以通过动态配置进行修改。

基本框架已经有了：https://github.com/go-gost/x/blob/master/chain/hop.go
现在要考虑的是数据源中的数据存储格式，由于Hop的信息较多，目前倾向于直接以yaml格式存储会比较灵活。

**Comment by helloworldyuhaiyang** [comment]
gost 作为转发为核心的项目用 Router 做为核心好像确实更符合抽象。
Forwarder 的功能也确实挺像是 Hop 的子集。
这样重构之后，就不会我之前的问题。是在 Forwarder 扩展，还是在Router 中做更改。

至于数据源相关的配置。我先把最新代理拉下来，学习一下。

另外两个问题: 
1. 有大约的计划啥时候发布吗。
2. 有进展或者想法可以在这个 issue 同步下。让我慢慢了解一些设计思路。比死看代码方便多了。[呲牙]

**Comment by ginuerzh** [comment]
你的使用场景需求用动态配置会更合适，动态配置是实时生效的，而热加载是周期性的同步数据源，有一定的滞后性。
Hop已经支持动态配置功能：https://gost.run/concepts/hop/
如果能够检测到IP变化，可以通过动态配置来更新hop以便快速生效。

**Comment by helloworldyuhaiyang** [comment]
是的。通过动态配置的方式应该是可以满足当前的场景。

**Comment by helloworldyuhaiyang** [comment]
你好在实践动态配置的过程中的一些思考。
### 方案1：动态配置:
   我觉得通过动态配置的方式思路上感觉也蛮像 service mesh 的数据层。但遇到了一个问题。如果有多个 gost 节点，是需要一个注册中心的组件。每个gost 启动的时候去注册。配置更新之后，才能够知道需要通知到哪 gost 在什么位置。这种方式的缺点就是另外的程序实现发现和通知机制。

### 方案2: 实现 chain.Hop 接口的RedisHop
  为了避免上面增加注册中心的负担。增加 RedisHop方式实现了 chain.Hop 接口。Select() 时候调用自己的 Nodes()方法实现从 redis 里取当前可用的 node 信息返回。这种方式缺点是只能实现指定为 RedisHop 的 hop 实现数据热加载。

### 方案3: 周期性同步方案
   至于你说的周期性同步方案。你也说过有一定的滞后性。

### 方案4:观察者模式
   参考了一下热加载做的比较好的开源软件 [trafix()](https://github.com/traefik/traefik) 的实现思路。
我们服务核心启动的时候启动一个ConfWatcher 观察者模式。
通过各种 provicer 实现类获取config.Config，调用各个 Listener。
#### Provider:
    这样你当前在实现的 api 部分和热加载配置文件部分都可以作为 provicer的实现类。而我也可以实现 remoteGost(动态检查) 或者更简单的 redis 实现 provider 类。

#### Listener:
   需要热更新的组件。ServerRegistry, ChainRegistry, HopRegistry 也可以把 limiter auth 等相关的可以热更新的都实现一个 LIstener。

#### uml 类图:
<img width="1153" alt="图片" src="https://user-images.githubusercontent.com/10350492/194838954-bb0a3f19-6233-45c7-9f9e-1a2653db711a.png">

**Comment by ginuerzh** [comment]
从实现角度来说，方案2是比较好的选择。
方案4更灵活，扩展性强，但改动会很大。

**Comment by helloworldyuhaiyang** [comment]
方案4，感觉应该主要是扩展。各个需要热更新模块增加一个 listener 来获取最新的配置。至于观察者纯新增代码了，不会影响到原逻辑。前期完全可以兼容当前 api 热更新和配置文件热更。而且很多代码可以参考 traefix 的实现。

如果你觉得方案4可以最终 merage 到主分支。我这边可以来做实现。

**Comment by ginuerzh** [comment]
转发链中的跳跃点(Hop)已经支持从外部数据源动态获取节点列表。
同时也支持插件服务，将节点的选择完全交给插件处理。
https://gost.run/concepts/hop/
